In [3]:
from bs4 import BeautifulSoup as bs
import pandas as pd
import request as r

{'Date': 'Sun, 01 Feb 2026 12:31:33 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=XK5zrAEeaB33y%2B%2F6KdqZKXaPL7ehQfhxeoxOyzRBVog%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1769949093"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=XK5zrAEeaB33y%2B%2F6KdqZKXaPL7ehQfhxeoxOyzRBVog%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1769949093"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9c717765aa9b705c-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

In [4]:
with open("scraped_data/data1.html","r") as f:
    html_content=f.read()
print(html_content)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="countries">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>
                            <strong>Population:</strong> <span class="country-population">84000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>
                            <strong>Population:</strong> <span class="country-population">4975593</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>
                            <strong>Population:</strong> <span class="country-population">29121286</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>
                            <strong>Population:</strong> <span class="country-population">86754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>
                            <strong>Population:</strong> <span class="country-population">13254</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>
                            <strong>Population:</strong> <span class="country-population">2986952</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>
                            <strong>Population:</strong> <span class="country-population">2968000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>
                            <strong>Population:</strong> <span class="country-population">13068161</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">None</span><br>
                            <strong>Population:</strong> <span class="country-population">0</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>
                            <strong>Population:</strong> <span class="country-population">41343201</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>
                            <strong>Population:</strong> <span class="country-population">57881</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>
                            <strong>Population:</strong> <span class="country-population">8205000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
                            <strong>Population:</strong> <span class="country-population">21515754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>
                            <strong>Population:</strong> <span class="country-population">71566</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>
                            <strong>Population:</strong> <span class="country-population">26711</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>
                            <strong>Population:</strong> <span class="country-population">8303512</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>
                            <strong>Population:</strong> <span class="country-population">4590000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>
                            <strong>Population:</strong> <span class="country-population">285653</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br>
                            <strong>Population:</strong> <span class="country-population">156118464</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Brussels</span><br>
                            <strong>Population:</strong> <span class="country-population">10403000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br>

In [5]:
soup=bs(html_content,'lxml')

In [6]:
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

In [7]:
soup.find("h1")

<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>

In [8]:
soup.find("h3")

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [9]:
# soup.find_all("h3")
all_h3=soup.find_all("h3")
type(all_h3)
all_h3

[<h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ci"></i>
                             Ivory Coast
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ck"></i>
                             Cook Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cl"></i>
                             Chile
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cm"></i>
                             Cameroon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cn"></i>
                             China
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-co"></i>
                             Colombia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cr"></i>
                             Costa Rica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cu"></i>
                             Cuba
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cv"></i>
                             Cape Verde
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cw"></i>
                             Curacao
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cx"></i>
                             Christmas Island
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cy"></i>
                             Cyprus
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cz"></i>
                             Czech Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-de"></i>
                             Germany
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dj"></i>
                             Djibouti
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dk"></i>
                             Denmark
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dm"></i>
                             Dominica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-do"></i>
                             Dominican Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dz"></i>
                             Algeria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ec"></i>
                             Ecuador
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ee"></i>
                             Estonia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eg"></i>
                             Egypt
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eh"></i>
                             Western Sahara
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-er"></i>
                             Eritrea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-es"></i>
                             Spain
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-et"></i>
                             Ethiopia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fi"></i>
                             Finland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fj"></i>
                             Fiji
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fk"></i>
                             Falkland Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fm"></i>
                             Micronesia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fo"></i>
                             Faroe Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fr"></i>
                             France
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ga"></i>
                             Gabon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gb"></i>
                             United Kingdom
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gd"></i>
                             Grenada
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ge"></i>
                             Georgia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gf"></i>
                             French Guiana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gg"></i>
                             Guernsey
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gh"></i>
                             Ghana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gi"></i>
                             Gibraltar
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gl"></i>
                             Greenland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gm"></i>
                             Gambia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gn"></i>
                             Guinea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gp"></i>
                             Guadeloupe
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gq"></i>
                             Equatorial Guinea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gr"></i>
                             Greece
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gs"></i>
                             South Georgia and the South Sandwich Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gt"></i>
                             Guatemala
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gu"></i>
                             Guam
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gw"></i>
                             Guinea-Bissau
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gy"></i>
                             Guyana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hk"></i>
                             Hong Kong
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hm"></i>
                             Heard Island and McDonald Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hn"></i>
                             Honduras
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hr"></i>
                             Croatia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ht"></i>
                             Haiti
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hu"></i>
                             Hungary
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-id"></i>
                             Indonesia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ie"></i>
                             Ireland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-il"></i>
                             Israel
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-im"></i>
                             Isle of Man
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-in"></i>
                             India
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-io"></i>
                             British Indian Ocean Territory
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-iq"></i>
                             Iraq
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ir"></i>
                             Iran
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-is"></i>
                             Iceland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-it"></i>
                             Italy
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-je"></i>
                             Jersey
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jm"></i>
                             Jamaica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jo"></i>
                             Jordan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jp"></i>
                             Japan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ke"></i>
                             Kenya
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kg"></i>
                             Kyrgyzstan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kh"></i>
                             Cambodia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ki"></i>
                             Kiribati
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-km"></i>
                             Comoros
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kn"></i>
                             Saint Kitts and Nevis
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kp"></i>
                             North Korea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kr"></i>
                             South Korea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kw"></i>
                             Kuwait
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ky"></i>
                             Cayman Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kz"></i>
                             Kazakhstan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-la"></i>
                             Laos
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lb"></i>
                             Lebanon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lc"></i>
                             Saint Lucia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-li"></i>
                             Liechtenstein
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lk"></i>
                             Sri Lanka
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lr"></i>
                             Liberia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ls"></i>
                             Lesotho
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lt"></i>
                             Lithuania
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lu"></i>
                             Luxembourg
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lv"></i>
                             Latvia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ly"></i>
                             Libya
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ma"></i>
                             Morocco
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mc"></i>
                             Monaco
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-md"></i>
                             Moldova
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-me"></i>
                             Montenegro
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mf"></i>
                             Saint Martin
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mg"></i>
                             Madagascar
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mh"></i>
                             Marshall Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mk"></i>
                             Macedonia
                         </h3>,
 <h3 class="country-name">

In [10]:
for h3 in all_h3:
    # print(h3)
    name=print(h3.get_text(strip=True))
    print(h3.findParent("div"))
    print(h3.findParent("div")["class"])

Andorra
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div>
['col-md-4', 'country']
United Arab Emirates
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Afghanistan
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Antigua and Barbuda
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Anguilla
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Albania
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Armenia
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Angola
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Antarctica
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div>
['col-md-4', 'country']
Argentina
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div>
['col-md-4', 'country']
American Samoa
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Austria
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Australia
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Aruba
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Åland
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Azerbaijan
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Bosnia and Herzegovina
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Barbados
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Bangladesh
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Belgium
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Burkina Faso
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Bulgaria
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Bahrain
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Burundi
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Benin
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Saint Barthélemy
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Bermuda
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Brunei
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Bolivia
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Bonaire
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Brazil
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Bahamas
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Bhutan
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Bouvet Island
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Botswana
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bw"></i>
                            Botswana
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
<strong>Population:</strong> <span class="country-population">2029307</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Belarus
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-by"></i>
                            Belarus
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
<strong>Population:</strong> <span class="country-population">9685000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Belize
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bz"></i>
                            Belize
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
<strong>Population:</strong> <span class="country-population">314522</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Canada
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ca"></i>
                            Canada
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
<strong>Population:</strong> <span class="country-population">33679000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Cocos [Keeling] Islands
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-cc"></i>
                            Cocos [Keeling] Islands
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
<strong>Population:</strong> <span class="country-population">628</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Democratic Republic of the Congo
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-cd"></i>
                            Democratic Republic of the Congo
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
<strong>Population:</strong> <span class="country-population">70916439</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Central African Republic
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-cf"></i>
                            Central African Republic
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
<strong>Population:</strong> <span class="country-population">4844927</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
</div>
</div>
['col-md-4', 'country']
Republic of the Congo

In [11]:
for h3 in all_h3:
    # population=h3.findNext("div").select("span.country-population")[0].get_text(strip=True)
    population=h3.findNext("div").select_one("span.country-population").get_text(strip=True)
    print(population)

84000
4975593
29121286
86754
13254
2986952
2968000
13068161
0
41343201
57881
8205000
21515754
71566
26711
8303512
4590000
285653
156118464
10403000
16241811
7148785
738004
9863117
9056010
8450
65365
395027
9947418
18012
201103330
301790
699847
0
2029307
9685000
314522
33679000
628
70916439
4844927
3039126
7581000
21058798
21388
16746491
19294149
1330044000
47790000
4516220
11423000
508659
141766
1500
1102677
10476000
81802257
740528
5484000
72813
9823821
34586184
14790608
1291170
80471869
273008
5792984
46505963
88013491
5244000
875983
2638
107708
48228
64768389
1545255
62348447
107818
4630000
195506
65228
24339838
27884
56375
1593256
10324025
443000
1014999
11000000
30
13550440
159358
1565126
748486
6898686
0
7989415
4491000
9648924
9982000
242968342
4622917
7353985
75049
1173108018
4000
29671605
76923300
308910
60340328
90812
2847232
6407085
127288000
40046566
5776500
14453680
92533
773407
51134
22912177
48422644
2789132
44270
15340000
6368162
4125247
160922
35000
21513990
3685076
1919552
2944459
497538
2217969
6461454
31627428
32965
4324000
666730
35925
21281844
65859
2062294
13796354
53414374
3086918
449198
53883
432900
3205060
9341
403000
1294104
395650
15447500
112468855
28274729
22061451
2128471
216494
15878271
1828
154000000
5995928
16645000
5009150
28951852
10065
2166
4252277
2967717
3410676
29907003
270485
6064515
99900177
184404791
38500000
7012
46
3916632
3800000
10676000
19907
6375830
840926
776948
21959278
7344847
140702000
11055976
25731776
559198
88340
35000000
9828655
4701069
7460
2007000
2550
5455000
5245695
31477
12323252
10112453
492829
8260490
175808
6052064
37429
22198110
1354051
20556
10543464
140
6587239
67089500
7487489
1466
1154625
4940916
10589025
122580
77804122
1228691
10472
22894384
41892895
45415596
33398682
0
310232863
3477000
27865738
921
104217
27223228
21730
108708
89571130
221552
16025
192001
1800000
23495361
159042
49000000
13460305
11651858

In [12]:
print(h3.findNext("div").get_text())

Capital: Harare
Population: 11651858
Area (km2): 390580.0

In [13]:
all_Countries=[]
for h3 in all_h3:
    name=h3.get_text(strip=True)
    population=h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    all_Countries.append([name,population])

In [14]:
all_Countries

[['Andorra', '84000'],
 ['United Arab Emirates', '4975593'],
 ['Afghanistan', '29121286'],
 ['Antigua and Barbuda', '86754'],
 ['Anguilla', '13254'],
 ['Albania', '2986952'],
 ['Armenia', '2968000'],
 ['Angola', '13068161'],
 ['Antarctica', '0'],
 ['Argentina', '41343201'],
 ['American Samoa', '57881'],
 ['Austria', '8205000'],
 ['Australia', '21515754'],
 ['Aruba', '71566'],
 ['Åland', '26711'],
 ['Azerbaijan', '8303512'],
 ['Bosnia and Herzegovina', '4590000'],
 ['Barbados', '285653'],
 ['Bangladesh', '156118464'],
 ['Belgium', '10403000'],
 ['Burkina Faso', '16241811'],
 ['Bulgaria', '7148785'],
 ['Bahrain', '738004'],
 ['Burundi', '9863117'],
 ['Benin', '9056010'],
 ['Saint Barthélemy', '8450'],
 ['Bermuda', '65365'],
 ['Brunei', '395027'],
 ['Bolivia', '9947418'],
 ['Bonaire', '18012'],
 ['Brazil', '201103330'],
 ['Bahamas', '301790'],
 ['Bhutan', '699847'],
 ['Bouvet Island', '0'],
 ['Botswana', '2029307'],
 ['Belarus', '9685000'],
 ['Belize', '314522'],
 ['Canada', '33679000'],
 ['Cocos [Keeling] Islands', '628'],
 ['Democratic Republic of the Congo', '70916439'],
 ['Central African Republic', '4844927'],
 ['Republic of the Congo', '3039126'],
 ['Switzerland', '7581000'],
 ['Ivory Coast', '21058798'],
 ['Cook Islands', '21388'],
 ['Chile', '16746491'],
 ['Cameroon', '19294149'],
 ['China', '1330044000'],
 ['Colombia', '47790000'],
 ['Costa Rica', '4516220'],
 ['Cuba', '11423000'],
 ['Cape Verde', '508659'],
 ['Curacao', '141766'],
 ['Christmas Island', '1500'],
 ['Cyprus', '1102677'],
 ['Czech Republic', '10476000'],
 ['Germany', '81802257'],
 ['Djibouti', '740528'],
 ['Denmark', '5484000'],
 ['Dominica', '72813'],
 ['Dominican Republic', '9823821'],
 ['Algeria', '34586184'],
 ['Ecuador', '14790608'],
 ['Estonia', '1291170'],
 ['Egypt', '80471869'],
 ['Western Sahara', '273008'],
 ['Eritrea', '5792984'],
 ['Spain', '46505963'],
 ['Ethiopia', '88013491'],
 ['Finland', '5244000'],
 ['Fiji', '875983'],
 ['Falkland Islands', '2638'],
 ['Micronesia', '107708'],
 ['Faroe Islands', '48228'],
 ['France', '64768389'],
 ['Gabon', '1545255'],
 ['United Kingdom', '62348447'],
 ['Grenada', '107818'],
 ['Georgia', '4630000'],
 ['French Guiana', '195506'],
 ['Guernsey', '65228'],
 ['Ghana', '24339838'],
 ['Gibraltar', '27884'],
 ['Greenland', '56375'],
 ['Gambia', '1593256'],
 ['Guinea', '10324025'],
 ['Guadeloupe', '443000'],
 ['Equatorial Guinea', '1014999'],
 ['Greece', '11000000'],
 ['South Georgia and the South Sandwich Islands', '30'],
 ['Guatemala', '13550440'],
 ['Guam', '159358'],
 ['Guinea-Bissau', '1565126'],
 ['Guyana', '748486'],
 ['Hong Kong', '6898686'],
 ['Heard Island and McDonald Islands', '0'],
 ['Honduras', '7989415'],
 ['Croatia', '4491000'],
 ['Haiti', '9648924'],
 ['Hungary', '9982000'],
 ['Indonesia', '242968342'],
 ['Ireland', '4622917'],
 ['Israel', '7353985'],
 ['Isle of Man', '75049'],
 ['India', '1173108018'],
 ['British Indian Ocean Territory', '4000'],
 ['Iraq', '29671605'],
 ['Iran', '76923300'],
 ['Iceland', '308910'],
 ['Italy', '60340328'],
 ['Jersey', '90812'],
 ['Jamaica', '2847232'],
 ['Jordan', '6407085'],
 ['Japan', '127288000'],
 ['Kenya', '40046566'],
 ['Kyrgyzstan', '5776500'],
 ['Cambodia', '14453680'],
 ['Kiribati', '92533'],
 ['Comoros', '773407'],
 ['Saint Kitts and Nevis', '51134'],
 ['North Korea', '22912177'],
 ['South Korea', '48422644'],
 ['Kuwait', '2789132'],
 ['Cayman Islands', '44270'],
 ['Kazakhstan', '15340000'],
 ['Laos', '6368162'],
 ['Lebanon', '4125247'],
 ['Saint Lucia', '160922'],
 ['Liechtenstein', '35000'],
 ['Sri Lanka', '21513990'],
 ['Liberia', '3685076'],
 ['Lesotho', '1919552'],
 ['Lithuania', '2944459'],
 ['Luxembourg', '497538'],
 ['Latvia', '2217969'],
 ['Libya', '6461454'],
 ['Morocco', '31627428'],
 ['Monaco', '32965'],
 ['Moldova', '4324000'],
 ['Montenegro', '666730'],
 ['Saint Martin', '35925'],
 ['Madagascar', '21281844'],
 ['Marshall Islands', '65859'],
 ['Macedonia', '2062294'],
 ['Mali', '13796354'],
 ['Myanmar [Burma]', '53414374'],
 ['Mongolia', '3086918'],
 ['Macao', '449198'],
 ['Northern Mariana Islands', '53883'],
 ['Martinique', '432900'],
 ['Mauritania', '3205060'],
 ['Montserrat', '9341'],
 ['Malta', '403000'],
 ['Mauritius', '1294104'],
 ['Maldives', '395650'],
 ['Malawi', '15447500'],
 ['Mexico', '112468855'],
 ['Malaysia', '28274729'],
 ['Mozambique', '22061451'],
 ['Namibia', '2128471'],
 ['New Caledonia', '216494'],
 ['Niger', '15878271'],
 ['Norfolk Island', '1828'],
 ['Nigeria', '154000000'],
 ['Nicaragua', '5995928'],
 ['Netherlands', '16645000'],
 ['Norway', '5009150'],
 ['Nepal', '28951852'],
 ['Nauru', '10065'],
 ['Niue', '2166'],
 ['New Zealand', '4252277'],
 ['Oman', '2967717'],
 ['Panama', '3410676'],
 ['Peru', '29907003'],
 ['French Polynesia', '270485'],
 ['Papua New Guinea', '6064515'],
 ['Philippines', '99900177'],
 ['Pakistan', '184404791'],
 ['Poland', '38500000'],
 ['Saint Pierre and Miquelon', '7012'],
 ['Pitcairn Islands', '46'],
 ['Puerto Rico', '3916632'],
 ['Palestine', '3800000'],
 ['Portugal', '10676000'],
 ['Palau', '19907'],
 ['Paraguay', '6375830'],
 ['Qatar', '840926'],
 ['Réunion', '776948'],
 ['Romania', '21959278'],
 ['Serbia', '7344847'],
 ['Russia', '140702000'],
 ['Rwanda', '11055976'],
 ['Saudi Arabia', '25731776'],
 ['Solomon Islands', '559198'],
 ['Seychelles', '88340'],
 ['Sudan', '35000000'],
 ['Sweden', '9828655'],
 ['Singapore', '4701069'],
 ['Saint Helena', '7460'],
 ['Slovenia', '2007000'],
 ['Svalbard and Jan Mayen', '2550'],
 ['Slovakia', '5455000'],
 ['Sierra Leone', '5245695'],
 ['San Marino', '31477'],
 ['Senegal', '12323252'],
 ['Somalia', '10112453'],
 ['Suriname', '492829'],
 ['South Sudan', '8260490'],
 ['São Tomé and Príncipe', '175808'],
 ['El Salvador', '6052064'],
 ['Sint Maarten', '37429'],
 ['Syria', '22198110'],
 ['Swaziland', '1354051'],
 ['Turks and Caicos Islands', '20556'],
 ['Chad', '10543464'],
 ['French Southern Territories', '140'],
 ['Togo', '6587239'],
 ['Thailand', '67089500'],
 ['Tajikistan', '7487489'],
 ['Tokelau', '1466'],
 ['East Timor', '1154625'],
 ['Turkmenistan', '4940916'],
 ['Tunisia', '10589025'],
 ['Tonga', '122580'],
 ['Turkey', '77804122'],
 ['Trinidad and Tobago', '1228691'],
 ['Tuvalu', '10472'],
 ['Taiwan', '22894384'],
 ['Tanzania', '41892895'],
 ['Ukraine', '45415596'],
 ['Uganda', '33398682'],
 ['U.S. Minor Outlying Islands', '0'],
 ['United States', '310232863'],
 ['Uruguay', '3477000'],
 ['Uzbekistan', '27865738'],
 ['Vatican City', '921'],
 ['Saint Vincent and the Grenadines', '104217'],
 ['Venezuela', '27223228'],
 ['British Virgin Islands', '21730'],
 ['U.S. Virgin Islands', '108708'],
 ['Vietnam', '89571130'],
 ['Vanuatu', '221552'],
 ['Wallis and Futuna', '16025'],
 ['Samoa', '192001'],
 ['Kosovo', '1800000'],
 ['Yemen', '23495361'],
 ['Mayotte', '159042'],
 ['South Africa', '49000000'],
 ['Zambia', '13460305'],
 ['Zimbabwe', '11651858']]

In [15]:
df=pd.DataFrame(all_Countries,columns=["Country","Population"])
df

                  Country Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

In [16]:
df.to_csv("cleanData.csv",index=False)

# Practice Web Sracping using BeautifulSoup

In [17]:
with open("scraped_data/data2.html","r") as f:
    html_content=f.read()

In [18]:
html_content
print(html_content)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="hockey">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://www.opensourcesports.com/hockey/" class="data-attribution" target="_blank">http://www.opensourcesports.com/hockey/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row search-area">
                    <div class="col-md-12 text-center">
                        <form method="GET" action="/pages/forms/" class="form form-inline">
                            <label for="q">
                                Search for Teams: &nbsp;
                            </label>
                            <input type="text" class="form-control" name="q" id="q" placeholder="Search for Teams" />

                            <input type="submit" class="btn btn-primary" value="Search" />
                        </form>
                        <hr>
                    </div>
                </div><!--.row.search-area-->


                <table class="table">
                    <tr>
                        <th>
                            Team Name
                        </th>
                        <th>
                            Year
                        </th>
                        <th>
                            Wins
                        </th>
                        <th>
                            Losses
                        </th>
                        <th>
                            OT Losses
                        </th>
                        <th>
                            Win %
                        </th>
                        <th>
                            Goals For (GF)
                        </th>
                        <th>
                            Goals Against (GA)
                        </th>
                        <th>
                            + / -
                        </th>
                    </tr>

                    <tr class="team">
                        <td class="name">
                            Boston Bruins
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            44
                        </td>
                        <td class="losses">
                            24
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-success">
                            0.55
                        </td>

                        <td class="gf">
                            299
                        </td>
                        <td class="ga">
                            264
                        </td>


                        <td class="diff text-success">
                            35
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Buffalo Sabres
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            31
                        </td>
                        <td class="losses">
                            30
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.388
                        </td>

                        <td class="gf">
                            292
                        </td>
                        <td class="ga">
                            278
                        </td>


                        <td class="diff text-success">
                            14
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Calgary Flames
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            46
                        </td>
                        <td class="losses">
                            26
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-success">
                            0.575
                        </td>

                        <td class="gf">
                            344
                        </td>
                        <td class="ga">
                            263
                        </td>


                        <td class="diff text-success">
                            81
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Chicago Blackhawks
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            49
                        </td>
                        <td class="losses">
                            23
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-success">
                            0.613
                        </td>

                        <td class="gf">
                            284
                        </td>
                        <td class="ga">
                            211
                        </td>


                        <td class="diff text-success">
                            73
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Detroit Red Wings
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            34
                        </td>
                        <td class="losses">
                            38
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.425
                        </td>

                        <td class="gf">
                            273
                        </td>
                        <td class="ga">
                            298
                        </td>


                        <td class="diff text-danger">
                            -25
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Edmonton Oilers
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            37
                        </td>
                        <td class="losses">
                            37
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.463
                        </td>

                        <td class="gf">
                            272
                        </td>
                        <td class="ga">
                            272
                        </td>


                        <td class="diff text-success">
                            0
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Hartford Whalers
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            31
                        </td>
                        <td class="losses">
                            38
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.388
                        </td>

                        <td class="gf">
                            238
                        </td>
                        <td class="ga">
                            276
                        </td>


                        <td class="diff text-danger">
                            -38
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Los Angeles Kings
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            46
                        </td>
                        <td class="losses">
                            24
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-success">
                            0.575
                        </td>

                        <td class="gf">
                            340
                        </td>
                        <td class="ga">
                            254
                        </td>


                        <td class="diff text-success">
                            86
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Minnesota North Stars
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            27
                        </td>
                        <td class="losses">
                            39
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.338
                        </td>

                        <td class="gf">
                            256
                        </td>
                        <td class="ga">
                            266
                        </td>


                        <td class="diff text-danger">
                            -10
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Montreal Canadiens
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            39
                        </td>
                        <td class="losses">
                            30
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.487
                        </td>

                        <td class="gf">
                            273
                        </td>
                        <td class="ga">
                            249
                        </td>


                        <td class="diff text-success">
                            24
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            New Jersey Devils
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            32
                        </td>
                        <td class="losses">
                            33
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.4
                        </td>

                        <td class="gf">
                            272
                        </td>
                        <td class="ga">
                            264
                        </td>


                        <td class="diff text-success">
                            8
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            New York Islanders
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            25
                        </td>
                        <td class="losses">
                            45
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.312
                        </td>

                        <td class="gf">
                            223
                        </td>
                        <td class="ga">
                            290
                        </td>


                        <td class="diff text-danger">
                            -67
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            New York Rangers
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            36
                        </td>
                        <td class="losses">
                            31
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.45
                        </td>

                        <td class="gf">
                            297
                        </td>
                        <td class="ga">
                            265
                        </td>



In [19]:
soup=bs(html_content,"lxml")
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">

In [20]:
table=soup.find("table",class_="table")
table

<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            26
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.325
                        </td>
<td class="gf">
                            260
                        </td>
<td class="ga">
                            288
                        </td>
<td class="diff text-danger">
                            -28
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            32
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            270
                        </td>
<td class="ga">
                            275
                        </td>
<td class="diff text-danger">
                            -5
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            289
                        </td>
<td class="ga">
                            299
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            296
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-danger">
                            -9
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            29
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            257
                        </td>
<td class="ga">
                            236
                        </td>
<td class="diff text-success">
                            21
                        </td>
</tr>
</table>

In [21]:
Team_details=[]
for tr in table.find_all("tr",class_="team"):
    # Extract Team Name
    name=tr.find("td",class_="name")
    team_name=name.get_text(strip=True)
    
    # Extract Wins
    win_td=tr.find("td",class_="wins")
    wins=win_td.get_text(strip=True)

    # Extract Losses
    loss_td=tr.find("td",class_="losses")
    losses=loss_td.get_text(strip=True)

    Team_details.append([team_name,wins,losses])

In [22]:
print(Team_details)

[['Boston Bruins', '44', '24'], ['Buffalo Sabres', '31', '30'], ['Calgary Flames', '46', '26'], ['Chicago Blackhawks', '49', '23'], ['Detroit Red Wings', '34', '38'], ['Edmonton Oilers', '37', '37'], ['Hartford Whalers', '31', '38'], ['Los Angeles Kings', '46', '24'], ['Minnesota North Stars', '27', '39'], ['Montreal Canadiens', '39', '30'], ['New Jersey Devils', '32', '33'], ['New York Islanders', '25', '45'], ['New York Rangers', '36', '31'], ['Philadelphia Flyers', '33', '37'], ['Pittsburgh Penguins', '41', '33'], ['Quebec Nordiques', '16', '50'], ['St. Louis Blues', '47', '22'], ['Toronto Maple Leafs', '23', '46'], ['Vancouver Canucks', '28', '43'], ['Washington Capitals', '37', '36'], ['Winnipeg Jets', '26', '43'], ['Boston Bruins', '36', '32'], ['Buffalo Sabres', '31', '37'], ['Calgary Flames', '31', '37'], ['Chicago Blackhawks', '36', '29']]

In [23]:
df=pd.DataFrame(Team_details,columns=["Team Name","Wins","Losses"])
df

                Team Name Wins Losses
0           Boston Bruins   44     24
1          Buffalo Sabres   31     30
2          Calgary Flames   46     26
3      Chicago Blackhawks   49     23
4       Detroit Red Wings   34     38
5         Edmonton Oilers   37     37
6        Hartford Whalers   31     38
7       Los Angeles Kings   46     24
8   Minnesota North Stars   27     39
9      Montreal Canadiens   39     30
10      New Jersey Devils   32     33
11     New York Islanders   25     45
12       New York Rangers   36     31
13    Philadelphia Flyers   33     37
14    Pittsburgh Penguins   41     33
15       Quebec Nordiques   16     50
16        St. Louis Blues   47     22
17    Toronto Maple Leafs   23     46
18      Vancouver Canucks   28     43
19    Washington Capitals   37     36
20          Winnipeg Jets   26     43
21          Boston Bruins   36     32
22         Buffalo Sabres   31     37
23         Calgary Flames   31     37
24     Chicago Blackhawks   36     29

In [24]:
df.to_csv("team deatils.csv",index=False)

# Practice 2

In [25]:
with open("scraped_data/data3.html","r") as f:
    html_content=f.read()
print(html_content)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Advanced Topics: Real World Challenges You&#39;ll Encounter | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Scraping real websites, you&#39;re likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>





        <div id="page">

            <section id="gotchas">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <h3>Advanced Topics: Real World Challenges You&#39;ll Encounter</h3>
                            <p class="lead">
                                Scraping real websites, you&#39;re likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.
                            </p>
                            <hr>


                            <h4>
                                <a href="/pages/advanced/?gotcha=headers" target="_blank">Spoofing Headers</a>
                            </h4>
                            <p>
                                Sometimes you need to make your web scraper appear to be making HTTP requests as a browser in order to get the web server to return the same data that you see in your browser.
                            </p>
                            <hr>

                            <h4>
                                <a href="/pages/advanced/?gotcha=login" target="_blank">Logins &amp; Session Data</a>
                            </h4>
                            <p>
                                Submit some data in one request, get a session cookie back from the site, and then be sure to send that cookie back on subsequent requests so you stay &#34;logged in&#34; between requests.
                            </p>
                            <hr>

                            <h4>
                                <a href="/pages/advanced/?gotcha=csrf" target="_blank">CSRF &amp; Hidden Values</a>
                            </h4>
                            <p>
                                Some forms require hidden values to be submitted, not just the fields that have text fields. Load the login page, grab all the hidden value, then submit them with the rest of the form fields.
                            </p>
                            <hr>


                        </div><!--.col-->
                    </div><!--.row-->

                </div><!--.container-->
            </section>

        </div><!--#page-->




    <section id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center text-muted">
                    Lessons and Videos &copy; Hartley Brody 2023
                </div><!--.col-->
            </div><!--.row-->
        </div><!--.container-->
    </section>
  </body>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>



  <script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css">

  <!-- pnotify messages -->
  <script type="text/javascript">

    PNotify.prototype.options.styling = "bootstrap3";
    $(function(){

    });


    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>

  <!-- golbal video controls -->
  <script type="text/javascript">
    $("video").hover(function() {
        $(this).prop("controls", true);
    }, function() {
        $(this).prop("controls", false);
    });

    $("video").click(function() {
        if( this.paused){
            this.play();
        }
        else {
            this.pause();
        }
    });
    </script>

  <!-- insert google analytics here -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41551755-8', 'auto');
    ga('send', 'pageview');
  </script>

  <!-- Facebook Pixel Code -->
  <script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '764287443701341');
  fbq('track', "PageView");</script>
  <noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=764287443701341&ev=PageView&noscript=1"
  /></noscript>
  <!-- End Facebook Pixel Code -->

  <!-- Google Code for Remarketing Tag -->
  <script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 950945448;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
    <div style="display:inline;">
    <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0"/>
    </div>
  </noscript>

  <!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=AW-950945448"></script>
  <script>
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());

   gtag('config', 'AW-950945448');
  </script>

</html>

In [26]:
soup=bs(html_content,"lxml")
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Advanced Topics: Real World Challenges You'll Encounter | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Scraping real websites, you're likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="gotchas">
<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3">
<h3>Advanced Topics: Real World Challenges You'll Encounter</h3>
<p class="lead">
                                Scraping real websites, you're likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.
                            </p>
<hr/>
<h4>
<a href="/pages/advanced/?gotcha=headers" target="_blank">Spoofing Headers</a>
</h4>
<p>
                                Sometimes you need to make your web scraper appear to be making HTTP requests as a browser in order to get the web server to return the same data that you see in your browser.
                            </p>
<hr/>
<h4>
<a href="/pages/advanced/?gotcha=login" target="_blank">Logins &amp; Session Data</a>
</h4>
<p>
                                Submit some data in one request, get a session cookie back from the site, and then be sure to send that cookie back on subsequent requests so you stay "logged in" between requests.
                            </p>
<hr/>
<h4>
<a href="/pages/advanced/?gotcha=csrf" target="_blank">CSRF &amp; Hidden Values</a>
</h4>
<p>
                                Some forms require hidden values to be submitted, not just the fields that have text fields. Load the login page, grab all the hidden value, then submit them with the rest of the form fields.
                            </p>
<hr/>
</div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
</div><!--#page-->
<section id="footer">
<div class="container">
<div class="row">
<div class="col-md-12 text-center text-muted">
                    Lessons and Videos © Hartley Brody 2023
                </div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script crossorigin="anonymous" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css"/>
<!-- pnotify messages -->
<script type="text/javascript">

    PNotify.prototype.options.styling = "bootstrap3";
    $(function(){

    });


    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
<!-- golbal video controls -->
<script type="text/javascript">
    $("video").hover(function() {
        $(this).prop("controls", true);
    }, function() {
        $(this).prop("controls", false);
    });

    $("video").click(function() {
        if( this.paused){
            this.play();
        }
        else {
            this.pause();
        }
    });
    </script>
<!-- insert google analytics here -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41551755-8', 'auto');
    ga('send', 'pageview');
  </script>
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '764287443701341');
  fbq('track', "PageView");</script>
<noscript><img height="1" src="https://www.facebook.com/tr?id=764287443701341&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
<!-- End Facebook Pixel Code -->
<!-- Google Code for Remarketing Tag -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 950945448;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
    </script>
<script src="//www.googleadservices.com/pagead/conversion.js" type="text/javascript">
</script>
<noscript>
<div style="display:inline;">
<img alt="" height="1" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0" style="border-style:none;" width="1"/>
</div>
</noscript>
<!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-950945448"></script>
<script>
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());

   gtag('config', 'AW-950945448');
  </script>
</html>

In [27]:
advance_topic=[]
for h4 in soup.find_all("h4"):
    heading=h4.get_text(strip=True)
    para=h4.findNext("p").get_text(strip=True)
    advance_topic.append([heading,para])

In [28]:
df=pd.DataFrame(advance_topic,columns=["Title","Content"])
df

                   Title                                            Content
0       Spoofing Headers  Sometimes you need to make your web scraper ap...
1  Logins & Session Data  Submit some data in one request, get a session...
2   CSRF & Hidden Values  Some forms require hidden values to be submitt...

In [29]:
df.to_csv("advance_topic.csv",index=False)

# Practice Again

In [30]:
with open("scraped_data/data4.html","r") as f:
    html_content=f.read()

In [31]:
html_content

'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="countries">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Countries of the World: A Simple Example\n                            <small>250 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row">\n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ad"></i>\n                            Andorra\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>\n                            <strong>Population:</strong> <span class="country-population">84000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ae"></i>\n                            United Arab Emirates\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>\n                            <strong>Population:</strong> <span class="country-population">4975593</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-af"></i>\n                            Afghanistan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>\n                            <strong>Population:</strong> <span class="country-population">29121286</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ag"></i>\n                            Antigua and Barbuda\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>\n                            <strong>Population:</strong> <span class="country-population">86754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ai"></i>\n                            Anguilla\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>\n                            <strong>Population:</strong> <span class="country-population">13254</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-al"></i>\n                            Albania\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>\n                            <strong>Population:</strong> <span class="country-population">2986952</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-am"></i>\n                            Armenia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>\n                            <strong>Population:</strong> <span class="country-population">2968000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ao"></i>\n                            Angola\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>\n                            <strong>Population:</strong> <span class="country-population">13068161</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aq"></i>\n                            Antarctica\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">None</span><br>\n                            <strong>Population:</strong> <span class="country-population">0</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ar"></i>\n                            Argentina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>\n                            <strong>Population:</strong> <span class="country-population">41343201</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-as"></i>\n                            American Samoa\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>\n                            <strong>Population:</strong> <span class="country-population">57881</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-at"></i>\n                            Austria\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>\n                            <strong>Population:</strong> <span class="country-population">8205000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-au"></i>\n                            Australia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>\n                            <strong>Population:</strong> <span class="country-population">21515754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aw"></i>\n                            Aruba\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>\n                            <strong>Population:</strong> <span class="country-population">71566</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ax"></i>\n                            Åland\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>\n                            <strong>Population:</strong> <span class="country-population">26711</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-az"></i>\n                            Azerbaijan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>\n                            <strong>Population:</strong> <span class="country-population">8303512</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ba"></i>\n                            Bosnia and Herzegovina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>\n                            <strong>Population:</strong> <span class="country-population">4590000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-bb"></i>\n                            Barbados\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>\n                            <strong>Population:</strong> <span class="country-population">285653</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 cou

In [32]:
soup=bs(html_content,"lxml")

In [33]:
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

In [34]:
soup.find('h3')

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [35]:
all_h3=soup.find_all('h3')

In [36]:
for h3 in all_h3:
    # print(h3.getText())
    print(h3.get_text(strip=True))

Andorra
United Arab Emirates
Afghanistan
Antigua and Barbuda
Anguilla
Albania
Armenia
Angola
Antarctica
Argentina
American Samoa
Austria
Australia
Aruba
Åland
Azerbaijan
Bosnia and Herzegovina
Barbados
Bangladesh
Belgium
Burkina Faso
Bulgaria
Bahrain
Burundi
Benin
Saint Barthélemy
Bermuda
Brunei
Bolivia
Bonaire
Brazil
Bahamas
Bhutan
Bouvet Island
Botswana
Belarus
Belize
Canada
Cocos [Keeling] Islands
Democratic Republic of the Congo
Central African Republic
Republic of the Congo
Switzerland
Ivory Coast
Cook Islands
Chile
Cameroon
China
Colombia
Costa Rica
Cuba
Cape Verde
Curacao
Christmas Island
Cyprus
Czech Republic
Germany
Djibouti
Denmark
Dominica
Dominican Republic
Algeria
Ecuador
Estonia
Egypt
Western Sahara
Eritrea
Spain
Ethiopia
Finland
Fiji
Falkland Islands
Micronesia
Faroe Islands
France
Gabon
United Kingdom
Grenada
Georgia
French Guiana
Guernsey
Ghana
Gibraltar
Greenland
Gambia
Guinea
Guadeloupe
Equatorial Guinea
Greece
South Georgia and the South Sandwich Islands
Guatemala
Guam
Guinea-Bissau
Guyana
Hong Kong
Heard Island and McDonald Islands
Honduras
Croatia
Haiti
Hungary
Indonesia
Ireland
Israel
Isle of Man
India
British Indian Ocean Territory
Iraq
Iran
Iceland
Italy
Jersey
Jamaica
Jordan
Japan
Kenya
Kyrgyzstan
Cambodia
Kiribati
Comoros
Saint Kitts and Nevis
North Korea
South Korea
Kuwait
Cayman Islands
Kazakhstan
Laos
Lebanon
Saint Lucia
Liechtenstein
Sri Lanka
Liberia
Lesotho
Lithuania
Luxembourg
Latvia
Libya
Morocco
Monaco
Moldova
Montenegro
Saint Martin
Madagascar
Marshall Islands
Macedonia
Mali
Myanmar [Burma]
Mongolia
Macao
Northern Mariana Islands
Martinique
Mauritania
Montserrat
Malta
Mauritius
Maldives
Malawi
Mexico
Malaysia
Mozambique
Namibia
New Caledonia
Niger
Norfolk Island
Nigeria
Nicaragua
Netherlands
Norway
Nepal
Nauru
Niue
New Zealand
Oman
Panama
Peru
French Polynesia
Papua New Guinea
Philippines
Pakistan
Poland
Saint Pierre and Miquelon
Pitcairn Islands
Puerto Rico
Palestine
Portugal
Palau
Paraguay
Qatar
Réunion
Romania
Serbia
Russia
Rwanda
Saudi Arabia
Solomon Islands
Seychelles
Sudan
Sweden
Singapore
Saint Helena
Slovenia
Svalbard and Jan Mayen
Slovakia
Sierra Leone
San Marino
Senegal
Somalia
Suriname
South Sudan
São Tomé and Príncipe
El Salvador
Sint Maarten
Syria
Swaziland
Turks and Caicos Islands
Chad
French Southern Territories
Togo
Thailand
Tajikistan
Tokelau
East Timor
Turkmenistan
Tunisia
Tonga
Turkey
Trinidad and Tobago
Tuvalu
Taiwan
Tanzania
Ukraine
Uganda
U.S. Minor Outlying Islands
United States
Uruguay
Uzbekistan
Vatican City
Saint Vincent and the Grenadines
Venezuela
British Virgin Islands
U.S. Virgin Islands
Vietnam
Vanuatu
Wallis and Futuna
Samoa
Kosovo
Yemen
Mayotte
South Africa
Zambia
Zimbabwe

In [37]:
soup.find_all('span')

[<span class="country-capital">Andorra la Vella</span>,
 <span class="country-population">84000</span>,
 <span class="country-area">468.0</span>,
 <span class="country-capital">Abu Dhabi</span>,
 <span class="country-population">4975593</span>,
 <span class="country-area">82880.0</span>,
 <span class="country-capital">Kabul</span>,
 <span class="country-population">29121286</span>,
 <span class="country-area">647500.0</span>,
 <span class="country-capital">St. John's</span>,
 <span class="country-population">86754</span>,
 <span class="country-area">443.0</span>,
 <span class="country-capital">The Valley</span>,
 <span class="country-population">13254</span>,
 <span class="country-area">102.0</span>,
 <span class="country-capital">Tirana</span>,
 <span class="country-population">2986952</span>,
 <span class="country-area">28748.0</span>,
 <span class="country-capital">Yerevan</span>,
 <span class="country-population">2968000</span>,
 <span class="country-area">29800.0</span>,
 <span class="country-capital">Luanda</span>,
 <span class="country-population">13068161</span>,
 <span class="country-area">1246700.0</span>,
 <span class="country-capital">None</span>,
 <span class="country-population">0</span>,
 <span class="country-area">1.4E7</span>,
 <span class="country-capital">Buenos Aires</span>,
 <span class="country-population">41343201</span>,
 <span class="country-area">2766890.0</span>,
 <span class="country-capital">Pago Pago</span>,
 <span class="country-population">57881</span>,
 <span class="country-area">199.0</span>,
 <span class="country-capital">Vienna</span>,
 <span class="country-population">8205000</span>,
 <span class="country-area">83858.0</span>,
 <span class="country-capital">Canberra</span>,
 <span class="country-population">21515754</span>,
 <span class="country-area">7686850.0</span>,
 <span class="country-capital">Oranjestad</span>,
 <span class="country-population">71566</span>,
 <span class="country-area">193.0</span>,
 <span class="country-capital">Mariehamn</span>,
 <span class="country-population">26711</span>,
 <span class="country-area">1580.0</span>,
 <span class="country-capital">Baku</span>,
 <span class="country-population">8303512</span>,
 <span class="country-area">86600.0</span>,
 <span class="country-capital">Sarajevo</span>,
 <span class="country-population">4590000</span>,
 <span class="country-area">51129.0</span>,
 <span class="country-capital">Bridgetown</span>,
 <span class="country-population">285653</span>,
 <span class="country-area">431.0</span>,
 <span class="country-capital">Dhaka</span>,
 <span class="country-population">156118464</span>,
 <span class="country-area">144000.0</span>,
 <span class="country-capital">Brussels</span>,
 <span class="country-population">10403000</span>,
 <span class="country-area">30510.0</span>,
 <span class="country-capital">Ouagadougou</span>,
 <span class="country-population">16241811</span>,
 <span class="country-area">274200.0</span>,
 <span class="country-capital">Sofia</span>,
 <span class="country-population">7148785</span>,
 <span class="country-area">110910.0</span>,
 <span class="country-capital">Manama</span>,
 <span class="country-population">738004</span>,
 <span class="country-area">665.0</span>,
 <span class="country-capital">Bujumbura</span>,
 <span class="country-population">9863117</span>,
 <span class="country-area">27830.0</span>,
 <span class="country-capital">Porto-Novo</span>,
 <span class="country-population">9056010</span>,
 <span class="country-area">112620.0</span>,
 <span class="country-capital">Gustavia</span>,
 <span class="country-population">8450</span>,
 <span class="country-area">21.0</span>,
 <span class="country-capital">Hamilton</span>,
 <span class="country-population">65365</span>,
 <span class="country-area">53.0</span>,
 <span class="country-capital">Bandar Seri Begawan</span>,
 <span class="country-population">395027</span>,
 <span class="country-area">5770.0</span>,
 <span class="country-capital">Sucre</span>,
 <span class="country-population">9947418</span>,
 <span class="country-area">1098580.0</span>,
 <span class="country-capital">Kralendijk</span>,
 <span class="country-population">18012</span>,
 <span class="country-area">328.0</span>,
 <span class="country-capital">Brasília</span>,
 <span class="country-population">201103330</span>,
 <span class="country-area">8511965.0</span>,
 <span class="country-capital">Nassau</span>,
 <span class="country-population">301790</span>,
 <span class="country-area">13940.0</span>,
 <span class="country-capital">Thimphu</span>,
 <span class="country-population">699847</span>,
 <span class="country-area">47000.0</span>,
 <span class="country-capital">None</span>,
 <span class="country-population">0</span>,
 <span class="country-area">49.0</span>,
 <span class="country-capital">Gaborone</span>,
 <span class="country-population">2029307</span>,
 <span class="country-area">600370.0</span>,
 <span class="country-capital">Minsk</span>,
 <span class="country-population">9685000</span>,
 <span class="country-area">207600.0</span>,
 <span class="country-capital">Belmopan</span>,
 <span class="country-population">314522</span>,
 <span class="country-area">22966.0</span>,
 <span class="country-capital">Ottawa</span>,
 <span class="country-population">33679000</span>,
 <span class="country-area">9984670.0</span>,
 <span class="country-capital">West Island</span>,
 <span class="country-population">628</span>,
 <span class="country-area">14.0</span>,
 <span class="country-capital">Kinshasa</span>,
 <span class="country-population">70916439</span>,
 <span class="country-area">2345410.0</span>,
 <span class="country-capital">Bangui</span>,
 <span class="country-population">4844927</span>,
 <span class="country-area">622984.0</span>,
 <span class="country-capital">Brazzaville</span>,
 <span class="country-population">3039126</span>,
 <span class="country-area">342000.0</span>,
 <span class="country-capital">Bern</span>,
 <span class="country-population">7581000</span>,
 <span class="country-area">41290.0</span>,
 <span class="country-capital">Yamoussoukro</span>,
 <span class="country-population">21058798</span>,
 <span class="country-area">322460.0</span>,
 <span class="country-capital">Avarua</span>,
 <span class="country-population">21388</span>,
 <span class="country-area">240.0</span>,
 <span class="country-capital">Santiago</span>,
 <span class="country-population">16746491</span>,
 <span class="country-area">756950.0</span>,
 <span class="country-capital">Yaoundé</span>,
 <span class="country-population">19294149</span>,
 <span class="country-area">475440.0</span>,
 <span class="country-capital">Beijing</span>,
 <span class="country-population">1330044000</span>,
 <span class="country-area">9596960.0</span>,
 <span class="country-capital">Bogotá</span>,
 <span class="country-population">47790000</span>,
 <span class="country-area">1138910.0</span>,
 <span class="country-capital">San José</span>,
 <span class="country-population">4516220</span>,
 <span class="country-area">51100.0</span>,
 <span class="country-capital">Havana</span>,
 <span class="country-population">11423000</span>,
 <span class="country-area">110860.0</span>,
 <span class="country-capital">Praia</span>,
 <span class="country-population">508659</span>,
 <span class="country-area">4033.0</span>,
 <span class="country-capital">Willemstad</span>,
 <span class="country-population">141766</span>,
 <span class="country-area">444.0</span>,
 <span class="country-capital">Flying Fish Cove</span>,
 <span class="country-population">1500</span>,
 <span class="country-area">135.0</span>,
 <span class="country-capital">Nicosia</span>,
 <span class="country-population">1102677</span>,
 <span class="country-area">9250.0</span>,
 <span class="country-capital">Prague</span>,
 <span class="country-population">10476000</span>,
 <span class="country-area">78866.0</span>,
 <span class="country-capital">Berlin</span>,
 <span class="country-population">81802257</span>,
 <span class="country-area">357021.0</span>,
 <span class="country-capital">Djibouti</span>,
 <span class="country-population">740528</span>,
 <span class="country-area">23000.0</span>,
 <span class="country-capital">Copenhagen</span>,
 <span class="country-population">5484000</span>,
 <span class="country-area">43094.0</span>,
 <span class="country-capital">Roseau</span>,
 <span class="country-population">72813</span>,
 <span class="country-area">754.0</span>,
 <span class="country-capital">Santo Domingo</span>,
 <span class="country-population">9823821</span>,
 <span class="country-area">48730.0</span>,
 <span class="country-capital">Algiers</span>,
 <span class="country-population">34586184</span>,
 <span class="country-area">2381740.0</span>,
 <span class="country-capital">Quito</span>,
 <span class="country-population">14790608</span>,
 <span class="country-area">283560.0</span>,
 <span class="country-capital">Tallinn</span>,
 <span class="country-population">1291170</span>,
 <span class="country-area">45226.0</span>,
 <span class="country-capital">Cairo</span>,
 <span class="country-population">80471869</span>,
 <span class="country-area">1001450.0</span>,
 <span class="country-capital">Laâyoune / El Aaiún</span>,
 <span class="country-population">273008</span>,
 <span class="country-area">266000.0</span>,
 <span class="country-capital">Asmara</span>,
 <span class="country-population">5792984</span>,
 <span class="country-area">121320.0</span>,
 <span class="country-capital">Madrid</span>,
 <span class="country-population">46505963</span>,
 <span class="country-area">504782.0</span>,
 <span class="country-capital">Addis Ababa</span>,
 <span class="country-population">88013491</span>,
 <span class="country-area">1127127.0</span>,
 <span class="country-capital">Helsinki</span>,
 <span class="country-population">5244000</span>,
 <span class="country-area">337030.0</span>,
 <span class="country-capital">Suva</span>,
 <span class="country-population">875983</span>,
 <span class="country-area">18270.0</span>,
 <span class="country-capital">Stanley</span>,
 <span class="country-population">2638</span>,
 <span class="country-area">12173.0</span>,
 <span class="country-capital">Palikir</span>,
 <span class="country-population">107708</span>,
 <span class="country-area">702.0</span>,
 <span class="country-capital">Tórshavn</span>,
 <span class="country-population">48228</span>,
 <span class="country-area">1399.0</span>,
 <span class="country-capital">Paris</span>,
 <span class="country-population">64768389</span>,
 <span class="country-area">547030.0</span>,
 <span class="country-capital">Libreville</span>,
 <span class="country-population">1545255</span>,
 <span class="country-area">267667.0</span>,
 <span class="country-capital">London</span>,
 <span class="country-population">62348447</span>,
 <span class="country-area">244820.0</span>,
 <span class="country-capital">St. George's</span>,
 <span class="country-population">107818</span>,
 <span class="country-area">344.0</span>,
 <span class="country-capital">Tbilisi</span>,
 <span class="country-population">4630000</span>,
 <span class="country-area">69700.0</span>,
 <span class="country-capital">Cayenne</span>,
 <span class="country-population">195506</span>,
 <span class="country-area">91000.0</span>,
 <span class="country-capital">St Peter Port</span>,
 <span class="country-population">65228</span>,
 <span class="country-area">78.0</span>,
 <span class="country-capital">Accra</span>,
 <span class="country-population">24339838</span>,
 <span class="country-area">239460.0</span>,
 <span class="country-capital">Gibraltar</span>,
 <span class="country-population">27884</span>,
 <span class="country-area">6.5</span>,
 <span class="country-capital">Nuuk</span>,
 <span class="country-population">56375</span>,
 <span class="country-area">2166086.0</span>,
 <span class="country-capital">Bathurst</span>,
 <span class="country-population">1593256</span>,
 <span class="country-area">11300.0</span>,
 <span class="country-capital">Conakry</span>,
 <span class="country-population">10324025</span>,
 <span class="country-area">245857.0</span>,
 <span class="country-capital">Basse-Terre</span>,
 <span class="country-population">443000</span>,
 <span class="country-area">1780.0</span>,
 <span class="country-capital">Malabo</span>,
 <span class="country-population">1014999</span>,
 <span class="country-area">28051.0</span>,
 <span class="country-capital">Athens</span>,
 <span class="country-population">11000000</span>,
 <span class="country-area">131940.0</span>,
 <span class="country-capital">Grytviken</span>,
 <span class="country-population">30</span>,
 <span class="country-area">3903.0</span>,
 <span class="country-capital">Guatemala City</span>,
 <span class="country-population">13550440</span>,
 <span class="country-area">108890.0</span>,
 <span class="country-capital">Hagåtña</span>,
 <span class="country-population">159358</span>,
 <span class="country-area">549.0</span>,
 <span class="country-capital">Bissau</span>,
 <span class="country-population">1565126</span>,
 <span class="country-area">36120.0</span>,
 <span class="country-capital">Georgetown</span>,
 <span class="country-population">748486</span>,
 <span class="country-area">214970.0</span>,
 <span class="country-capital">Hong Kong</span>,
 <span class="country-population">6898686</span>,
 <span class="country-area">1092.0</span>,
 <span class="country-capital">None</span>,
 <span class="country-population">0</span>,
 <span class="country-area">412.0</span>,
 <span class="country-capital">Tegucigalpa</span>,
 <span class="country-population">7989415</span>,
 <span class="country-area">112090.0</span>,
 <span class="country-capital">Zagreb</span>,
 <span class="country-population">4491000</span>,
 <span class="country-area">56542.0</span>,
 <span class="country-capital">Port-au-Prince</span>,
 <span class="country-population">9648924</span>,
 <span class="country-area">27750.0</span>,
 <span class="country-capital">Budapest</span>,
 <span class="country-population">9982000</span>,
 <span class="country-area">93030.0</span>,
 <span class="country-capital">Jakarta</span>,
 <span class="country-population">242968342</span>,
 <span class="country-area">1919440.0</span>,
 <span class="country-capital">Dublin</span>,
 <span class="country-population">4622917</span>,
 <span class="country-area">70280.0</span>,
 <span class="country-capital">None</span>,
 <span class="country-population">7353985</span>,
 <span class="country-area">20770.0</span>,
 <span class="country-capital">Douglas</span>,
 <span class="country-population">75049</span>,
 <span class="country-area">572.0</span>,
 <span class="country-capital">New Delhi</span>,
 <span class="country-population">1173108018</span>,
 <span class="country-area">3287590.0</span>,
 <span class="country-capital">None</span>,
 <span class="country-population">4000</span>,
 <span class="country-area">60.0</span>,
 <span class="country-capital">Baghdad</span>,
 <span class="country-population">29671605</span>,
 <span class="country-area">437072.0</span>,
 <span class="country-capital">Tehran</span>,
 <span class="country-population">76923300</span>,
 <span class="country-area">1648000.0</span>,
 <span class="country-capital">Reykjavik</span>,
 <span class="country-population">308910</span>,
 <span class="country-area">103000.0</span>,
 <span class="country-capital">Rome</span>,
 <span class="country-population">60340328</span>,
 <span class="country-area">301230.0</span>,
 <span class="country-capital">Saint Helier</span>,
 <span class="country-population">90812</span>,
 <span class="country-area">116.0</span>,
 <span class="country-capital">Kingston</span>,
 <span class="country-population">2847232</span>,
 <span class="country-area">10991.0</span>,
 <span class="country-capital">Amman</span>,
 <span class="country-population">6407085</span>,
 <span class="country-area">92300.0</span>,
 <span class="country-capital">Tokyo</span>,
 <span class="country-population">127288000</span>,
 <span class="country-area">377835.0</span>,
 <span class="country-capital">Nairobi</span>,
 <span class="country-population">40046566</span>,
 <span class="country-area">582650.0</span>,
 <span class="country-capital">Bishkek</span>,
 <span class="country-population">5776500</span>,
 <span class="country-area">198500.0</span>,
 <span class="country-capital">Phnom Penh</span>,
 <span class="country-population">14453680</span>,
 <span class="country-area">181040.0</span>,
 <span class="country-capital">Tarawa</span>,
 <span class="country-population">92533</span>,
 <span class="country-area">811.0</span>,
 <span class="country-capital">Moroni</span>,
 <span class="country-population">773407</span>,
 <span class="country-area">2170.0</span>,
 <span class="country-capital">Basseterre</span>,
 <span class="country-population">51134</span>,
 <span class="country-area">261.0</span>,
 <span class="country-capital">Pyongyang</span>,
 <span class="country-population">22912177</span>,
 <span class="country-area">120540.0</span>,
 <span class="country-capital">Seoul</span>,
 <span class="country-population">48422644</span>,
 <span class="country-area">98480.0</span>,
 <span class="country-capital">Kuwait City</span>,
 <span class="country-population">2789132</span>,
 <span class="country-area">17820.0</span>,
 <span class="country-capital">George Town</span>,
 <span class="country-population">44270</span>,
 <span class="country-area">262.0</span>,
 <span class="country-capital">Astana</span>,
 <span class="country-population">15340000</span>,
 <span class="country-area">2717300.0</span>,
 <span class="country-capital">Vientiane</span>,
 <span class="country-population">6368162</span>,
 <span class="country-area">236800.0</span>,
 <span class="country-capital">Beirut</span>,
 <span class="country-population">4125247</span>,
 <span class="country-area">10400.0</span>,
 <span class="country-capital">Castries</span>,
 <span class="country-population">160922</span>,
 <span class="country-area">616.0</span>,
 <span class="country-capital">Vaduz</span>,
 <span class="country-population">35000</span>,
 <span class="country-area">160.0</span>,
 <span class="country-capital">Colombo</span>,
 <span class="country-population">21513990</span>,
 <span class="country-area">65610.0</span>,
 <span class="country-capital">Monrovia</span>,
 <span class="country-population">3685076</span>,
 <span class="country-area">111370.0</span>,
 <span class="country-capital">Maseru</span>,
 <span class="country-population">1919552</span>,
 <span class="country-area">30355.0</span>,
 <span class="country-capital">Vilnius</span>,
 <span class="country-population">2944459</span>,
 <span class="country-area">65200.0</span>,
 <span class="country-capital">Luxembourg</span>,
 <span class="country-population">497538</span>,
 <span class="country-area">2586.0</span>,
 <span class="country-capital">Riga</span>,
 <span class="country-population">2217969</span>,
 <span class="country-area">64589.0</span>,
 <span class="country-capital">Tripoli</span>,
 <span class="country-population">6461454</span>,
 <span class="country-area">1759540.0</span>,
 <span class="country-capital">Rabat</span>,
 <span class="country-population">31627428</span>,
 <span class="country-area">446550.0</span>,
 <span class="country-capital">Monaco</span>,
 <span class="country-population">32965</span>,
 <span class="country-area">1.95</span>,
 <span class="country-capital">Chişinău</span>,
 <span class="country-population">4324000</span>,
 <span class="country-area">33843.0</span>,
 <span class="country-capital">Podgorica</span>,
 <span class="country-population">666730</span>,
 <span class="country-area">14026.0</span>,
 <span class="country-capital">Marigot</span>,
 <span class="country-population">35925</span>,
 <span class="country-area">53.0</span>,
 <span class="country-capital">Antananarivo</span>,

In [38]:
for h3 in all_h3:
    # print(h3.findNext('div'))
    # print(h3.findNext('div').select("span.country-population"))
    # print(h3.findNext('div').select("span.country-population")[0])
    print(h3.findNext('div').select("span.country-population")[0].get_text(strip=True))

84000
4975593
29121286
86754
13254
2986952
2968000
13068161
0
41343201
57881
8205000
21515754
71566
26711
8303512
4590000
285653
156118464
10403000
16241811
7148785
738004
9863117
9056010
8450
65365
395027
9947418
18012
201103330
301790
699847
0
2029307
9685000
314522
33679000
628
70916439
4844927
3039126
7581000
21058798
21388
16746491
19294149
1330044000
47790000
4516220
11423000
508659
141766
1500
1102677
10476000
81802257
740528
5484000
72813
9823821
34586184
14790608
1291170
80471869
273008
5792984
46505963
88013491
5244000
875983
2638
107708
48228
64768389
1545255
62348447
107818
4630000
195506
65228
24339838
27884
56375
1593256
10324025
443000
1014999
11000000
30
13550440
159358
1565126
748486
6898686
0
7989415
4491000
9648924
9982000
242968342
4622917
7353985
75049
1173108018
4000
29671605
76923300
308910
60340328
90812
2847232
6407085
127288000
40046566
5776500
14453680
92533
773407
51134
22912177
48422644
2789132
44270
15340000
6368162
4125247
160922
35000
21513990
3685076
1919552
2944459
497538
2217969
6461454
31627428
32965
4324000
666730
35925
21281844
65859
2062294
13796354
53414374
3086918
449198
53883
432900
3205060
9341
403000
1294104
395650
15447500
112468855
28274729
22061451
2128471
216494
15878271
1828
154000000
5995928
16645000
5009150
28951852
10065
2166
4252277
2967717
3410676
29907003
270485
6064515
99900177
184404791
38500000
7012
46
3916632
3800000
10676000
19907
6375830
840926
776948
21959278
7344847
140702000
11055976
25731776
559198
88340
35000000
9828655
4701069
7460
2007000
2550
5455000
5245695
31477
12323252
10112453
492829
8260490
175808
6052064
37429
22198110
1354051
20556
10543464
140
6587239
67089500
7487489
1466
1154625
4940916
10589025
122580
77804122
1228691
10472
22894384
41892895
45415596
33398682
0
310232863
3477000
27865738
921
104217
27223228
21730
108708
89571130
221552
16025
192001
1800000
23495361
159042
49000000
13460305
11651858

In [39]:
all_countries=[]

for h3 in all_h3:
    name=h3.get_text(strip=True)
    population=h3.findNext('div').select("span.country-population")[0].get_text(strip=True)
    

    all_countries.append([name,population])

In [40]:
all_countries

[['Andorra', '84000'],
 ['United Arab Emirates', '4975593'],
 ['Afghanistan', '29121286'],
 ['Antigua and Barbuda', '86754'],
 ['Anguilla', '13254'],
 ['Albania', '2986952'],
 ['Armenia', '2968000'],
 ['Angola', '13068161'],
 ['Antarctica', '0'],
 ['Argentina', '41343201'],
 ['American Samoa', '57881'],
 ['Austria', '8205000'],
 ['Australia', '21515754'],
 ['Aruba', '71566'],
 ['Åland', '26711'],
 ['Azerbaijan', '8303512'],
 ['Bosnia and Herzegovina', '4590000'],
 ['Barbados', '285653'],
 ['Bangladesh', '156118464'],
 ['Belgium', '10403000'],
 ['Burkina Faso', '16241811'],
 ['Bulgaria', '7148785'],
 ['Bahrain', '738004'],
 ['Burundi', '9863117'],
 ['Benin', '9056010'],
 ['Saint Barthélemy', '8450'],
 ['Bermuda', '65365'],
 ['Brunei', '395027'],
 ['Bolivia', '9947418'],
 ['Bonaire', '18012'],
 ['Brazil', '201103330'],
 ['Bahamas', '301790'],
 ['Bhutan', '699847'],
 ['Bouvet Island', '0'],
 ['Botswana', '2029307'],
 ['Belarus', '9685000'],
 ['Belize', '314522'],
 ['Canada', '33679000'],
 ['Cocos [Keeling] Islands', '628'],
 ['Democratic Republic of the Congo', '70916439'],
 ['Central African Republic', '4844927'],
 ['Republic of the Congo', '3039126'],
 ['Switzerland', '7581000'],
 ['Ivory Coast', '21058798'],
 ['Cook Islands', '21388'],
 ['Chile', '16746491'],
 ['Cameroon', '19294149'],
 ['China', '1330044000'],
 ['Colombia', '47790000'],
 ['Costa Rica', '4516220'],
 ['Cuba', '11423000'],
 ['Cape Verde', '508659'],
 ['Curacao', '141766'],
 ['Christmas Island', '1500'],
 ['Cyprus', '1102677'],
 ['Czech Republic', '10476000'],
 ['Germany', '81802257'],
 ['Djibouti', '740528'],
 ['Denmark', '5484000'],
 ['Dominica', '72813'],
 ['Dominican Republic', '9823821'],
 ['Algeria', '34586184'],
 ['Ecuador', '14790608'],
 ['Estonia', '1291170'],
 ['Egypt', '80471869'],
 ['Western Sahara', '273008'],
 ['Eritrea', '5792984'],
 ['Spain', '46505963'],
 ['Ethiopia', '88013491'],
 ['Finland', '5244000'],
 ['Fiji', '875983'],
 ['Falkland Islands', '2638'],
 ['Micronesia', '107708'],
 ['Faroe Islands', '48228'],
 ['France', '64768389'],
 ['Gabon', '1545255'],
 ['United Kingdom', '62348447'],
 ['Grenada', '107818'],
 ['Georgia', '4630000'],
 ['French Guiana', '195506'],
 ['Guernsey', '65228'],
 ['Ghana', '24339838'],
 ['Gibraltar', '27884'],
 ['Greenland', '56375'],
 ['Gambia', '1593256'],
 ['Guinea', '10324025'],
 ['Guadeloupe', '443000'],
 ['Equatorial Guinea', '1014999'],
 ['Greece', '11000000'],
 ['South Georgia and the South Sandwich Islands', '30'],
 ['Guatemala', '13550440'],
 ['Guam', '159358'],
 ['Guinea-Bissau', '1565126'],
 ['Guyana', '748486'],
 ['Hong Kong', '6898686'],
 ['Heard Island and McDonald Islands', '0'],
 ['Honduras', '7989415'],
 ['Croatia', '4491000'],
 ['Haiti', '9648924'],
 ['Hungary', '9982000'],
 ['Indonesia', '242968342'],
 ['Ireland', '4622917'],
 ['Israel', '7353985'],
 ['Isle of Man', '75049'],
 ['India', '1173108018'],
 ['British Indian Ocean Territory', '4000'],
 ['Iraq', '29671605'],
 ['Iran', '76923300'],
 ['Iceland', '308910'],
 ['Italy', '60340328'],
 ['Jersey', '90812'],
 ['Jamaica', '2847232'],
 ['Jordan', '6407085'],
 ['Japan', '127288000'],
 ['Kenya', '40046566'],
 ['Kyrgyzstan', '5776500'],
 ['Cambodia', '14453680'],
 ['Kiribati', '92533'],
 ['Comoros', '773407'],
 ['Saint Kitts and Nevis', '51134'],
 ['North Korea', '22912177'],
 ['South Korea', '48422644'],
 ['Kuwait', '2789132'],
 ['Cayman Islands', '44270'],
 ['Kazakhstan', '15340000'],
 ['Laos', '6368162'],
 ['Lebanon', '4125247'],
 ['Saint Lucia', '160922'],
 ['Liechtenstein', '35000'],
 ['Sri Lanka', '21513990'],
 ['Liberia', '3685076'],
 ['Lesotho', '1919552'],
 ['Lithuania', '2944459'],
 ['Luxembourg', '497538'],
 ['Latvia', '2217969'],
 ['Libya', '6461454'],
 ['Morocco', '31627428'],
 ['Monaco', '32965'],
 ['Moldova', '4324000'],
 ['Montenegro', '666730'],
 ['Saint Martin', '35925'],
 ['Madagascar', '21281844'],
 ['Marshall Islands', '65859'],
 ['Macedonia', '2062294'],
 ['Mali', '13796354'],
 ['Myanmar [Burma]', '53414374'],
 ['Mongolia', '3086918'],
 ['Macao', '449198'],
 ['Northern Mariana Islands', '53883'],
 ['Martinique', '432900'],
 ['Mauritania', '3205060'],
 ['Montserrat', '9341'],
 ['Malta', '403000'],
 ['Mauritius', '1294104'],
 ['Maldives', '395650'],
 ['Malawi', '15447500'],
 ['Mexico', '112468855'],
 ['Malaysia', '28274729'],
 ['Mozambique', '22061451'],
 ['Namibia', '2128471'],
 ['New Caledonia', '216494'],
 ['Niger', '15878271'],
 ['Norfolk Island', '1828'],
 ['Nigeria', '154000000'],
 ['Nicaragua', '5995928'],
 ['Netherlands', '16645000'],
 ['Norway', '5009150'],
 ['Nepal', '28951852'],
 ['Nauru', '10065'],
 ['Niue', '2166'],
 ['New Zealand', '4252277'],
 ['Oman', '2967717'],
 ['Panama', '3410676'],
 ['Peru', '29907003'],
 ['French Polynesia', '270485'],
 ['Papua New Guinea', '6064515'],
 ['Philippines', '99900177'],
 ['Pakistan', '184404791'],
 ['Poland', '38500000'],
 ['Saint Pierre and Miquelon', '7012'],
 ['Pitcairn Islands', '46'],
 ['Puerto Rico', '3916632'],
 ['Palestine', '3800000'],
 ['Portugal', '10676000'],
 ['Palau', '19907'],
 ['Paraguay', '6375830'],
 ['Qatar', '840926'],
 ['Réunion', '776948'],
 ['Romania', '21959278'],
 ['Serbia', '7344847'],
 ['Russia', '140702000'],
 ['Rwanda', '11055976'],
 ['Saudi Arabia', '25731776'],
 ['Solomon Islands', '559198'],
 ['Seychelles', '88340'],
 ['Sudan', '35000000'],
 ['Sweden', '9828655'],
 ['Singapore', '4701069'],
 ['Saint Helena', '7460'],
 ['Slovenia', '2007000'],
 ['Svalbard and Jan Mayen', '2550'],
 ['Slovakia', '5455000'],
 ['Sierra Leone', '5245695'],
 ['San Marino', '31477'],
 ['Senegal', '12323252'],
 ['Somalia', '10112453'],
 ['Suriname', '492829'],
 ['South Sudan', '8260490'],
 ['São Tomé and Príncipe', '175808'],
 ['El Salvador', '6052064'],
 ['Sint Maarten', '37429'],
 ['Syria', '22198110'],
 ['Swaziland', '1354051'],
 ['Turks and Caicos Islands', '20556'],
 ['Chad', '10543464'],
 ['French Southern Territories', '140'],
 ['Togo', '6587239'],
 ['Thailand', '67089500'],
 ['Tajikistan', '7487489'],
 ['Tokelau', '1466'],
 ['East Timor', '1154625'],
 ['Turkmenistan', '4940916'],
 ['Tunisia', '10589025'],
 ['Tonga', '122580'],
 ['Turkey', '77804122'],
 ['Trinidad and Tobago', '1228691'],
 ['Tuvalu', '10472'],
 ['Taiwan', '22894384'],
 ['Tanzania', '41892895'],
 ['Ukraine', '45415596'],
 ['Uganda', '33398682'],
 ['U.S. Minor Outlying Islands', '0'],
 ['United States', '310232863'],
 ['Uruguay', '3477000'],
 ['Uzbekistan', '27865738'],
 ['Vatican City', '921'],
 ['Saint Vincent and the Grenadines', '104217'],
 ['Venezuela', '27223228'],
 ['British Virgin Islands', '21730'],
 ['U.S. Virgin Islands', '108708'],
 ['Vietnam', '89571130'],
 ['Vanuatu', '221552'],
 ['Wallis and Futuna', '16025'],
 ['Samoa', '192001'],
 ['Kosovo', '1800000'],
 ['Yemen', '23495361'],
 ['Mayotte', '159042'],
 ['South Africa', '49000000'],
 ['Zambia', '13460305'],
 ['Zimbabwe', '11651858']]

In [41]:
df=pd.DataFrame(all_countries,columns=["Country","Population"])

In [42]:
df

                  Country Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

# ____________________________________________________________

In [43]:
with open("scraped_data/data5.html","r") as f:
    html_content=f.read()

In [44]:
html_content

'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="countries">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Countries of the World: A Simple Example\n                            <small>250 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row">\n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ad"></i>\n                            Andorra\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>\n                            <strong>Population:</strong> <span class="country-population">84000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ae"></i>\n                            United Arab Emirates\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>\n                            <strong>Population:</strong> <span class="country-population">4975593</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-af"></i>\n                            Afghanistan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>\n                            <strong>Population:</strong> <span class="country-population">29121286</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ag"></i>\n                            Antigua and Barbuda\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>\n                            <strong>Population:</strong> <span class="country-population">86754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ai"></i>\n                            Anguilla\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>\n                            <strong>Population:</strong> <span class="country-population">13254</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-al"></i>\n                            Albania\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>\n                            <strong>Population:</strong> <span class="country-population">2986952</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-am"></i>\n                            Armenia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>\n                            <strong>Population:</strong> <span class="country-population">2968000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ao"></i>\n                            Angola\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>\n                            <strong>Population:</strong> <span class="country-population">13068161</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aq"></i>\n                            Antarctica\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">None</span><br>\n                            <strong>Population:</strong> <span class="country-population">0</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ar"></i>\n                            Argentina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>\n                            <strong>Population:</strong> <span class="country-population">41343201</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-as"></i>\n                            American Samoa\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>\n                            <strong>Population:</strong> <span class="country-population">57881</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-at"></i>\n                            Austria\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>\n                            <strong>Population:</strong> <span class="country-population">8205000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-au"></i>\n                            Australia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>\n                            <strong>Population:</strong> <span class="country-population">21515754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aw"></i>\n                            Aruba\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>\n                            <strong>Population:</strong> <span class="country-population">71566</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ax"></i>\n                            Åland\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>\n                            <strong>Population:</strong> <span class="country-population">26711</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-az"></i>\n                            Azerbaijan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>\n                            <strong>Population:</strong> <span class="country-population">8303512</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ba"></i>\n                            Bosnia and Herzegovina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>\n                            <strong>Population:</strong> <span class="country-population">4590000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-bb"></i>\n                            Barbados\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>\n                            <strong>Population:</strong> <span class="country-population">285653</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 cou

In [45]:
soup=bs(html_content,'lxml')

In [46]:
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

In [47]:
soup.h3

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [48]:
all_h3=soup.find_all('h3')

In [49]:
all_h3

[<h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ci"></i>
                             Ivory Coast
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ck"></i>
                             Cook Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cl"></i>
                             Chile
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cm"></i>
                             Cameroon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cn"></i>
                             China
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-co"></i>
                             Colombia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cr"></i>
                             Costa Rica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cu"></i>
                             Cuba
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cv"></i>
                             Cape Verde
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cw"></i>
                             Curacao
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cx"></i>
                             Christmas Island
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cy"></i>
                             Cyprus
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cz"></i>
                             Czech Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-de"></i>
                             Germany
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dj"></i>
                             Djibouti
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dk"></i>
                             Denmark
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dm"></i>
                             Dominica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-do"></i>
                             Dominican Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dz"></i>
                             Algeria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ec"></i>
                             Ecuador
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ee"></i>
                             Estonia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eg"></i>
                             Egypt
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eh"></i>
                             Western Sahara
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-er"></i>
                             Eritrea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-es"></i>
                             Spain
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-et"></i>
                             Ethiopia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fi"></i>
                             Finland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fj"></i>
                             Fiji
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fk"></i>
                             Falkland Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fm"></i>
                             Micronesia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fo"></i>
                             Faroe Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fr"></i>
                             France
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ga"></i>
                             Gabon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gb"></i>
                             United Kingdom
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gd"></i>
                             Grenada
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ge"></i>
                             Georgia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gf"></i>
                             French Guiana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gg"></i>
                             Guernsey
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gh"></i>
                             Ghana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gi"></i>
                             Gibraltar
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gl"></i>
                             Greenland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gm"></i>
                             Gambia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gn"></i>
                             Guinea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gp"></i>
                             Guadeloupe
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gq"></i>
                             Equatorial Guinea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gr"></i>
                             Greece
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gs"></i>
                             South Georgia and the South Sandwich Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gt"></i>
                             Guatemala
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gu"></i>
                             Guam
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gw"></i>
                             Guinea-Bissau
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gy"></i>
                             Guyana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hk"></i>
                             Hong Kong
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hm"></i>
                             Heard Island and McDonald Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hn"></i>
                             Honduras
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hr"></i>
                             Croatia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ht"></i>
                             Haiti
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hu"></i>
                             Hungary
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-id"></i>
                             Indonesia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ie"></i>
                             Ireland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-il"></i>
                             Israel
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-im"></i>
                             Isle of Man
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-in"></i>
                             India
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-io"></i>
                             British Indian Ocean Territory
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-iq"></i>
                             Iraq
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ir"></i>
                             Iran
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-is"></i>
                             Iceland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-it"></i>
                             Italy
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-je"></i>
                             Jersey
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jm"></i>
                             Jamaica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jo"></i>
                             Jordan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jp"></i>
                             Japan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ke"></i>
                             Kenya
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kg"></i>
                             Kyrgyzstan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kh"></i>
                             Cambodia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ki"></i>
                             Kiribati
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-km"></i>
                             Comoros
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kn"></i>
                             Saint Kitts and Nevis
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kp"></i>
                             North Korea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kr"></i>
                             South Korea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kw"></i>
                             Kuwait
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ky"></i>
                             Cayman Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kz"></i>
                             Kazakhstan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-la"></i>
                             Laos
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lb"></i>
                             Lebanon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lc"></i>
                             Saint Lucia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-li"></i>
                             Liechtenstein
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lk"></i>
                             Sri Lanka
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lr"></i>
                             Liberia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ls"></i>
                             Lesotho
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lt"></i>
                             Lithuania
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lu"></i>
                             Luxembourg
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lv"></i>
                             Latvia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ly"></i>
                             Libya
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ma"></i>
                             Morocco
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mc"></i>
                             Monaco
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-md"></i>
                             Moldova
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-me"></i>
                             Montenegro
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mf"></i>
                             Saint Martin
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mg"></i>
                             Madagascar
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mh"></i>
                             Marshall Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mk"></i>
                             Macedonia
                         </h3>,
 <h3 class="country-name">

In [50]:
country_info=[]
for h3 in all_h3:
    country_name=h3.get_text(strip=True)
    Capital=h3.findNext('div').select('span.country-capital')[0].get_text(strip=True)
    Population=h3.findNext('div').select('span.country-population')[0].get_text(strip=True)
    Area_km2=h3.findNext('div').select('span.country-area')[0].get_text(strip=True)

    country_info.append([country_name,Capital,Population,Area_km2])

In [51]:
country_info

[['Andorra', 'Andorra la Vella', '84000', '468.0'],
 ['United Arab Emirates', 'Abu Dhabi', '4975593', '82880.0'],
 ['Afghanistan', 'Kabul', '29121286', '647500.0'],
 ['Antigua and Barbuda', "St. John's", '86754', '443.0'],
 ['Anguilla', 'The Valley', '13254', '102.0'],
 ['Albania', 'Tirana', '2986952', '28748.0'],
 ['Armenia', 'Yerevan', '2968000', '29800.0'],
 ['Angola', 'Luanda', '13068161', '1246700.0'],
 ['Antarctica', 'None', '0', '1.4E7'],
 ['Argentina', 'Buenos Aires', '41343201', '2766890.0'],
 ['American Samoa', 'Pago Pago', '57881', '199.0'],
 ['Austria', 'Vienna', '8205000', '83858.0'],
 ['Australia', 'Canberra', '21515754', '7686850.0'],
 ['Aruba', 'Oranjestad', '71566', '193.0'],
 ['Åland', 'Mariehamn', '26711', '1580.0'],
 ['Azerbaijan', 'Baku', '8303512', '86600.0'],
 ['Bosnia and Herzegovina', 'Sarajevo', '4590000', '51129.0'],
 ['Barbados', 'Bridgetown', '285653', '431.0'],
 ['Bangladesh', 'Dhaka', '156118464', '144000.0'],
 ['Belgium', 'Brussels', '10403000', '30510.0'],
 ['Burkina Faso', 'Ouagadougou', '16241811', '274200.0'],
 ['Bulgaria', 'Sofia', '7148785', '110910.0'],
 ['Bahrain', 'Manama', '738004', '665.0'],
 ['Burundi', 'Bujumbura', '9863117', '27830.0'],
 ['Benin', 'Porto-Novo', '9056010', '112620.0'],
 ['Saint Barthélemy', 'Gustavia', '8450', '21.0'],
 ['Bermuda', 'Hamilton', '65365', '53.0'],
 ['Brunei', 'Bandar Seri Begawan', '395027', '5770.0'],
 ['Bolivia', 'Sucre', '9947418', '1098580.0'],
 ['Bonaire', 'Kralendijk', '18012', '328.0'],
 ['Brazil', 'Brasília', '201103330', '8511965.0'],
 ['Bahamas', 'Nassau', '301790', '13940.0'],
 ['Bhutan', 'Thimphu', '699847', '47000.0'],
 ['Bouvet Island', 'None', '0', '49.0'],
 ['Botswana', 'Gaborone', '2029307', '600370.0'],
 ['Belarus', 'Minsk', '9685000', '207600.0'],
 ['Belize', 'Belmopan', '314522', '22966.0'],
 ['Canada', 'Ottawa', '33679000', '9984670.0'],
 ['Cocos [Keeling] Islands', 'West Island', '628', '14.0'],
 ['Democratic Republic of the Congo', 'Kinshasa', '70916439', '2345410.0'],
 ['Central African Republic', 'Bangui', '4844927', '622984.0'],
 ['Republic of the Congo', 'Brazzaville', '3039126', '342000.0'],
 ['Switzerland', 'Bern', '7581000', '41290.0'],
 ['Ivory Coast', 'Yamoussoukro', '21058798', '322460.0'],
 ['Cook Islands', 'Avarua', '21388', '240.0'],
 ['Chile', 'Santiago', '16746491', '756950.0'],
 ['Cameroon', 'Yaoundé', '19294149', '475440.0'],
 ['China', 'Beijing', '1330044000', '9596960.0'],
 ['Colombia', 'Bogotá', '47790000', '1138910.0'],
 ['Costa Rica', 'San José', '4516220', '51100.0'],
 ['Cuba', 'Havana', '11423000', '110860.0'],
 ['Cape Verde', 'Praia', '508659', '4033.0'],
 ['Curacao', 'Willemstad', '141766', '444.0'],
 ['Christmas Island', 'Flying Fish Cove', '1500', '135.0'],
 ['Cyprus', 'Nicosia', '1102677', '9250.0'],
 ['Czech Republic', 'Prague', '10476000', '78866.0'],
 ['Germany', 'Berlin', '81802257', '357021.0'],
 ['Djibouti', 'Djibouti', '740528', '23000.0'],
 ['Denmark', 'Copenhagen', '5484000', '43094.0'],
 ['Dominica', 'Roseau', '72813', '754.0'],
 ['Dominican Republic', 'Santo Domingo', '9823821', '48730.0'],
 ['Algeria', 'Algiers', '34586184', '2381740.0'],
 ['Ecuador', 'Quito', '14790608', '283560.0'],
 ['Estonia', 'Tallinn', '1291170', '45226.0'],
 ['Egypt', 'Cairo', '80471869', '1001450.0'],
 ['Western Sahara', 'Laâyoune / El Aaiún', '273008', '266000.0'],
 ['Eritrea', 'Asmara', '5792984', '121320.0'],
 ['Spain', 'Madrid', '46505963', '504782.0'],
 ['Ethiopia', 'Addis Ababa', '88013491', '1127127.0'],
 ['Finland', 'Helsinki', '5244000', '337030.0'],
 ['Fiji', 'Suva', '875983', '18270.0'],
 ['Falkland Islands', 'Stanley', '2638', '12173.0'],
 ['Micronesia', 'Palikir', '107708', '702.0'],
 ['Faroe Islands', 'Tórshavn', '48228', '1399.0'],
 ['France', 'Paris', '64768389', '547030.0'],
 ['Gabon', 'Libreville', '1545255', '267667.0'],
 ['United Kingdom', 'London', '62348447', '244820.0'],
 ['Grenada', "St. George's", '107818', '344.0'],
 ['Georgia', 'Tbilisi', '4630000', '69700.0'],
 ['French Guiana', 'Cayenne', '195506', '91000.0'],
 ['Guernsey', 'St Peter Port', '65228', '78.0'],
 ['Ghana', 'Accra', '24339838', '239460.0'],
 ['Gibraltar', 'Gibraltar', '27884', '6.5'],
 ['Greenland', 'Nuuk', '56375', '2166086.0'],
 ['Gambia', 'Bathurst', '1593256', '11300.0'],
 ['Guinea', 'Conakry', '10324025', '245857.0'],
 ['Guadeloupe', 'Basse-Terre', '443000', '1780.0'],
 ['Equatorial Guinea', 'Malabo', '1014999', '28051.0'],
 ['Greece', 'Athens', '11000000', '131940.0'],
 ['South Georgia and the South Sandwich Islands', 'Grytviken', '30', '3903.0'],
 ['Guatemala', 'Guatemala City', '13550440', '108890.0'],
 ['Guam', 'Hagåtña', '159358', '549.0'],
 ['Guinea-Bissau', 'Bissau', '1565126', '36120.0'],
 ['Guyana', 'Georgetown', '748486', '214970.0'],
 ['Hong Kong', 'Hong Kong', '6898686', '1092.0'],
 ['Heard Island and McDonald Islands', 'None', '0', '412.0'],
 ['Honduras', 'Tegucigalpa', '7989415', '112090.0'],
 ['Croatia', 'Zagreb', '4491000', '56542.0'],
 ['Haiti', 'Port-au-Prince', '9648924', '27750.0'],
 ['Hungary', 'Budapest', '9982000', '93030.0'],
 ['Indonesia', 'Jakarta', '242968342', '1919440.0'],
 ['Ireland', 'Dublin', '4622917', '70280.0'],
 ['Israel', 'None', '7353985', '20770.0'],
 ['Isle of Man', 'Douglas', '75049', '572.0'],
 ['India', 'New Delhi', '1173108018', '3287590.0'],
 ['British Indian Ocean Territory', 'None', '4000', '60.0'],
 ['Iraq', 'Baghdad', '29671605', '437072.0'],
 ['Iran', 'Tehran', '76923300', '1648000.0'],
 ['Iceland', 'Reykjavik', '308910', '103000.0'],
 ['Italy', 'Rome', '60340328', '301230.0'],
 ['Jersey', 'Saint Helier', '90812', '116.0'],
 ['Jamaica', 'Kingston', '2847232', '10991.0'],
 ['Jordan', 'Amman', '6407085', '92300.0'],
 ['Japan', 'Tokyo', '127288000', '377835.0'],
 ['Kenya', 'Nairobi', '40046566', '582650.0'],
 ['Kyrgyzstan', 'Bishkek', '5776500', '198500.0'],
 ['Cambodia', 'Phnom Penh', '14453680', '181040.0'],
 ['Kiribati', 'Tarawa', '92533', '811.0'],
 ['Comoros', 'Moroni', '773407', '2170.0'],
 ['Saint Kitts and Nevis', 'Basseterre', '51134', '261.0'],
 ['North Korea', 'Pyongyang', '22912177', '120540.0'],
 ['South Korea', 'Seoul', '48422644', '98480.0'],
 ['Kuwait', 'Kuwait City', '2789132', '17820.0'],
 ['Cayman Islands', 'George Town', '44270', '262.0'],
 ['Kazakhstan', 'Astana', '15340000', '2717300.0'],
 ['Laos', 'Vientiane', '6368162', '236800.0'],
 ['Lebanon', 'Beirut', '4125247', '10400.0'],
 ['Saint Lucia', 'Castries', '160922', '616.0'],
 ['Liechtenstein', 'Vaduz', '35000', '160.0'],
 ['Sri Lanka', 'Colombo', '21513990', '65610.0'],
 ['Liberia', 'Monrovia', '3685076', '111370.0'],
 ['Lesotho', 'Maseru', '1919552', '30355.0'],
 ['Lithuania', 'Vilnius', '2944459', '65200.0'],
 ['Luxembourg', 'Luxembourg', '497538', '2586.0'],
 ['Latvia', 'Riga', '2217969', '64589.0'],
 ['Libya', 'Tripoli', '6461454', '1759540.0'],
 ['Morocco', 'Rabat', '31627428', '446550.0'],
 ['Monaco', 'Monaco', '32965', '1.95'],
 ['Moldova', 'Chişinău', '4324000', '33843.0'],
 ['Montenegro', 'Podgorica', '666730', '14026.0'],
 ['Saint Martin', 'Marigot', '35925', '53.0'],
 ['Madagascar', 'Antananarivo', '21281844', '587040.0'],
 ['Marshall Islands', 'Majuro', '65859', '181.3'],
 ['Macedonia', 'Skopje', '2062294', '25333.0'],
 ['Mali', 'Bamako', '13796354', '1240000.0'],
 ['Myanmar [Burma]', 'Naypyitaw', '53414374', '678500.0'],
 ['Mongolia', 'Ulan Bator', '3086918', '1565000.0'],
 ['Macao', 'Macao', '449198', '254.0'],
 ['Northern Mariana Islands', 'Saipan', '53883', '477.0'],
 ['Martinique', 'Fort-de-France', '432900', '1100.0'],
 ['Mauritania', 'Nouakchott', '3205060', '1030700.0'],
 ['Montserrat', 'Plymouth', '9341', '102.0'],
 ['Malta', 'Valletta', '403000', '316.0'],
 ['Mauritius', 'Port Louis', '1294104', '2040.0'],
 ['Maldives', 'Malé', '395650', '300.0'],
 ['Malawi', 'Lilongwe', '15447500', '118480.0'],
 ['Mexico', 'Mexico City', '112468855', '1972550.0'],
 ['Malaysia', 'Kuala Lumpur', '28274729', '329750.0'],
 ['Mozambique', 'Maputo', '22061451', '801590.0'],
 ['Namibia', 'Windhoek', '2128471', '825418.0'],
 ['New Caledonia', 'Noumea', '216494', '19060.0'],
 ['Niger', 'Niamey', '15878271', '1267000.0'],
 ['Norfolk Island', 'Kingston', '1828', '34.6'],
 ['Nigeria', 'Abuja', '154000000', '923768.0'],
 ['Nicaragua', 'Managua', '5995928', '129494.0'],
 ['Netherlands', 'Amsterdam', '16645000', '41526.0'],
 ['Norway', 'Oslo', '5009150', '324220.0'],
 ['Nepal', 'Kathmandu', '28951852', '140800.0'],
 ['Nauru', 'Yaren', '10065', '21.0'],
 ['Niue', 'Alofi', '2166', '260.0'],
 ['New Zealand', 'Wellington', '4252277', '268680.0'],
 ['Oman', 'Muscat', '2967717', '212460.0'],
 ['Panama', 'Panama City', '3410676', '78200.0'],
 ['Peru', 'Lima', '29907003', '1285220.0'],
 ['French Polynesia', 'Papeete', '270485', '4167.0'],
 ['Papua New Guinea', 'Port Moresby', '6064515', '462840.0'],
 ['Philippines', 'Manila', '99900177', '300000.0'],
 ['Pakistan', 'Islamabad', '184404791', '803940.0'],
 ['Poland', 'Warsaw', '38500000', '312685.0'],
 ['Saint Pierre and Miquelon', 'Saint-Pierre', '7012', '242.0'],
 ['Pitcairn Islands', 'Adamstown', '46', '47.0'],
 ['Puerto Rico', 'San Juan', '3916632', '9104.0'],
 ['Palestine', 'None', '3800000', '5970.0'],
 ['Portugal', 'Lisbon', '10676000', '92391.0'],
 ['Palau', 'Melekeok', '19907', '458.0'],
 ['Paraguay', 'Asunción', '6375830', '406750.0'],
 ['Qatar', 'Doha', '840926', '11437.0'],
 ['Réunion', 'Saint-Denis', '776948', '2517.0'],
 ['Romania', 'Bucharest', '21959278', '237500.0'],
 ['Serbia', 'Belgrade', '7344847', '88361.0'],
 ['Russia', 'Moscow', '140702000', '1.71E7'],
 ['Rwanda', 'Kigali', '11055976', '26338.0'],
 ['Saudi Arabia', 'Riyadh', '25731776', '1960582.0'],
 ['Solomon Islands', 'Honiara', '559198', '28450.0'],
 ['Seychelles', 'Victoria', '88340', '455.0'],
 ['Sudan', 'Khartoum', '35000000', '1861484.0'],
 ['Sweden', 'Stockholm', '9828655', '449964.0'],
 ['Singapore', 'Singapore', '4701069', '692.7'],
 ['Saint Helena', 'Jamestown', '7460', '410.0'],
 ['Slovenia', 'Ljubljana', '2007000', '20273.0'],
 ['Svalbard and Jan Mayen', 'Longyearbyen', '2550', '62049.0'],
 ['Slovakia', 'Bratislava', '5455000', '48845.0'],
 ['Sierra Leone', 'Freetown', '5245695', '71740.0'],
 ['San Marino', 'San Marino', '31477', '61.2'],
 ['Senegal', 'Dakar', '12323252', '196190.0'],
 ['Somalia', 'Mogadishu', '10112453', '637657.0'],
 ['Suriname', 'Paramaribo', '492829', '163270.0'],
 ['South Sudan', 'Juba', '8260490', '644329.0'],
 ['São Tomé and Príncipe', 'São Tomé', '175808', '1001.0'],
 ['El Salvador', 'San Salvador', '6052064', '21040.0'],
 ['Sint Maarten', 'Philipsburg', '37429', '21.0'],
 ['Syria', 'Damascus', '22198110', '185180.0'],
 ['Swaziland', 'Mbabane', '1354051', '17363.0'],
 ['Turks and Caicos Islands', 'Cockburn Town', '20556', '430.0'],
 ['Chad', "N'Djamena", '10543464', '1284000.0'],
 ['French Southern Territories', 'Port-aux-Français', '140', '7829.0'],
 ['Togo', 'Lomé', '6587239', '56785.0'],
 ['Thailand', 'Bangkok', '67089500', '514000.0'],
 ['Tajikistan', 'Dushanbe', '7487489', '143100.0'],
 ['Tokelau', 'None', '1466', '10.0'],
 ['East Timor', 'Dili', '1154625', '15007.0'],
 ['Turkmenistan', 'Ashgabat', '4940916', '488100.0'],
 ['Tunisia', 'Tunis', '10589025', '163610.0'],
 ['Tonga', "Nuku'alofa", '122580', '748.0'],
 ['Turkey', 'Ankara', '77804122', '780580.0'],
 ['Trinidad and Tobago', 'Port of Spain', '1228691', '5128.0'],
 ['Tuvalu', 'Funafuti', '10472', '26.0'],
 ['Taiwan', 'Taipei', '22894384', '35980.0'],
 ['Tanzania', 'Dodoma', '41892895', '945087.0'],
 ['Ukraine', 'Kiev', '45415596', '603700.0'],
 ['Uganda', 'Kampala', '33398682', '236040.0'],
 ['U.S. Minor Outlying Islands', 'None', '0', '0.0'],
 ['United States', 'Washington', '310232863', '9629091.0'],
 ['Uruguay', 'Montevideo', '3477000', '176220.0'],
 ['Uzbekistan', 'Tashkent', '27865738', '447400.0'],
 ['Vatican City', 'Vatican City', '921', '0.44'],
 ['Saint Vincent and the Grenadines', 'Kingstown', '104217', '389.0'],
 ['Venezuela', 'Caracas', '27223228', '912050.0'],
 ['British Virgin Islands', 'Road Town', '21730', '153.0'],
 ['U.S. Virgin Islands', 'Charlotte Amalie', '108708', '352.0'],
 ['Vietnam', 'Hanoi', '89571130', '329560.0'],
 ['Vanuatu', 'Port Vila', '221552', '12200.0'],
 ['Wallis and Futuna', 'Mata-Utu', '16025', '274.0'],
 ['Samoa', 'Apia', '192001', '2944.0'],
 ['Kosovo', 'Pristina', '1800000', '10908.0'],
 ['Yemen', 'Sanaa', '23495361', '527970.0'],
 ['Mayotte', 'Mamoudzou', '159042', '374.0'],
 ['South Africa', 'Pretoria', '49000000', '1219912.0'],
 ['Zambia', 'Lusaka', '13460305', '752614.0'],
 ['Zimbabwe', 'Harare', '11651858', '390580.0']]

In [52]:
df=pd.DataFrame(country_info,columns=["Country Name","Capital","Population","Area_km2"])

In [53]:
df

             Country Name           Capital Population   Area_km2
0                 Andorra  Andorra la Vella      84000      468.0
1    United Arab Emirates         Abu Dhabi    4975593    82880.0
2             Afghanistan             Kabul   29121286   647500.0
3     Antigua and Barbuda        St. John's      86754      443.0
4                Anguilla        The Valley      13254      102.0
..                    ...               ...        ...        ...
245                 Yemen             Sanaa   23495361   527970.0
246               Mayotte         Mamoudzou     159042      374.0
247          South Africa          Pretoria   49000000  1219912.0
248                Zambia            Lusaka   13460305   752614.0
249              Zimbabwe            Harare   11651858   390580.0

[250 rows x 4 columns]

In [54]:
df.to_csv("Country Info",index=False)

# ______________________________________________

In [55]:
with open("scraped_data/data6.html","r") as f:
    html_content=f.read()

In [56]:
html_content

'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="hockey">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Hockey Teams: Forms, Searching and Pagination\n                            <small>25 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.\n                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://www.opensourcesports.com/hockey/" class="data-attribution" target="_blank">http://www.opensourcesports.com/hockey/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row search-area">\n                    <div class="col-md-12 text-center">\n                        <form method="GET" action="/pages/forms/" class="form form-inline">\n                            <label for="q">\n                                Search for Teams: &nbsp;\n                            </label>\n                            <input type="text" class="form-control" name="q" id="q" placeholder="Search for Teams" />\n                            \n                            <input type="submit" class="btn btn-primary" value="Search" />\n                        </form>\n                        <hr>\n                    </div>\n                </div><!--.row.search-area-->\n\n\n                <table class="table">\n                    <tr>\n                        <th>\n                            Team Name\n                        </th>\n                        <th>\n                            Year\n                        </th>\n                        <th>\n                            Wins\n                        </th>\n                        <th>\n                            Losses\n                        </th>\n                        <th>\n                            OT Losses\n                        </th>\n                        <th>\n                            Win %\n                        </th>\n                        <th>\n                            Goals For (GF)\n                        </th>\n                        <th>\n                            Goals Against (GA)\n                        </th>\n                        <th>\n                            + / -\n                        </th>\n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Boston Bruins\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            44\n                        </td>\n                        <td class="losses">\n                            24\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.55\n                        </td>\n                        \n                        <td class="gf">\n                            299\n                        </td>\n                        <td class="ga">\n                            264\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            35\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Buffalo Sabres\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            31\n                        </td>\n                        <td class="losses">\n                            30\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.388\n                        </td>\n                        \n                        <td class="gf">\n                            292\n                        </td>\n                        <td class="ga">\n                            278\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            14\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Calgary Flames\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            46\n                        </td>\n                        <td class="losses">\n                            26\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.575\n                        </td>\n                        \n                        <td class="gf">\n                            344\n                        </td>\n                        <td class="ga">\n                            263\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            81\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Chicago Blackhawks\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            49\n                        </td>\n                        <td class="losses">\n                            23\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.613\n                        </td>\n                        \n                        <td class="gf">\n                            284\n                        </td>\n                        <td class="ga">\n                            211\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            73\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Detroit Red Wings\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            34\n                        </td>\n                        <td class="losses">\n                            38\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.425\n                        </td>\n                        \n                        <td class="gf">\n                            273\n                        </td>\n                        <td class="ga">\n                            298\n                        </td>\n                        \n                        \n                        <td class="diff text-danger">\n                            -25\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Edmonton Oilers\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            37\n                        </td>\n                        <td class="losses">\n                            37\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.463\n                        </td>\n                        \n                        <td class="gf">\n                            272\n                        </td>\n                        <td class="ga">\n                            272\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            0\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Hartford Whalers\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            31\n                        </td>\n                        <td class="losses">\n                            38\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.388\n                        </td>\n                        \n                        <td class="gf">\n                            238\n                        </td>\n                        <td class="ga">\n                            276\n                        </td>\n                        \n                        \n                        <td class="diff text-danger">\n                            -38\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Los Angeles Kings\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            46\n                        </td>\n                        <td class="losses">\n                            24\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.575\n                        </td>\n                        \n                        <td class="gf">\n                            340\n                        </td>\n                        <td class="ga">\n                            254\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            86\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Minnesota North Stars\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            27\n                        </td>\n                        <td class="losses">\n                            39\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.338\n                        </td>\n                        \n                        <td class="gf">\n                            256\n                        </td>\n                        <td class="ga">\n                            266\n                        </td>\n                        \n                        \n                        <td class="diff text-danger">\n                            -10\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Montreal Canadiens\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            39\n                        </td>\n                        <td class="losses">\n                            30\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.487\n                        </td>\n                        \n                        <td class="gf">\n                            273\n                        </td>\n                        <td class="ga">\n                            249\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            24\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            New Jersey Devils\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td 

In [57]:
soup=bs(html_content,'lxml')

In [58]:
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">

In [59]:
all_tr=soup.find_all('tr',class_="team")

In [60]:
Hockey_Team=[]
for tr in all_tr:
    Team_Name=tr.findAll("td",class_="name")[0].get_text(strip=True)
    Year=tr.findAll("td",class_="year")[0].get_text(strip=True)
    Wins=tr.findAll("td",class_="wins")[0].get_text(strip=True)
    losses=tr.findAll("td",class_="losses")[0].get_text(strip=True)

    Hockey_Team.append([Team_Name,Year,Wins,losses])

In [61]:
df=pd.DataFrame(Hockey_Team,columns=["Team Name","Year","Wins","Losses"])

In [62]:
df

                Team Name  Year Wins Losses
0           Boston Bruins  1990   44     24
1          Buffalo Sabres  1990   31     30
2          Calgary Flames  1990   46     26
3      Chicago Blackhawks  1990   49     23
4       Detroit Red Wings  1990   34     38
5         Edmonton Oilers  1990   37     37
6        Hartford Whalers  1990   31     38
7       Los Angeles Kings  1990   46     24
8   Minnesota North Stars  1990   27     39
9      Montreal Canadiens  1990   39     30
10      New Jersey Devils  1990   32     33
11     New York Islanders  1990   25     45
12       New York Rangers  1990   36     31
13    Philadelphia Flyers  1990   33     37
14    Pittsburgh Penguins  1990   41     33
15       Quebec Nordiques  1990   16     50
16        St. Louis Blues  1990   47     22
17    Toronto Maple Leafs  1990   23     46
18      Vancouver Canucks  1990   28     43
19    Washington Capitals  1990   37     36
20          Winnipeg Jets  1990   26     43
21          Boston Bruins  1991   36     32
22         Buffalo Sabres  1991   31     37
23         Calgary Flames  1991   31     37
24     Chicago Blackhawks  1991   36     29

In [63]:
df.to_csv("Hockey Team Info",index=False)

# __________________________________________________________________

In [64]:
with open("scraped_data/data7.html","r") as f:
    html_content=f.read()

In [ ]:
# print(html_content.json())

AttributeError: 'str' object has no attribute 'json'

In [ ]:
soup=bs(html_content,'html.parser')

In [ ]:
soup

[
  {
    "title": "Spotlight  ",
    "year": 2015,
    "awards": 2,
    "nominations": 6,
    "best_picture": true
  },
  {
    "title": "Mad Max: Fury Road ",
    "year": 2015,
    "awards": 6,
    "nominations": 10
  },
  {
    "title": "The Revenant   ",
    "year": 2015,
    "awards": 3,
    "nominations": 12
  },
  {
    "title": "Bridge of Spies",
    "year": 2015,
    "awards": 1,
    "nominations": 6
  },
  {
    "title": "The Big Short  ",
    "year": 2015,
    "awards": 1,
    "nominations": 5
  },
  {
    "title": "The Danish Girl",
    "year": 2015,
    "awards": 1,
    "nominations": 4
  },
  {
    "title": "Room   ",
    "year": 2015,
    "awards": 1,
    "nominations": 4
  },
  {
    "title": "Ex Machina ",
    "year": 2015,
    "awards": 1,
    "nominations": 2
  },
  {
    "title": "The Hateful Eight  ",
    "year": 2015,
    "awards": 1,
    "nominations": 2
  },
  {
    "title": "Inside Out ",
    "year": 2015,
    "awards": 1,
    "nominations": 2
  },
  {
    "title": "Amy",
    "year": 2015,
    "awards": 1,
    "nominations": 1
  },
  {
    "title": "Bear Story ",
    "year": 2015,
    "awards": 1,
    "nominations": 1
  },
  {
    "title": "A Girl in the River: The Price of Forgiveness  ",
    "year": 2015,
    "awards": 1,
    "nominations": 1
  },
  {
    "title": "Son of Saul",
    "year": 2015,
    "awards": 1,
    "nominations": 1
  },
  {
    "title": "Spectre",
    "year": 2015,
    "awards": 1,
    "nominations": 1
  },
  {
    "title": "Stutterer  ",
    "year": 2015,
    "awards": 1,
    "nominations": 1
  }
]

In [ ]:
rows = soup.find_all("tr", class_="film")

In [ ]:
rows

[]

In [ ]:
for row in rows:
    title = row.find("td", class_="film-title").text.strip()
    nominations = row.find("td", class_="film-nominations").text.strip()
    awards = row.find("td", class_="film-awards").text.strip()

    print(title, nominations, awards)

# _____________________

In [ ]:
with open("scraped_data/data8.html","r") as f:
    html_content=f.read()

In [ ]:
html_content

'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Turtles All the Way Down: Frames &amp; iFrames | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    \n\n        <div id="page">\n\n            <section id="frames">\n                <div class="container">\n\n                    <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Turtles All the Way Down: Frames &amp; iFrames\n                            <small>14 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.\n                            See if you can find the &#39;real&#39; URL that our content is being loaded from, and scrape that page. Also practice interating over a list of items and loading their detail pages to get more information about each one.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">3 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="https://en.wikipedia.org/wiki/List_of_Testudines_families" class="data-attribution" target="_blank">https://en.wikipedia.org/wiki/List_of_Testudines_families</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                    <div class="row">\n                        <div class="col-md-12">\n                            <frameset rows="10%,80%,10%">\n                                <frame name="top" src="/pages/frames/?frame=top" />\n                                <frame name="main" src="/pages/frames/?frame=main" />\n                                <frame name="bottom" src="/pages/frames/frame=bottom" />\n                                <noframes>\n                                        Your browser does not support frames.\n                                </noframes>\n                            </frameset>\n\n                            <iframe src="/pages/frames/?frame=i" id="iframe">\n                                Your browser does not support iframes\n                            </iframe>\n\n                        </div><!--.col-->\n                    </div><!--.row-->\n\n                </div><!--.container-->\n            </section>\n\n        </div><!--#page-->\n\n    \n\n\n    <section id="footer">\n        <div class="container">\n            <div class="row">\n                <div class="col-md-12 text-center text-muted">\n                    Lessons and Videos &copy; Hartley Brody 2023\n                </div><!--.col-->\n            </div><!--.row-->\n        </div><!--.container-->\n    </section>\n  </body>\n\n  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>\n  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>\n\n  \n\n  <script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>\n  <link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css">\n\n  <!-- pnotify messages -->\n  <script type="text/javascript">\n    \n    PNotify.prototype.options.styling = "bootstrap3";\n    $(function(){\n      \n    });\n    \n\n    $(function () {\n      $(\'[data-toggle="tooltip"]\').tooltip()\n    })\n  </script>\n\n  <!-- golbal video controls -->\n  <script type="text/javascript">\n    $("video").hover(function() {\n        $(this).prop("controls", true);\n    }, function() {\n        $(this).prop("controls", false);\n    });\n\n    $("video").click(function() {\n        if( this.paused){\n            this.play();\n        }\n        else {\n            this.pause();\n        }\n    });\n    </script>\n\n  <!-- insert google analytics here -->\n  <script>\n    (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){\n    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n    })(window,document,\'script\',\'https://www.google-analytics.com/analytics.js\',\'ga\');\n\n    ga(\'create\', \'UA-41551755-8\', \'auto\');\n    ga(\'send\', \'pageview\');\n  </script>\n\n  <!-- Facebook Pixel Code -->\n  <script>\n  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?\n  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;\n  n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;\n  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,\n  document,\'script\',\'https://connect.facebook.net/en_US/fbevents.js\');\n\n  fbq(\'init\', \'764287443701341\');\n  fbq(\'track\', "PageView");</script>\n  <noscript><img height="1" width="1" style="display:none"\n  src="https://www.facebook.com/tr?id=764287443701341&ev=PageView&noscript=1"\n  /></noscript>\n  <!-- End Facebook Pixel Code -->\n\n  <!-- Google Code for Remarketing Tag -->\n  <script type="text/javascript">\n    /* <![CDATA[ */\n    var google_conversion_id = 950945448;\n    var google_custom_params = window.google_tag_params;\n    var google_remarketing_only = true;\n    /* ]]> */\n    </script>\n    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">\n    </script>\n    <noscript>\n    <div style="display:inline;">\n    <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0"/>\n    </div>\n  </noscript>\n\n  <!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->\n  <script async src="https://www.googletagmanager.com/gtag/js?id=AW-950945448"></script>\n  <script>\n   window.dataLayer = window.dataLayer || [];\n   function gtag(){dataLayer.push(arguments);}\n   gtag(\'js\', new Date());\n\n   gtag(\'config\', \'AW-950945448\');\n  </script>\n\n</html>'

In [ ]:
soup=bs(html_content,'lxml')

In [ ]:
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Turtles All the Way Down: Frames &amp; iFrames | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="frames">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Turtles All the Way Down: Frames &amp; iFrames
                            <small>14 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.
                            See if you can find the 'real' URL that our content is being loaded from, and scrape that page. Also practice interating over a list of items and loading their detail pages to get more information about each one.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">3 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="https://en.wikipedia.org/wiki/List_of_Testudines_families" target="_blank">https://en.wikipedia.org/wiki/List_of_Testudines_families</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<frameset rows="10%,80%,10%">
<frame name="top" src="/pages/frames/?frame=top"/>
<frame name="main" src="/pages/frames/?frame=main"/>
<frame name="bottom" src="/pages/frames/frame=bottom"/>
<noframes>
                                        Your browser does not support frames.
                                </noframes>
</frameset>
<iframe id="iframe" src="/pages/frames/?frame=i">
                                Your browser does not support iframes
                            </iframe>
</div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
</div><!--#page-->
<section id="footer">
<div class="container">
<div class="row">
<div class="col-md-12 text-center text-muted">
                    Lessons and Videos © Hartley Brody 2023
                </div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script crossorigin="anonymous" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css"/>
<!-- pnotify messages -->
<script type="text/javascript">

    PNotify.prototype.options.styling = "bootstrap3";
    $(function(){

    });


    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
<!-- golbal video controls -->
<script type="text/javascript">
    $("video").hover(function() {
        $(this).prop("controls", true);
    }, function() {
        $(this).prop("controls", false);
    });

    $("video").click(function() {
        if( this.paused){
            this.play();
        }
        else {
            this.pause();
        }
    });
    </script>
<!-- insert google analytics here -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41551755-8', 'auto');
    ga('send', 'pageview');
  </script>
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '764287443701341');
  fbq('track', "PageView");</script>
<noscript><img height="1" src="https://www.facebook.com/tr?id=764287443701341&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
<!-- End Facebook Pixel Code -->
<!-- Google Code for Remarketing Tag -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 950945448;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
    </script>
<script src="//www.googleadservices.com/pagead/conversion.js" type="text/javascript">
</script>
<noscript>
<div style="display:inline;">
<img alt="" height="1" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0" style="border-style:none;" width="1"/>
</div>
</noscript>
<!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-950945448"></script>
<script>
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());

   gtag('config', 'AW-950945448');
  </script>
</html>

In [ ]:
soup.h1

<h1>
                            Turtles All the Way Down: Frames &amp; iFrames
                            <small>14 items</small>
</h1>

In [ ]:
soup.find_all("p",class_="lead")[0].get_text(strip=True)

"Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.\n                            See if you can find the 'real' URL that our content is being loaded from, and scrape that page. Also practice interating over a list of items and loading their detail pages to get more information about each one."

# ________________________________________________

In [66]:
with open("scraped_data/data10.html","r") as f:
    html_content=f.read()

In [67]:
soup=bs(html_content,'lxml')

In [68]:
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Advanced Topics: Real World Challenges You'll Encounter | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Scraping real websites, you're likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="gotchas">
<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3">
<h3>Advanced Topics: Real World Challenges You'll Encounter</h3>
<p class="lead">
                                Scraping real websites, you're likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.
                            </p>
<hr/>
<h4>
<a href="/pages/advanced/?gotcha=headers" target="_blank">Spoofing Headers</a>
</h4>
<p>
                                Sometimes you need to make your web scraper appear to be making HTTP requests as a browser in order to get the web server to return the same data that you see in your browser.
                            </p>
<hr/>
<h4>
<a href="/pages/advanced/?gotcha=login" target="_blank">Logins &amp; Session Data</a>
</h4>
<p>
                                Submit some data in one request, get a session cookie back from the site, and then be sure to send that cookie back on subsequent requests so you stay "logged in" between requests.
                            </p>
<hr/>
<h4>
<a href="/pages/advanced/?gotcha=csrf" target="_blank">CSRF &amp; Hidden Values</a>
</h4>
<p>
                                Some forms require hidden values to be submitted, not just the fields that have text fields. Load the login page, grab all the hidden value, then submit them with the rest of the form fields.
                            </p>
<hr/>
</div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
</div><!--#page-->
<section id="footer">
<div class="container">
<div class="row">
<div class="col-md-12 text-center text-muted">
                    Lessons and Videos © Hartley Brody 2023
                </div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script crossorigin="anonymous" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css"/>
<!-- pnotify messages -->
<script type="text/javascript">

    PNotify.prototype.options.styling = "bootstrap3";
    $(function(){

    });


    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
<!-- golbal video controls -->
<script type="text/javascript">
    $("video").hover(function() {
        $(this).prop("controls", true);
    }, function() {
        $(this).prop("controls", false);
    });

    $("video").click(function() {
        if( this.paused){
            this.play();
        }
        else {
            this.pause();
        }
    });
    </script>
<!-- insert google analytics here -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41551755-8', 'auto');
    ga('send', 'pageview');
  </script>
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '764287443701341');
  fbq('track', "PageView");</script>
<noscript><img height="1" src="https://www.facebook.com/tr?id=764287443701341&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
<!-- End Facebook Pixel Code -->
<!-- Google Code for Remarketing Tag -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 950945448;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
    </script>
<script src="//www.googleadservices.com/pagead/conversion.js" type="text/javascript">
</script>
<noscript>
<div style="display:inline;">
<img alt="" height="1" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0" style="border-style:none;" width="1"/>
</div>
</noscript>
<!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-950945448"></script>
<script>
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());

   gtag('config', 'AW-950945448');
  </script>
</html>

In [81]:
all_h4 = soup.find_all("h4")

In [82]:
all_h4

[<h4>
 <a href="/pages/advanced/?gotcha=headers" target="_blank">Spoofing Headers</a>
 </h4>,
 <h4>
 <a href="/pages/advanced/?gotcha=login" target="_blank">Logins &amp; Session Data</a>
 </h4>,
 <h4>
 <a href="/pages/advanced/?gotcha=csrf" target="_blank">CSRF &amp; Hidden Values</a>
 </h4>]

In [93]:
Real_World_Challenges=[]
for h in all_h4:
    Heading=h.find_all("a")[0].get_text(strip=True)
    para=h.findAllNext("p")[0].get_text(strip=True)
    Real_World_Challenges.append([Heading,para])

In [94]:
Real_World_Challenges

[['Spoofing Headers',
  'Sometimes you need to make your web scraper appear to be making HTTP requests as a browser in order to get the web server to return the same data that you see in your browser.'],
 ['Logins & Session Data',
  'Submit some data in one request, get a session cookie back from the site, and then be sure to send that cookie back on subsequent requests so you stay "logged in" between requests.'],
 ['CSRF & Hidden Values',
  'Some forms require hidden values to be submitted, not just the fields that have text fields. Load the login page, grab all the hidden value, then submit them with the rest of the form fields.']]

In [96]:
df=pd.DataFrame(Real_World_Challenges,columns=["Heading","Para"])
df

                 Heading                                               Para
0       Spoofing Headers  Sometimes you need to make your web scraper ap...
1  Logins & Session Data  Submit some data in one request, get a session...
2   CSRF & Hidden Values  Some forms require hidden values to be submitt...