In [3]:
import requests as r
import pandas as pd

In [4]:
URL="https://stephen-king-api.onrender.com/api/books"

In [5]:
respones=r.get(URL)
respones

In [6]:
json_Data=respones.json()
json_Data

{'data': [{'id': 1,
   'Year': 1974,
   'Title': 'Carrie',
   'handle': 'carrie',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-08695-0',
   'Pages': 199,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:47.848Z',
   'villains': [{'name': 'Tina Blake',
     'url': 'https://stephen-king-api.onrender.com/api/villain/4'},
    {'name': 'Cindi',
     'url': 'https://stephen-king-api.onrender.com/api/villain/14'},
    {'name': 'Myra Crewes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/16'},
    {'name': 'Billy deLois',
     'url': 'https://stephen-king-api.onrender.com/api/villain/25'},
    {'name': 'Kenny Garson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/38'},
    {'name': 'Mary Lila Grace',
     'url': 'https://stephen-king-api.onrender.com/api/villain/44'},
    {'name': 'Christine Hargensen',
     'url': 'https://stephen-king-api.onrender.com/api/villain/49'},
    {'name': 'Vic Mooney',
     'url': 'https://stephen-king-api.onrender.com/api/villain/75'},
    {'name': 'The Mortimer Snerds',
     'url': 'https://stephen-king-api.onrender.com/api/villain/77'},
    {'name': 'Billy Nolan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/80'},
    {'name': 'Elenor Richmond',
     'url': 'https://stephen-king-api.onrender.com/api/villain/90'},
    {'name': 'Rachel Spies',
     'url': 'https://stephen-king-api.onrender.com/api/villain/94'},
    {'name': 'Jackie Talbot',
     'url': 'https://stephen-king-api.onrender.com/api/villain/99'},
    {'name': 'Donna and Mary Lila Grace Thibodeau',
     'url': 'https://stephen-king-api.onrender.com/api/villain/102'},
    {'name': 'Jessica Upshaw',
     'url': 'https://stephen-king-api.onrender.com/api/villain/108'},
    {'name': 'Norma Watson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/109'},
    {'name': 'Margaret White',
     'url': 'https://stephen-king-api.onrender.com/api/villain/113'}]},
  {'id': 2,
   'Year': 1975,
   'Title': "Salem's Lot",
   'handle': 'salem-s-lot',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-00751-1',
   'Pages': 439,
   'Notes': ['Nominee, World Fantasy Award, 1976[2]'],
   'created_at': '2023-11-13T23:48:48.098Z',
   'villains': [{'name': 'Kurt Barlow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/2'},
    {'name': 'Richard Straker',
     'url': 'https://stephen-king-api.onrender.com/api/villain/98'}]},
  {'id': 3,
   'Year': 1977,
   'Title': 'The Shining',
   'handle': 'the-shining',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12167-5',
   'Pages': 447,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1978[2]'],
   'created_at': '2023-11-13T23:48:48.219Z',
   'villains': [{'name': 'Horace M. Derwent',
     'url': 'https://stephen-king-api.onrender.com/api/villain/26'},
    {'name': 'Delbert Grady',
     'url': 'https://stephen-king-api.onrender.com/api/villain/45'},
    {'name': 'Jack Torrance',
     'url': 'https://stephen-king-api.onrender.com/api/villain/106'}]},
  {'id': 4,
   'Year': 1977,
   'Title': 'Rage',
   'handle': 'rage',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-07645-8',
   'Pages': 211,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.339Z',
   'villains': []},
  {'id': 5,
   'Year': 1978,
   'Title': 'The Stand',
   'handle': 'the-stand',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12168-2',
   'Pages': 823,
   'Notes': ['Nominee, World Fantasy Award, 1979',
    'Runner-up (15th place), Locus Award, 1979[2]'],
   'created_at': '2023-11-13T23:48:48.477Z',
   'villains': [{'name': 'Donald Merwin Elbert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/34'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Lloyd Henreid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/51'},
    {'name': 'The Kid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/62'},
    {'name': 'Harold Lauder',
     'url': 'https://stephen-king-api.onrender.com/api/villain/64'},
    {'name': 'Rat Man',
     'url': 'https://stephen-king-api.onrender.com/api/villain/87'}]},
  {'id': 6,
   'Year': 1979,
   'Title': 'The Long Walk',
   'handle': 'the-long-walk',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-08754-6',
   'Pages': 384,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.608Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'The Major',
     'url': 'https://stephen-king-api.onrender.com/api/villain/70'}]},
  {'id': 7,
   'Year': 1979,
   'Title': 'The Dead Zone',
   'handle': 'the-dead-zone',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-26077-5',
   'Pages': 428,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Fantasy Novel, 1980[2]'],
   'created_at': '2023-11-13T23:48:48.753Z',
   'villains': [{'name': 'Frank Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/29'},
    {'name': 'Henrietta Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/30'},
    {'name': 'Malcolm Janus',
     'url': 'https://stephen-king-api.onrender.com/api/villain/71'},
    {'name': 'Sonny Elliman',
     'url': 'https://stephen-king-api.onrender.com/api/villain/93'},
    {'name': 'Greg Stillson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/97'},
    {'name': "The Devil's Dozen",
     'url': 'https://stephen-king-api.onrender.com/api/villain/100'}]},
  {'id': 8,
   'Year': 1980,
   'Title': 'Firestarter',
   'handle': 'firestarter',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-31541-3',
   'Pages': 426,
   'Notes': ['Nominee, British Fantasy Award’s August Derleth Award, 1981',
    'Runner-up (8th place), Locus Award for Best Science Fiction Novel, 1981[2]'],
   'created_at': '2023-11-13T23:48:48.876Z',
   'villains': [{'name': 'James Hollister',
     'url': 'https://stephen-king-api.onrender.com/api/villain/54'},
    {'name': 'Charlie McGee',
     'url': 'https://stephen-king-api.onrender.com/api/villain/73'},
    {'name': 'John Rainbird',
     'url': 'https://stephen-king-api.onrender.com/api/villain/86'}]},
  {'id': 9,
   'Year': 1981,
   'Title': 'Roadwork',
   'handle': 'roadwork',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-09668-5',
   'Pages': 274,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.005Z',
   'villains': []},
  {'id': 10,
   'Year': 1981,
   'Title': 'Cujo',
   'handle': 'cujo',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-45193-7',
   'Pages': 319,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1982',
    'Runner-up (21st place), Locus Award for Best Fantasy Novel, 1982[2]'],
   'created_at': '2023-11-13T23:48:49.131Z',
   'villains': [{'name': 'Cujo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/19'}]},
  {'id': 11,
   'Year': 1982,
   'Title': 'The Running Man',
   'handle': 'the-running-man',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-11508-9',
   'Pages': 219,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.252Z',
   'villains': [{'name': 'The Gladiators',
     'url': 'https://stephen-king-api.onrender.com/api/villain/42'},
    {'name': 'Damon Killian',
     'url': 'https://stephen-king-api.onrender.com/api/villain/63'}]},
  {'id': 12,
   'Year': 1982,
   'Title': 'The Dark Tower: The Gunslinger',
   'handle': 'the-dark-tower-the-gunslinger',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-50-9',
   'Pages': 224,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:49.374Z',
   'villains': [{'name': 'Marten Broadcloak',
     'url': 'https://stephen-king-api.onrender.com/api/villain/10'},
    {'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Sylvia Pittston',
     'url': 'https://stephen-king-api.onrender.com/api/villain/84'}]},
  {'id': 13,
   'Year': 1983,
   'Title': 'Christine',
   'handle': 'christine',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-22026-7',
   'Pages': 526,
   'Notes': ['Runner-up (6th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.505Z',
   'villains': [{'name': 'Christine (car)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/11'},
    {'name': 'Arnie Cunningham',
     'url': 'https://stephen-king-api.onrender.com/api/villain/20'}]},
  {'id': 14,
   'Year': 1983,
   'Title': 'Pet Sematary',
   'handle': 'pet-sematary',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-18244-7',
   'Pages': 374,
   'Notes': ['Nominee, World Fantasy Award, 1984',
    'Runner-up (7th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.637Z',
   'villains': [{'name': 'Winston Church',
     'url': 'https://stephen-king-api.onrender.com/api/villain/13'},
    {'name': 'Gage Creed',
     'url': 'https://stephen-king-api.onrender.com/api/villain/15'},
    {'name': 'Victor Pascow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/83'},
    {'name': 'Wendigo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/110'}]},
  {'id': 15,
   'Year': 1983,
   'Title': 'Cycle of the Werewolf',
   'handle': 'cycle-of-the-werewolf',
   'Publisher': 'Land of Enchantment',
   'ISBN': '978-0-960-38282-8',
   'Pages': 127,
   'Notes': ['Illustrated by Bernie Wrightson'],
   'created_at': '2023-11-13T23:48:49.757Z',
   'villains': [{'name': 'Lester Lowe',
     'url': 'https://stephen-king-api.onrender.com/api/villain/68'}]},
  {'id': 16,
   'Year': 1984,
   'Title': 'The Talisman',
   'handle': 'the-talisman',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-69199-9',
   'Pages': 646,
   'Notes': ['Written with Peter Straub',
    'Nominee, World Fantasy Award, 1985',
    'Runner-up (4th place), Locus Award for Best Fantasy Novel, 1985[2]'],
   'created_at': '2023-11-13T23:48:49.872Z',
   'villains': []},
  {'id': 17,
   'Year': 1984,
   'Title': 'The Eyes of the Dragon',
   'handle': 'the-eyes-of-the-dragon',
   'Publisher': 'Philtrum Press (1984)Viking (1987)',
   'ISBN': '978-0-670-81458-9',
   'Pages': 326,
   'Notes': ['First published as a limited edition in 1984, then for the mass market in 1987'],
   'created_at': '2023-11-13T23:48:49.988Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 18,
   'Year': 1984,
   'Title': 'Thinner',
   'handle': 'thinner',
   'Publisher': 'NAL',
   'ISBN': '978-0-453-00468-8',
   'Pages': 309,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:50.102Z',
   'villains': []},
  {'id': 19,
   'Year': 1986,
   'Title': 'It',
   'handle': 'it',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81302-5',
   'Pages': 1138,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1987',
    'Nominee, World Fantasy Award, 1987',
    'Runner-up (3rd place), Locus Award for Best Fantasy Novel, 1987[2]'],
   'created_at': '2023-11-13T23:48:50.223Z',
   'villains': [{'name': 'Henry Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/7'},
    {'name': 'Butch Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/8'},
    {'name': 'Greta Bowie',
     'url': 'https://stephen-king-api.onrender.com/api/villain/9'},
    {'name': 'Victor Criss',
     'url': 'https://stephen-king-api.onrender.com/api/villain/18'},
    {'name': 'Marcia Fadden',
     'url': 'https://stephen-king-api.onrender.com/api/villain/35'},
    {'name': 'John Garton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/39'},
    {'name': 'Peter Gordon',
     'url': 'https://stephen-king-api.onrender.com/api/villain/43'},
    {'name': 'Patrick Hockstetter',
     'url': 'https://stephen-king-api.onrender.com/api/villain/53'},
    {'name': 'Belch Huggins',
     'url': 'https://stephen-king-api.onrender.com/api/villain/55'},
    {'name': 'It (Creature)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/57'},
    {'name': 'Richard P. Macklin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/69'},
    {'name': 'Alvin Marsh',
     'url': 'https://stephen-king-api.onrender.com/api/villain/72'},
    {'name': 'Sally Mueller',
     'url': 'https://stephen-king-api.onrender.com/api/villain/79'},
    {'name': 'Tom Rogan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/91'},
    {'name': 'Christopher Unwin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/107'}]},
  {'id': 20,
   'Year': 1987,
   'Title': 'The Dark Tower II: The Drawing of the Three',
   'handle': 'the-dark-tower-ii-the-drawing-of-the-three',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-90-5',
   'Pages': 400,
   'Notes': ['Runner-up (16th place), Locus Award for Best Fantasy Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.339Z',
   'villains': [{'name': 'Jack Mort',
     'url': 'https://stephen-king-api.onrender.com/api/villain/76'}]},
  {'id': 21,
   'Year': 1987,
   'Title': 'Misery',
   'handle': 'misery',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81364-3',
   'Pages': 310,
   'Notes': ['Winner, Bram Stoker Award, 1988',
    'Nominee, World Fantasy Award, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.459Z',
   'villains': [{'name': 'Annie Wilkes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/114'}]},
  {'id': 22,
   'Year': 1987,
   'Title': 'The Tommyknockers',
   'handle': 'the-tommyknockers',
   'Publisher': 'Putnam',
   'ISBN': '978-0-399-13314-5',
   'Pages': 558,
   'Notes': ['Runner-up (16th place), Locus Award for Best Science Fiction Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.579Z',
   'villains': [{'name': 'Tommyknockers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/104'}]},
  {'id': 23,
   'Year': 1989,
   'Title': 'The Dark Half',
   'handle': 'the-dark-half',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-82982-8',
   'Pages': 431,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Horror Novel, 1990[2]'],
   'created_at': '2023-11-13T23:48:50.696Z',
   'villains': [{'name': 'George Stark',
     'url': 'https://stephen-king-api.onrender.com/api/villain/96'}]},
  {'id': 24,
   'Year': 1990,
   'Title': 'The Stand Uncut',
   'handle': 'the-stand-uncut',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-19957-5',
   'Pages': 1152,
   'Notes': ['The Complete & Uncut Edition',
    "Runner-up (2nd place), Locus Award's Best Horror/Dark Fantasy Novel, 1991[2]"],
   'created_at': '2023-11-13T23:48:50.809Z',
   'villains': []},
  {'id': 25,
   'Year': 1991,
   'Title': 'The Dark Tower III: The Waste Lands',
   'handle': 'the-dark-tower-iii-the-waste-lands',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-17-2',
   'Pages': 512,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:50.926Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 26,
   'Year': 1991,
   'Title': 'Needful Things',
   'handle': 'needful-things',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-83953-7',
   'Pages': 690,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (13th place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:51.044Z',
   'villains': [{'name': 'Leland Gaunt',
     'url': 'https://stephen-king-api.onrender.com/api/villain/40'}]},
  {'id': 27,
   'Year': 1992,
   'Title': "Gerald's Game",
   'handle': 'gerald-s-game',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84650-4',
   'Pages': 352,
   'Notes': [],
   'created_at': '2023-11-13T23:48:51.165Z',
   'villains': [{'name': 'Gerald Burlingame',
     'url': 'https://stephen-king-api.onrender.com/api/villain/41'},
    {'name': 'Raymond Andrew Joubert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/61'},
    {'name': 'Tom Mahout',
     'url': 'https://stephen-king-api.onrender.com/api/villain/103'}]},
  {'id': 28,
   'Year': 1992,
   'Title': 'Dolores Claiborne',
   'handle': 'dolores-claiborne',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84452-4',
   'Pages': 305,
   'Notes': ['Runner-up (14th place), Locus Award for Best Horror/Dark Fantasy Novel, 1993[2]'],
   'created_at': '2023-11-13T23:48:51.295Z',
   'villains': [{'name': 'Joe St. George',
     'url': 'https://stephen-king-api.onrender.com/api/villain/95'}]},
  {'id': 29,
   'Year': 1994,
   'Title': 'Insomnia',
   'handle': 'insomnia',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85503-2',
   'Pages': 787,
   'Notes': ['Nominee, Bram Stoker Award, 1995',
    'Runner-up (3rd place), Locus Award for Best Fantasy/Horror Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.415Z',
   'villains': [{'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 30,
   'Year': 1995,
   'Title': 'Rose Madder',
   'handle': 'rose-madder',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85869-9',
   'Pages': 420,
   'Notes': ['Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.533Z',
   'villains': [{'name': 'Norman Daniels',
     'url': 'https://stephen-king-api.onrender.com/api/villain/22'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 31,
   'Year': 1996,
   'Title': 'The Green Mile',
   'handle': 'the-green-mile',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-19049-9978-0-451-19052-9978-0-451-19054-3978-0-451-19055-0978-0-451-19056-7978-0-451-19057-4',
   'Pages': 400,
   'Notes': ['Winner, Bram Stoker Award, 1997',
    'Runner-up (8th place), Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.660Z',
   'villains': [{'name': 'Percy Wetmore',
     'url': 'https://stephen-king-api.onrender.com/api/villain/111'},
    {'name': 'William Wharton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/112'}]},
  {'id': 32,
   'Year': 1996,
   'Title': 'Desperation',
   'handle': 'desperation',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-86836-0',
   'Pages': 704,
   'Notes': ['Twin novel of The Regulators',
    'Winner, Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.784Z',
   'villains': []},
  {'id': 33,
   'Year': 1996,
   'Title': 'The Regulators',
   'handle': 'the-regulators',
   'Publisher': 'Dutton',
   'ISBN': '978-0-525-94190-3',
   'Pages': 480,
   'Notes': ['Published under pseudonym Richard Bachman',
    'Twin novel of Desperation'],
   'created_at': '2023-11-13T23:48:51.900Z',
   'villains': []},
  {'id': 34,
   'Year': 1997,
   'Title': 'The Dark Tower IV: Wizard and Glass',
   'handle': 'the-dark-tower-iv-wizard-and-glass',
   'Publisher': 'Grant',
   'ISBN': '978-1-880418-38-3',
   'Pages': 787,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1998',
    'Runner-up (6th place), Locus Award for Best Art Book, 1998[2]'],
   'created_at': '2023-11-13T23:48:52.019Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Cordelia Delgado',
     'url': 'https://stephen-king-api.onrender.com/api/villain/24'},
    {'name': 'Rhea Dubativo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/32'},

In [7]:
df=pd.json_normalize(json_Data["data"])
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
58,59,2018,The Outsider,the-outsider,Scribner,978-1-50118-098-9,576,"[First novel in the Holly Gibney Series, Runne...",2023-11-13T23:48:55.165Z,"[{'name': 'The Outsider (Creature)', 'url': 'h..."
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]

In [8]:
df.columns

Index(['id', 'Year', 'Title', 'handle', 'Publisher', 'ISBN', 'Pages', 'Notes',
       'created_at', 'villains'],
      dtype='object')

In [9]:
df[["id","Title","Year","ISBN"]]

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

# Home Work Problem

# Q1

In [10]:
url="https://dogapi.dog/api/v2/breeds"

In [11]:
respones=r.get(url)
respones

In [12]:
json_Data=respones.json()
json_Data

{'data': [{'id': '036feed0-da8a-42c9-ab9a-57449b530b13',
   'type': 'breed',
   'attributes': {'name': 'Affenpinscher',
    'description': 'The Affenpinscher is a small and playful breed of dog that was originally bred in Germany for hunting small game. They are intelligent, energetic, and affectionate, and make excellent companion dogs.',
    'life': {'max': 16, 'min': 14},
    'male_weight': {'max': 5, 'min': 3},
    'female_weight': {'max': 5, 'min': 3},
    'hypoallergenic': True},
   'relationships': {'group': {'data': {'id': 'f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c',
      'type': 'group'}}}},
  {'id': 'dd9362cc-52e0-462d-b856-fccdcf24b140',
   'type': 'breed',
   'attributes': {'name': 'Afghan Hound',
    'description': 'The Afghan Hound is a large and elegant breed of dog that was originally bred in Afghanistan for hunting small game. They are intelligent, independent, and athletic, and make excellent companion dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 27, 'min': 23},
    'female_weight': {'max': 25, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': '1460844f-841c-4de8-b788-271aa4d63224',
   'type': 'breed',
   'attributes': {'name': 'Airedale Terrier',
    'description': 'The Airedale Terrier is a large and powerful breed of dog that was originally bred in England for hunting small game. They are intelligent, energetic, and determined, and make excellent hunting dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 23, 'min': 20},
    'female_weight': {'max': 20, 'min': 18},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '1bbf373b-1937-4e73-9863-45385daa4979',
      'type': 'group'}}}},
  {'id': 'e7e99424-d514-4b56-9f0c-05736f6dd22d',
   'type': 'breed',
   'attributes': {'name': 'Akita',
    'description': 'The Akita is a large, muscular dog breed that originated in Japan. They are known for their loyalty and courage.',
    'life': {'max': 12, 'min': 10},
    'male_weight': {'max': 60, 'min': 35},
    'female_weight': {'max': 50, 'min': 35},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '56081cf0-fdf2-4114-9bf7-23a3f5b6af91',
      'type': 'group'}}}},
  {'id': '667c7359-a739-4f2b-abb4-98867671e375',
   'type': 'breed',
   'attributes': {'name': 'Alaskan Klee Kai',
    'description': 'The Alaskan Klee Kai is a small to medium-sized breed of dog that was developed in Alaska in the 1970s. It is an active and intelligent breed that is loyal and friendly. The Alaskan Klee Kai stands between 13-17 inches at the shoulder and has a double-coat that can come in various colors and patterns.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 7, 'min': 6},
    'female_weight': {'max': 7, 'min': 6},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '5328d59b-b4e4-48e9-98ec-0545c66c4385',
   'type': 'breed',
   'attributes': {'name': 'Alaskan Malamute',
    'description': 'The Alaskan Malamute is a large and powerful sled dog from Alaska. They are strong and hardworking, yet friendly and loyal. Alaskan Malamutes have a thick, double coat that can be any color. They are active and require plenty of exercise and mental stimulation to stay healthy and happy.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 39, 'min': 34},
    'female_weight': {'max': 34, 'min': 25},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '56081cf0-fdf2-4114-9bf7-23a3f5b6af91',
      'type': 'group'}}}},
  {'id': 'f72528b5-a5d7-4a17-b709-aba2db722307',
   'type': 'breed',
   'attributes': {'name': 'American Bulldog',
    'description': 'The American Bulldog is a large and powerful breed of dog that was originally bred in the United States for working on farms. They are intelligent, loyal, and protective, and make excellent guard dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 50, 'min': 25},
    'female_weight': {'max': 45, 'min': 25},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '4524645f-dda7-4031-9272-dee29f5f91ea',
   'type': 'breed',
   'attributes': {'name': 'American English Coonhound',
    'description': 'The American English Coonhound is a large and athletic breed of dog that was originally bred in the United States for hunting raccoons. They are intelligent, energetic, and determined, and make excellent hunting dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 30, 'min': 20},
    'female_weight': {'max': 30, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': 'e1c0664d-aa61-4c85-970d-6c86ba197bee',
   'type': 'breed',
   'attributes': {'name': 'American Eskimo Dog',
    'description': 'The American Eskimo Dog is a small to medium-sized breed with a thick, fluffy coat that comes in white, cream, or biscuit colors. It is known for its intelligence and its ability to learn a wide variety of tricks.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 20, 'min': 9},
    'female_weight': {'max': 20, 'min': 9},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '7f6ea988-366a-4e20-b4ba-4d04274fea61',
      'type': 'group'}}}},
  {'id': '8355b9c9-3724-477d-858a-c1c1c0f1743f',
   'type': 'breed',
   'attributes': {'name': 'American Foxhound',
    'description': 'The American Foxhound is a large and athletic breed of dog that was originally bred in the United States for hunting foxes. They are intelligent, energetic, and determined, and make excellent hunting dogs.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 34, 'min': 20},
    'female_weight': {'max': 34, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': 'bba868bb-71ce-4e66-9970-861fb5af642f',
   'type': 'breed',
   'attributes': {'name': 'American Hairless Terrier',
    'description': 'The American Hairless Terrier is a small to medium-sized breed of terrier that originated in the United States. It is the hairless variety of the Rat Terrier, and was developed by breeding selectively for the gene that causes the hairlessness. The Hairless variety is considered to have a more mellow and laid-back temperament than its coated counterpart, and is an active and intelligent breed that loves to please and stay busy. The breed stands between 12-16 inches at the shoulder and comes in a variety of colors.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 7, 'min': 6},
    'female_weight': {'max': 7, 'min': 6},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '1bbf373b-1937-4e73-9863-45385daa4979',
      'type': 'group'}}}},
  {'id': '7b1fef86-3fa7-4dd0-92d2-8d7a5524e844',
   'type': 'breed',
   'attributes': {'name': 'American Leopard Hound',
    'description': 'The American Leopard Hound is a large, athletic dog breed that was originally bred for hunting. They are known for their spotted coats and keen sense of smell.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 40, 'min': 30},
    'female_weight': {'max': 35, 'min': 25},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '30a056b8-2bbe-4aa9-b874-c511eb2ca775',
   'type': 'breed',
   'attributes': {'name': 'American Staffordshire Terrier',
    'description': 'The American Staffordshire Terrier is a medium-sized breed of dog that was originally bred for dog fighting. They are intelligent, loyal, and protective, and make excellent family pets.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 40, 'min': 18},
    'female_weight': {'max': 40, 'min': 18},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '1bbf373b-1937-4e73-9863-45385daa4979',
      'type': 'group'}}}},
  {'id': '46a95f0b-8b66-400d-8323-07084c36fcae',
   'type': 'breed',
   'attributes': {'name': 'American Water Spaniel',
    'description': 'The American Water Spaniel is a medium-sized breed of dog that was originally bred in the United States for hunting waterfowl. They are intelligent, energetic, and eager to please, and make excellent hunting dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 20, 'min': 15},
    'female_weight': {'max': 20, 'min': 15},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'ab110192-e41b-43ff-a630-f7aee156b33a',
      'type': 'group'}}}},
  {'id': 'c94e50a5-f733-4b15-8b11-54598c949b6f',
   'type': 'breed',
   'attributes': {'name': 'Anatolian Shepherd Dog',
    'description': 'The Anatolian Shepherd Dog is a large breed of flock guardian dog that originated in Turkey. It is a powerful and athletic breed, with a long, coarse coat. Its head is large and round, with small, erect ears. Its legs are strong and muscular, and its tail is usually docked. The Anatolian Shepherd Dog is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs plenty of exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 70, 'min': 50},
    'female_weight': {'max': 70, 'min': 50},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '56081cf0-fdf2-4114-9bf7-23a3f5b6af91',
      'type': 'group'}}}},
  {'id': 'b56e4273-9ec0-4274-831d-b238225f8fb6',
   'type': 'breed',
   'attributes': {'name': 'Appenzeller Sennenhund',
    'description': 'The Appenzeller Sennenhund is a large breed of mountain dog that originated in Switzerland. It is a powerful and athletic breed, with a thick, double coat. Its head is large and round, with small, erect ears. Its legs are strong and muscular, and its tail is usually docked. The Appenzeller Sennenhund is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs plenty of exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 45, 'min': 30},
    'female_weight': {'max': 45, 'min': 30},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '0543cf54-a255-402e-84e5-f440cc2a67cc',
   'type': 'breed',
   'attributes': {'name': 'Australian Cattle Dog',
    'description': 'The Australian Cattle Dog is a medium-sized breed of dog that was originally bred in Australia for herding and guarding livestock. They are intelligent, energetic, and hardworking, and make excellent working dogs.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 20, 'min': 16},
    'female_weight': {'max': 20, 'min': 16},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'b8e4e89d-057f-432a-9e58-0b85b29b693c',
      'type': 'group'}}}},
  {'id': '2adf5a19-028d-4993-8044-4571008b6d49',
   'type': 'breed',
   'attributes': {'name': 'Australian Kelpie',
    'description': 'The Australian Kelpie is a lively and intelligent herding dog from Australia. They are active, friendly, and loyal, and make great family pets. Australian Kelpies have a thick, double coat that can be any color. They are easy to train and require plenty of exercise and mental stimulation to stay healthy and happy.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 20, 'min': 16},
    'female_weight': {'max': 20, 'min': 16},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '03269b7d-c5d6-4a8f-83d1-7a6180d40127',
   'type': 'breed',
   'attributes': {'name': 'Australian Shepherd',
    'description': 'The Australian Shepherd is a medium-sized breed with a medium-length, double coat. They have a wedge-shaped head and a muscular body, with a straight, medium-length tail. The Australian Shepherd is an intelligent working dog that is eager to please and loves to be around its family. They are known for their loyalty and are often used in agility, obedience, and herding events.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 30, 'min': 20},
    'female_weight': {'max': 25, 'min': 17},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'b8e4e89d-057f-432a-9e58-0b85b29b693c',
      'type': 'group'}}}},
  {'id': '6e04f700-c307-4dd5-8d2f-fd346d949cd6',
   'type': 'breed',
   'attributes': {'name': 'Australian Stumpy Tail Cattle Dog',
    'description': 'The Australian Stumpy Tail Cattle Dog is a medium-sized herding dog breed with a distinctive stumpy tail and a smooth, dense coat that can be blue, red, or fawn in color. They are intelligent, energetic, and obedient, and were originally bred to help farmers drive their cattle over long distances.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 20, 'min': 15},
    'female_weight': {'max': 20, 'min': 15},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '4b3278eb-612a-4e87-b2ab-73174d039514',
   'type': 'breed',
   'attributes': {'name': 'Australian Terrier',
    'description': 'The Australian Terrier is a small breed of terrier that originated in Australia. It is a compact and lively breed, with a short, wiry coat. Its head is large and round, with small, erect ears. Its legs are short and strong, and its tail is usually docked. The Australian Terrier is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs regular exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family.',
    'life': {'max': 16, 'min': 14},
    'male_weight': {'max': 6, 'min': 4},
    'female_weight': {'max': 6, 'min': 4},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '1bbf373b-1937-4e73-9863-45385daa4979',
      'type': 'group'}}}},
  {'id': '1ceaee48-1374-4b11-9c66-173cce6f5da5',
   'type': 'breed',
   'attributes': {'name': 'Azawakh',
    'description': 'The Azawakh is a small and slender breed of dog that was originally bred in Africa for hunting and guarding. They are intelligent, alert, and athletic, and make excellent companion dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 30, 'min': 25},
    'female_weight': {'max': 30, 'min': 25},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': 'cb71135b-596c-4943-892a-d0757da0297e',
   'type': 'breed',
   'attributes': {'name': 'Barbado da Terceira',
    'description': 'The Barbado da Terceira is a large, working breed of dog that originated in the Azores. It is a strong and powerful breed, with a short, wiry coat. Its head is large and round, with small, erect ears. Its legs are strong and muscular, and its tail is usually docked. The Barbado da Terceira is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs plenty of exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 20, 'min': 15},
    'female_weight': {'max': 20, 'min': 15},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '4a230092-a25e-4efe-8240-a6693b5405f4',
   'type': 'breed',
   'attributes': {'name': 'Barbet',
    'description': 'The Barbet is an ancient breed of French water dog. They are active, friendly, and highly intelligent, and make great family pets. Barbets have a unique, woolly coat that is curly or wavy and can be any color. They have webbed feet, and are very good swimmers. Barbets bond closely with their family, and do best in homes where they get plenty of attention and exercise.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 30, 'min': 20},
    'female_weight': {'max': 30, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'ab110192-e41b-43ff-a630-f7aee156b33a',
      'type': 'group'}}}},
  {'id': 'edf3d596-e83b-4ba1-972b-d1144a39cf3c',
   'type': 'breed',
   'attributes': {'name': 'Basenji',
    'description': 'The Basenji is a small and agile breed of dog that was originally bred in Africa for hunting small game. They are intelligent, independent, and alert, and make excellent companion dogs.',
    'life': {'max': 16, 'min': 14},
    'male_weight': {'max': 10, 'min': 9},
    'female_weight': {'max': 10, 'min': 9},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': 'c052b615-9502-407f-b46a-845d246d9f22',
   'type': 'breed',
   'attributes': {'name': 'Basset Fauve de Bretagne',
    'description': 'The Basset Fauve de Bretagne is a small and playful breed of dog that was originally bred in France for hunting small game. They are intelligent, affectionate, and loyal, and make excellent companion dogs.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 25, 'min': 20},
    'female_weight': {'max': 25, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '3e4912ab-bf3c-40cd-8eb9-be1e5999179b',
   'type': 'breed',
   'attributes': {'name': 'Basset Hound',
    'description': 'The Basset Hound is a small and playful breed of dog that was originally bred in France for hunting small game. They are intelligent, affectionate, and loyal, and make excellent companion dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 29, 'min': 20},
    'female_weight': {'max': 29, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': '406e8454-d350-4187-9788-6d857ee52e06',
   'type': 'breed',
   'attributes': {'name': 'Bavarian Mountain Scent Houn',
    'description': 'The Bavarian Mountain Scent Hound is a medium-sized breed of dog that was originally bred in Germany for hunting small game. They are intelligent, energetic, and determined, and make excellent hunting dogs.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 30, 'min': 20},
    'female_weight': {'max': 30, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': 'd8621d92-6558-451c-8631-a32e767026a0',
   'type': 'breed',
   'attributes': {'name': 'Beagle',
    'description': 'The Beagle is a small to medium-sized dog breed that was originally bred for hunting. They are known for their cheerful dispositions and keen sense of smell.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 11, 'min': 9},
    'female_weight': {'max': 11, 'min': 9},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': '62c29679-0420-4de6-ab88-2b3e99c22317',
   'type': 'breed',
   'attributes': {'name': 'Bearded Collie',

In [13]:
df=pd.json_normalize(json_Data["data"])
df

,id,type,attributes.name,attributes.description,attributes.life.max,attributes.life.min,attributes.male_weight.max,attributes.male_weight.min,attributes.female_weight.max,attributes.female_weight.min,attributes.hypoallergenic,relationships.group.data.id,relationships.group.data.type
0,036feed0-da8a-42c9-ab9a-57449b530b13,breed,Affenpinscher,The Affenpinscher is a small and playful breed...,16,14,5,3,5,3,True,f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c,group
1,dd9362cc-52e0-462d-b856-fccdcf24b140,breed,Afghan Hound,The Afghan Hound is a large and elegant breed ...,14,12,27,23,25,20,False,be0147df-7755-4228-b132-2518c0c6d10d,group
2,1460844f-841c-4de8-b788-271aa4d63224,breed,Airedale Terrier,The Airedale Terrier is a large and powerful b...,14,12,23,20,20,18,False,1bbf373b-1937-4e73-9863-45385daa4979,group
3,e7e99424-d514-4b56-9f0c-05736f6dd22d,breed,Akita,"The Akita is a large, muscular dog breed that ...",12,10,60,35,50,35,False,56081cf0-fdf2-4114-9bf7-23a3f5b6af91,group
4,667c7359-a739-4f2b-abb4-98867671e375,breed,Alaskan Klee Kai,The Alaskan Klee Kai is a small to medium-size...,15,12,7,6,7,6,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,095a1856-6506-478d-a7a8-206847d5e702,breed,Wirehaired Vizsla,The Wirehaired Vizsla is a medium-sized breed ...,15,12,30,25,30,25,False,ab110192-e41b-43ff-a630-f7aee156b33a,group
279,c6b12b96-9f53-445b-8f3e-bf867c761dca,breed,Working Kelpie,The Working Kelpie is a medium-sized breed of ...,15,12,20,16,20,16,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
280,43cdadb4-851b-4a3a-99c1-5f63d08d97f8,breed,Xoloitzcuintli,"The Xoloitzcuintli, also known as the Mexican ...",15,12,15,10,15,10,True,7f6ea988-366a-4e20-b4ba-4d04274fea61,group
281,052684bc-a484-4f29-b953-d5ccf6a3d5e6,breed,Yakutian Laika,The Yakutian Laika is a medium-sized breed of ...,15,12,30,18,30,18,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
282,ce40589c-295a-4259-9e83-711854db8129,breed,Yorkshire Terrier,"The Yorkshire Terrier is a small, intelligent ...",15,12,3,2,3,2,False,f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c,group

In [14]:
df.columns

Index(['id', 'type', 'attributes.name', 'attributes.description',
       'attributes.life.max', 'attributes.life.min',
       'attributes.male_weight.max', 'attributes.male_weight.min',
       'attributes.female_weight.max', 'attributes.female_weight.min',
       'attributes.hypoallergenic', 'relationships.group.data.id',
       'relationships.group.data.type'],
      dtype='object')

In [15]:
df[["id","type","attributes.name","attributes.description"]]

,id,type,attributes.name,attributes.description
0,036feed0-da8a-42c9-ab9a-57449b530b13,breed,Affenpinscher,The Affenpinscher is a small and playful breed...
1,dd9362cc-52e0-462d-b856-fccdcf24b140,breed,Afghan Hound,The Afghan Hound is a large and elegant breed ...
2,1460844f-841c-4de8-b788-271aa4d63224,breed,Airedale Terrier,The Airedale Terrier is a large and powerful b...
3,e7e99424-d514-4b56-9f0c-05736f6dd22d,breed,Akita,"The Akita is a large, muscular dog breed that ..."
4,667c7359-a739-4f2b-abb4-98867671e375,breed,Alaskan Klee Kai,The Alaskan Klee Kai is a small to medium-size...
...,...,...,...,...
278,095a1856-6506-478d-a7a8-206847d5e702,breed,Wirehaired Vizsla,The Wirehaired Vizsla is a medium-sized breed ...
279,c6b12b96-9f53-445b-8f3e-bf867c761dca,breed,Working Kelpie,The Working Kelpie is a medium-sized breed of ...
280,43cdadb4-851b-4a3a-99c1-5f63d08d97f8,breed,Xoloitzcuintli,"The Xoloitzcuintli, also known as the Mexican ..."
281,052684bc-a484-4f29-b953-d5ccf6a3d5e6,breed,Yakutian Laika,The Yakutian Laika is a medium-sized breed of ...
282,ce40589c-295a-4259-9e83-711854db8129,breed,Yorkshire Terrier,"The Yorkshire Terrier is a small, intelligent ..."

# Q 2

In [16]:
url="https://dogapi.dog/api/v2/breeds"

In [17]:
res=r.get(url)

In [18]:
res

In [19]:
json_Data=res.json()
json_Data

{'data': [{'id': '036feed0-da8a-42c9-ab9a-57449b530b13',
   'type': 'breed',
   'attributes': {'name': 'Affenpinscher',
    'description': 'The Affenpinscher is a small and playful breed of dog that was originally bred in Germany for hunting small game. They are intelligent, energetic, and affectionate, and make excellent companion dogs.',
    'life': {'max': 16, 'min': 14},
    'male_weight': {'max': 5, 'min': 3},
    'female_weight': {'max': 5, 'min': 3},
    'hypoallergenic': True},
   'relationships': {'group': {'data': {'id': 'f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c',
      'type': 'group'}}}},
  {'id': 'dd9362cc-52e0-462d-b856-fccdcf24b140',
   'type': 'breed',
   'attributes': {'name': 'Afghan Hound',
    'description': 'The Afghan Hound is a large and elegant breed of dog that was originally bred in Afghanistan for hunting small game. They are intelligent, independent, and athletic, and make excellent companion dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 27, 'min': 23},
    'female_weight': {'max': 25, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': '1460844f-841c-4de8-b788-271aa4d63224',
   'type': 'breed',
   'attributes': {'name': 'Airedale Terrier',
    'description': 'The Airedale Terrier is a large and powerful breed of dog that was originally bred in England for hunting small game. They are intelligent, energetic, and determined, and make excellent hunting dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 23, 'min': 20},
    'female_weight': {'max': 20, 'min': 18},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '1bbf373b-1937-4e73-9863-45385daa4979',
      'type': 'group'}}}},
  {'id': 'e7e99424-d514-4b56-9f0c-05736f6dd22d',
   'type': 'breed',
   'attributes': {'name': 'Akita',
    'description': 'The Akita is a large, muscular dog breed that originated in Japan. They are known for their loyalty and courage.',
    'life': {'max': 12, 'min': 10},
    'male_weight': {'max': 60, 'min': 35},
    'female_weight': {'max': 50, 'min': 35},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '56081cf0-fdf2-4114-9bf7-23a3f5b6af91',
      'type': 'group'}}}},
  {'id': '667c7359-a739-4f2b-abb4-98867671e375',
   'type': 'breed',
   'attributes': {'name': 'Alaskan Klee Kai',
    'description': 'The Alaskan Klee Kai is a small to medium-sized breed of dog that was developed in Alaska in the 1970s. It is an active and intelligent breed that is loyal and friendly. The Alaskan Klee Kai stands between 13-17 inches at the shoulder and has a double-coat that can come in various colors and patterns.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 7, 'min': 6},
    'female_weight': {'max': 7, 'min': 6},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '5328d59b-b4e4-48e9-98ec-0545c66c4385',
   'type': 'breed',
   'attributes': {'name': 'Alaskan Malamute',
    'description': 'The Alaskan Malamute is a large and powerful sled dog from Alaska. They are strong and hardworking, yet friendly and loyal. Alaskan Malamutes have a thick, double coat that can be any color. They are active and require plenty of exercise and mental stimulation to stay healthy and happy.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 39, 'min': 34},
    'female_weight': {'max': 34, 'min': 25},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '56081cf0-fdf2-4114-9bf7-23a3f5b6af91',
      'type': 'group'}}}},
  {'id': 'f72528b5-a5d7-4a17-b709-aba2db722307',
   'type': 'breed',
   'attributes': {'name': 'American Bulldog',
    'description': 'The American Bulldog is a large and powerful breed of dog that was originally bred in the United States for working on farms. They are intelligent, loyal, and protective, and make excellent guard dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 50, 'min': 25},
    'female_weight': {'max': 45, 'min': 25},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '4524645f-dda7-4031-9272-dee29f5f91ea',
   'type': 'breed',
   'attributes': {'name': 'American English Coonhound',
    'description': 'The American English Coonhound is a large and athletic breed of dog that was originally bred in the United States for hunting raccoons. They are intelligent, energetic, and determined, and make excellent hunting dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 30, 'min': 20},
    'female_weight': {'max': 30, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': 'e1c0664d-aa61-4c85-970d-6c86ba197bee',
   'type': 'breed',
   'attributes': {'name': 'American Eskimo Dog',
    'description': 'The American Eskimo Dog is a small to medium-sized breed with a thick, fluffy coat that comes in white, cream, or biscuit colors. It is known for its intelligence and its ability to learn a wide variety of tricks.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 20, 'min': 9},
    'female_weight': {'max': 20, 'min': 9},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '7f6ea988-366a-4e20-b4ba-4d04274fea61',
      'type': 'group'}}}},
  {'id': '8355b9c9-3724-477d-858a-c1c1c0f1743f',
   'type': 'breed',
   'attributes': {'name': 'American Foxhound',
    'description': 'The American Foxhound is a large and athletic breed of dog that was originally bred in the United States for hunting foxes. They are intelligent, energetic, and determined, and make excellent hunting dogs.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 34, 'min': 20},
    'female_weight': {'max': 34, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': 'bba868bb-71ce-4e66-9970-861fb5af642f',
   'type': 'breed',
   'attributes': {'name': 'American Hairless Terrier',
    'description': 'The American Hairless Terrier is a small to medium-sized breed of terrier that originated in the United States. It is the hairless variety of the Rat Terrier, and was developed by breeding selectively for the gene that causes the hairlessness. The Hairless variety is considered to have a more mellow and laid-back temperament than its coated counterpart, and is an active and intelligent breed that loves to please and stay busy. The breed stands between 12-16 inches at the shoulder and comes in a variety of colors.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 7, 'min': 6},
    'female_weight': {'max': 7, 'min': 6},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '1bbf373b-1937-4e73-9863-45385daa4979',
      'type': 'group'}}}},
  {'id': '7b1fef86-3fa7-4dd0-92d2-8d7a5524e844',
   'type': 'breed',
   'attributes': {'name': 'American Leopard Hound',
    'description': 'The American Leopard Hound is a large, athletic dog breed that was originally bred for hunting. They are known for their spotted coats and keen sense of smell.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 40, 'min': 30},
    'female_weight': {'max': 35, 'min': 25},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '30a056b8-2bbe-4aa9-b874-c511eb2ca775',
   'type': 'breed',
   'attributes': {'name': 'American Staffordshire Terrier',
    'description': 'The American Staffordshire Terrier is a medium-sized breed of dog that was originally bred for dog fighting. They are intelligent, loyal, and protective, and make excellent family pets.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 40, 'min': 18},
    'female_weight': {'max': 40, 'min': 18},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '1bbf373b-1937-4e73-9863-45385daa4979',
      'type': 'group'}}}},
  {'id': '46a95f0b-8b66-400d-8323-07084c36fcae',
   'type': 'breed',
   'attributes': {'name': 'American Water Spaniel',
    'description': 'The American Water Spaniel is a medium-sized breed of dog that was originally bred in the United States for hunting waterfowl. They are intelligent, energetic, and eager to please, and make excellent hunting dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 20, 'min': 15},
    'female_weight': {'max': 20, 'min': 15},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'ab110192-e41b-43ff-a630-f7aee156b33a',
      'type': 'group'}}}},
  {'id': 'c94e50a5-f733-4b15-8b11-54598c949b6f',
   'type': 'breed',
   'attributes': {'name': 'Anatolian Shepherd Dog',
    'description': 'The Anatolian Shepherd Dog is a large breed of flock guardian dog that originated in Turkey. It is a powerful and athletic breed, with a long, coarse coat. Its head is large and round, with small, erect ears. Its legs are strong and muscular, and its tail is usually docked. The Anatolian Shepherd Dog is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs plenty of exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 70, 'min': 50},
    'female_weight': {'max': 70, 'min': 50},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '56081cf0-fdf2-4114-9bf7-23a3f5b6af91',
      'type': 'group'}}}},
  {'id': 'b56e4273-9ec0-4274-831d-b238225f8fb6',
   'type': 'breed',
   'attributes': {'name': 'Appenzeller Sennenhund',
    'description': 'The Appenzeller Sennenhund is a large breed of mountain dog that originated in Switzerland. It is a powerful and athletic breed, with a thick, double coat. Its head is large and round, with small, erect ears. Its legs are strong and muscular, and its tail is usually docked. The Appenzeller Sennenhund is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs plenty of exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 45, 'min': 30},
    'female_weight': {'max': 45, 'min': 30},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '0543cf54-a255-402e-84e5-f440cc2a67cc',
   'type': 'breed',
   'attributes': {'name': 'Australian Cattle Dog',
    'description': 'The Australian Cattle Dog is a medium-sized breed of dog that was originally bred in Australia for herding and guarding livestock. They are intelligent, energetic, and hardworking, and make excellent working dogs.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 20, 'min': 16},
    'female_weight': {'max': 20, 'min': 16},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'b8e4e89d-057f-432a-9e58-0b85b29b693c',
      'type': 'group'}}}},
  {'id': '2adf5a19-028d-4993-8044-4571008b6d49',
   'type': 'breed',
   'attributes': {'name': 'Australian Kelpie',
    'description': 'The Australian Kelpie is a lively and intelligent herding dog from Australia. They are active, friendly, and loyal, and make great family pets. Australian Kelpies have a thick, double coat that can be any color. They are easy to train and require plenty of exercise and mental stimulation to stay healthy and happy.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 20, 'min': 16},
    'female_weight': {'max': 20, 'min': 16},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '03269b7d-c5d6-4a8f-83d1-7a6180d40127',
   'type': 'breed',
   'attributes': {'name': 'Australian Shepherd',
    'description': 'The Australian Shepherd is a medium-sized breed with a medium-length, double coat. They have a wedge-shaped head and a muscular body, with a straight, medium-length tail. The Australian Shepherd is an intelligent working dog that is eager to please and loves to be around its family. They are known for their loyalty and are often used in agility, obedience, and herding events.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 30, 'min': 20},
    'female_weight': {'max': 25, 'min': 17},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'b8e4e89d-057f-432a-9e58-0b85b29b693c',
      'type': 'group'}}}},
  {'id': '6e04f700-c307-4dd5-8d2f-fd346d949cd6',
   'type': 'breed',
   'attributes': {'name': 'Australian Stumpy Tail Cattle Dog',
    'description': 'The Australian Stumpy Tail Cattle Dog is a medium-sized herding dog breed with a distinctive stumpy tail and a smooth, dense coat that can be blue, red, or fawn in color. They are intelligent, energetic, and obedient, and were originally bred to help farmers drive their cattle over long distances.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 20, 'min': 15},
    'female_weight': {'max': 20, 'min': 15},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '4b3278eb-612a-4e87-b2ab-73174d039514',
   'type': 'breed',
   'attributes': {'name': 'Australian Terrier',
    'description': 'The Australian Terrier is a small breed of terrier that originated in Australia. It is a compact and lively breed, with a short, wiry coat. Its head is large and round, with small, erect ears. Its legs are short and strong, and its tail is usually docked. The Australian Terrier is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs regular exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family.',
    'life': {'max': 16, 'min': 14},
    'male_weight': {'max': 6, 'min': 4},
    'female_weight': {'max': 6, 'min': 4},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '1bbf373b-1937-4e73-9863-45385daa4979',
      'type': 'group'}}}},
  {'id': '1ceaee48-1374-4b11-9c66-173cce6f5da5',
   'type': 'breed',
   'attributes': {'name': 'Azawakh',
    'description': 'The Azawakh is a small and slender breed of dog that was originally bred in Africa for hunting and guarding. They are intelligent, alert, and athletic, and make excellent companion dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 30, 'min': 25},
    'female_weight': {'max': 30, 'min': 25},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': 'cb71135b-596c-4943-892a-d0757da0297e',
   'type': 'breed',
   'attributes': {'name': 'Barbado da Terceira',
    'description': 'The Barbado da Terceira is a large, working breed of dog that originated in the Azores. It is a strong and powerful breed, with a short, wiry coat. Its head is large and round, with small, erect ears. Its legs are strong and muscular, and its tail is usually docked. The Barbado da Terceira is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs plenty of exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 20, 'min': 15},
    'female_weight': {'max': 20, 'min': 15},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '4a230092-a25e-4efe-8240-a6693b5405f4',
   'type': 'breed',
   'attributes': {'name': 'Barbet',
    'description': 'The Barbet is an ancient breed of French water dog. They are active, friendly, and highly intelligent, and make great family pets. Barbets have a unique, woolly coat that is curly or wavy and can be any color. They have webbed feet, and are very good swimmers. Barbets bond closely with their family, and do best in homes where they get plenty of attention and exercise.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 30, 'min': 20},
    'female_weight': {'max': 30, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'ab110192-e41b-43ff-a630-f7aee156b33a',
      'type': 'group'}}}},
  {'id': 'edf3d596-e83b-4ba1-972b-d1144a39cf3c',
   'type': 'breed',
   'attributes': {'name': 'Basenji',
    'description': 'The Basenji is a small and agile breed of dog that was originally bred in Africa for hunting small game. They are intelligent, independent, and alert, and make excellent companion dogs.',
    'life': {'max': 16, 'min': 14},
    'male_weight': {'max': 10, 'min': 9},
    'female_weight': {'max': 10, 'min': 9},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': 'c052b615-9502-407f-b46a-845d246d9f22',
   'type': 'breed',
   'attributes': {'name': 'Basset Fauve de Bretagne',
    'description': 'The Basset Fauve de Bretagne is a small and playful breed of dog that was originally bred in France for hunting small game. They are intelligent, affectionate, and loyal, and make excellent companion dogs.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 25, 'min': 20},
    'female_weight': {'max': 25, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': '3e4912ab-bf3c-40cd-8eb9-be1e5999179b',
   'type': 'breed',
   'attributes': {'name': 'Basset Hound',
    'description': 'The Basset Hound is a small and playful breed of dog that was originally bred in France for hunting small game. They are intelligent, affectionate, and loyal, and make excellent companion dogs.',
    'life': {'max': 14, 'min': 12},
    'male_weight': {'max': 29, 'min': 20},
    'female_weight': {'max': 29, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': '406e8454-d350-4187-9788-6d857ee52e06',
   'type': 'breed',
   'attributes': {'name': 'Bavarian Mountain Scent Houn',
    'description': 'The Bavarian Mountain Scent Hound is a medium-sized breed of dog that was originally bred in Germany for hunting small game. They are intelligent, energetic, and determined, and make excellent hunting dogs.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 30, 'min': 20},
    'female_weight': {'max': 30, 'min': 20},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': '8000793f-a1ae-4ec4-8d55-ef83f1f644e5',
      'type': 'group'}}}},
  {'id': 'd8621d92-6558-451c-8631-a32e767026a0',
   'type': 'breed',
   'attributes': {'name': 'Beagle',
    'description': 'The Beagle is a small to medium-sized dog breed that was originally bred for hunting. They are known for their cheerful dispositions and keen sense of smell.',
    'life': {'max': 15, 'min': 12},
    'male_weight': {'max': 11, 'min': 9},
    'female_weight': {'max': 11, 'min': 9},
    'hypoallergenic': False},
   'relationships': {'group': {'data': {'id': 'be0147df-7755-4228-b132-2518c0c6d10d',
      'type': 'group'}}}},
  {'id': '62c29679-0420-4de6-ab88-2b3e99c22317',
   'type': 'breed',
   'attributes': {'name': 'Bearded Collie',

In [20]:
df=pd.json_normalize(json_Data["data"])
df

,id,type,attributes.name,attributes.description,attributes.life.max,attributes.life.min,attributes.male_weight.max,attributes.male_weight.min,attributes.female_weight.max,attributes.female_weight.min,attributes.hypoallergenic,relationships.group.data.id,relationships.group.data.type
0,036feed0-da8a-42c9-ab9a-57449b530b13,breed,Affenpinscher,The Affenpinscher is a small and playful breed...,16,14,5,3,5,3,True,f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c,group
1,dd9362cc-52e0-462d-b856-fccdcf24b140,breed,Afghan Hound,The Afghan Hound is a large and elegant breed ...,14,12,27,23,25,20,False,be0147df-7755-4228-b132-2518c0c6d10d,group
2,1460844f-841c-4de8-b788-271aa4d63224,breed,Airedale Terrier,The Airedale Terrier is a large and powerful b...,14,12,23,20,20,18,False,1bbf373b-1937-4e73-9863-45385daa4979,group
3,e7e99424-d514-4b56-9f0c-05736f6dd22d,breed,Akita,"The Akita is a large, muscular dog breed that ...",12,10,60,35,50,35,False,56081cf0-fdf2-4114-9bf7-23a3f5b6af91,group
4,667c7359-a739-4f2b-abb4-98867671e375,breed,Alaskan Klee Kai,The Alaskan Klee Kai is a small to medium-size...,15,12,7,6,7,6,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,095a1856-6506-478d-a7a8-206847d5e702,breed,Wirehaired Vizsla,The Wirehaired Vizsla is a medium-sized breed ...,15,12,30,25,30,25,False,ab110192-e41b-43ff-a630-f7aee156b33a,group
279,c6b12b96-9f53-445b-8f3e-bf867c761dca,breed,Working Kelpie,The Working Kelpie is a medium-sized breed of ...,15,12,20,16,20,16,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
280,43cdadb4-851b-4a3a-99c1-5f63d08d97f8,breed,Xoloitzcuintli,"The Xoloitzcuintli, also known as the Mexican ...",15,12,15,10,15,10,True,7f6ea988-366a-4e20-b4ba-4d04274fea61,group
281,052684bc-a484-4f29-b953-d5ccf6a3d5e6,breed,Yakutian Laika,The Yakutian Laika is a medium-sized breed of ...,15,12,30,18,30,18,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
282,ce40589c-295a-4259-9e83-711854db8129,breed,Yorkshire Terrier,"The Yorkshire Terrier is a small, intelligent ...",15,12,3,2,3,2,False,f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c,group

In [21]:
df.columns

Index(['id', 'type', 'attributes.name', 'attributes.description',
       'attributes.life.max', 'attributes.life.min',
       'attributes.male_weight.max', 'attributes.male_weight.min',
       'attributes.female_weight.max', 'attributes.female_weight.min',
       'attributes.hypoallergenic', 'relationships.group.data.id',
       'relationships.group.data.type'],
      dtype='object')

# Web Scarping

In [22]:
url="https://www.scrapethissite.com/pages/simple/"

In [23]:
headers={
    "User-Agent":"Mozilla/5.0"
}
res=r.get(url,headers=headers)
res

In [24]:
res.status_code

200

In [25]:
res.headers

{'Date': 'Sun, 01 Feb 2026 08:46:44 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=P8qRlvhvIp0lL4HcVvUJHxbeqWf2dv15xZN%2F19%2FnkBs%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1769935604"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=P8qRlvhvIp0lL4HcVvUJHxbeqWf2dv15xZN%2F19%2FnkBs%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1769935604"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9c702e154c75ce67-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

In [26]:
res.content

b'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="countries">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Countries of the World: A Simple Example\n                            <small>250 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row">\n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ad"></i>\n                            Andorra\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>\n                            <strong>Population:</strong> <span class="country-population">84000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ae"></i>\n                            United Arab Emirates\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>\n                            <strong>Population:</strong> <span class="country-population">4975593</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-af"></i>\n                            Afghanistan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>\n                            <strong>Population:</strong> <span class="country-population">29121286</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ag"></i>\n                            Antigua and Barbuda\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>\n                            <strong>Population:</strong> <span class="country-population">86754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ai"></i>\n                            Anguilla\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>\n                            <strong>Population:</strong> <span class="country-population">13254</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-al"></i>\n                            Albania\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>\n                            <strong>Population:</strong> <span class="country-population">2986952</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-am"></i>\n                            Armenia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>\n                            <strong>Population:</strong> <span class="country-population">2968000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ao"></i>\n                            Angola\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>\n                            <strong>Population:</strong> <span class="country-population">13068161</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aq"></i>\n                            Antarctica\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">None</span><br>\n                            <strong>Population:</strong> <span class="country-population">0</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ar"></i>\n                            Argentina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>\n                            <strong>Population:</strong> <span class="country-population">41343201</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-as"></i>\n                            American Samoa\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>\n                            <strong>Population:</strong> <span class="country-population">57881</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-at"></i>\n                            Austria\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>\n                            <strong>Population:</strong> <span class="country-population">8205000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-au"></i>\n                            Australia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>\n                            <strong>Population:</strong> <span class="country-population">21515754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aw"></i>\n                            Aruba\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>\n                            <strong>Population:</strong> <span class="country-population">71566</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ax"></i>\n                            \xc3\x85land\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>\n                            <strong>Population:</strong> <span class="country-population">26711</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-az"></i>\n                            Azerbaijan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>\n                            <strong>Population:</strong> <span class="country-population">8303512</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ba"></i>\n                            Bosnia and Herzegovina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>\n                            <strong>Population:</strong> <span class="country-population">4590000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-bb"></i>\n                            Barbados\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>\n                            <strong>Population:</strong> <span class="country-population">285653</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-

In [27]:
res.text

'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="countries">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Countries of the World: A Simple Example\n                            <small>250 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row">\n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ad"></i>\n                            Andorra\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>\n                            <strong>Population:</strong> <span class="country-population">84000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ae"></i>\n                            United Arab Emirates\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>\n                            <strong>Population:</strong> <span class="country-population">4975593</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-af"></i>\n                            Afghanistan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>\n                            <strong>Population:</strong> <span class="country-population">29121286</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ag"></i>\n                            Antigua and Barbuda\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>\n                            <strong>Population:</strong> <span class="country-population">86754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ai"></i>\n                            Anguilla\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>\n                            <strong>Population:</strong> <span class="country-population">13254</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-al"></i>\n                            Albania\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>\n                            <strong>Population:</strong> <span class="country-population">2986952</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-am"></i>\n                            Armenia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>\n                            <strong>Population:</strong> <span class="country-population">2968000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ao"></i>\n                            Angola\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>\n                            <strong>Population:</strong> <span class="country-population">13068161</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aq"></i>\n                            Antarctica\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">None</span><br>\n                            <strong>Population:</strong> <span class="country-population">0</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ar"></i>\n                            Argentina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>\n                            <strong>Population:</strong> <span class="country-population">41343201</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-as"></i>\n                            American Samoa\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>\n                            <strong>Population:</strong> <span class="country-population">57881</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-at"></i>\n                            Austria\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>\n                            <strong>Population:</strong> <span class="country-population">8205000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-au"></i>\n                            Australia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>\n                            <strong>Population:</strong> <span class="country-population">21515754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aw"></i>\n                            Aruba\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>\n                            <strong>Population:</strong> <span class="country-population">71566</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ax"></i>\n                            Åland\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>\n                            <strong>Population:</strong> <span class="country-population">26711</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-az"></i>\n                            Azerbaijan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>\n                            <strong>Population:</strong> <span class="country-population">8303512</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ba"></i>\n                            Bosnia and Herzegovina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>\n                            <strong>Population:</strong> <span class="country-population">4590000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-bb"></i>\n                            Barbados\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>\n                            <strong>Population:</strong> <span class="country-population">285653</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 cou

In [28]:
if res.status_code==200:
    print(res.text)
    print(res.content)
    print(res.headers)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="countries">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>
                            <strong>Population:</strong> <span class="country-population">84000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>
                            <strong>Population:</strong> <span class="country-population">4975593</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>
                            <strong>Population:</strong> <span class="country-population">29121286</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>
                            <strong>Population:</strong> <span class="country-population">86754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>
                            <strong>Population:</strong> <span class="country-population">13254</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>
                            <strong>Population:</strong> <span class="country-population">2986952</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>
                            <strong>Population:</strong> <span class="country-population">2968000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>
                            <strong>Population:</strong> <span class="country-population">13068161</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">None</span><br>
                            <strong>Population:</strong> <span class="country-population">0</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>
                            <strong>Population:</strong> <span class="country-population">41343201</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>
                            <strong>Population:</strong> <span class="country-population">57881</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>
                            <strong>Population:</strong> <span class="country-population">8205000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
                            <strong>Population:</strong> <span class="country-population">21515754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>
                            <strong>Population:</strong> <span class="country-population">71566</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>
                            <strong>Population:</strong> <span class="country-population">26711</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>
                            <strong>Population:</strong> <span class="country-population">8303512</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>
                            <strong>Population:</strong> <span class="country-population">4590000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>
                            <strong>Population:</strong> <span class="country-population">285653</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br>
                            <strong>Population:</strong> <span class="country-population">156118464</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Brussels</span><br>
                            <strong>Population:</strong> <span class="country-population">10403000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br>

In [29]:
with open("scraped_data/data1.html","w") as f:
    f.write(res.text)

# Practice Q1

In [30]:
url="https://www.scrapethissite.com/pages/forms/"

In [31]:
headers={
    "User-Agent":"Mozilla/5.0"}
res=r.get(url,headers=headers)
res

In [32]:
res.status_code

200

In [33]:
res.text

'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="hockey">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Hockey Teams: Forms, Searching and Pagination\n                            <small>25 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.\n                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://www.opensourcesports.com/hockey/" class="data-attribution" target="_blank">http://www.opensourcesports.com/hockey/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row search-area">\n                    <div class="col-md-12 text-center">\n                        <form method="GET" action="/pages/forms/" class="form form-inline">\n                            <label for="q">\n                                Search for Teams: &nbsp;\n                            </label>\n                            <input type="text" class="form-control" name="q" id="q" placeholder="Search for Teams" />\n                            \n                            <input type="submit" class="btn btn-primary" value="Search" />\n                        </form>\n                        <hr>\n                    </div>\n                </div><!--.row.search-area-->\n\n\n                <table class="table">\n                    <tr>\n                        <th>\n                            Team Name\n                        </th>\n                        <th>\n                            Year\n                        </th>\n                        <th>\n                            Wins\n                        </th>\n                        <th>\n                            Losses\n                        </th>\n                        <th>\n                            OT Losses\n                        </th>\n                        <th>\n                            Win %\n                        </th>\n                        <th>\n                            Goals For (GF)\n                        </th>\n                        <th>\n                            Goals Against (GA)\n                        </th>\n                        <th>\n                            + / -\n                        </th>\n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Boston Bruins\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            44\n                        </td>\n                        <td class="losses">\n                            24\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.55\n                        </td>\n                        \n                        <td class="gf">\n                            299\n                        </td>\n                        <td class="ga">\n                            264\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            35\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Buffalo Sabres\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            31\n                        </td>\n                        <td class="losses">\n                            30\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.388\n                        </td>\n                        \n                        <td class="gf">\n                            292\n                        </td>\n                        <td class="ga">\n                            278\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            14\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Calgary Flames\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            46\n                        </td>\n                        <td class="losses">\n                            26\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.575\n                        </td>\n                        \n                        <td class="gf">\n                            344\n                        </td>\n                        <td class="ga">\n                            263\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            81\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Chicago Blackhawks\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            49\n                        </td>\n                        <td class="losses">\n                            23\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.613\n                        </td>\n                        \n                        <td class="gf">\n                            284\n                        </td>\n                        <td class="ga">\n                            211\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            73\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Detroit Red Wings\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            34\n                        </td>\n                        <td class="losses">\n                            38\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.425\n                        </td>\n                        \n                        <td class="gf">\n                            273\n                        </td>\n                        <td class="ga">\n                            298\n                        </td>\n                        \n                        \n                        <td class="diff text-danger">\n                            -25\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Edmonton Oilers\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            37\n                        </td>\n                        <td class="losses">\n                            37\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.463\n                        </td>\n                        \n                        <td class="gf">\n                            272\n                        </td>\n                        <td class="ga">\n                            272\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            0\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Hartford Whalers\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            31\n                        </td>\n                        <td class="losses">\n                            38\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.388\n                        </td>\n                        \n                        <td class="gf">\n                            238\n                        </td>\n                        <td class="ga">\n                            276\n                        </td>\n                        \n                        \n                        <td class="diff text-danger">\n                            -38\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Los Angeles Kings\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            46\n                        </td>\n                        <td class="losses">\n                            24\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.575\n                        </td>\n                        \n                        <td class="gf">\n                            340\n                        </td>\n                        <td class="ga">\n                            254\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            86\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Minnesota North Stars\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            27\n                        </td>\n                        <td class="losses">\n                            39\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.338\n                        </td>\n                        \n                        <td class="gf">\n                            256\n                        </td>\n                        <td class="ga">\n                            266\n                        </td>\n                        \n                        \n                        <td class="diff text-danger">\n                            -10\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Montreal Canadiens\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            39\n                        </td>\n                        <td class="losses">\n                            30\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.487\n                        </td>\n                        \n                        <td class="gf">\n                            273\n                        </td>\n                        <td class="ga">\n                            249\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            24\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            New Jersey Devils\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td 

In [34]:
with open("scraped_data/data2.html","w") as f:
    f.write(res.text)

# Practice Q2

In [35]:
url="https://www.scrapethissite.com/pages/advanced/"

In [36]:
headers={
    "User-Agent":"Mozilla/5.0"
}
res=r.get(url,headers=headers)
res

In [37]:
res.text

'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Advanced Topics: Real World Challenges You&#39;ll Encounter | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="Scraping real websites, you&#39;re likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    \n\n        <div id="page">\n\n            <section id="gotchas">\n                <div class="container">\n                    <div class="row">\n                        <div class="col-md-6 col-md-offset-3">\n                            <h3>Advanced Topics: Real World Challenges You&#39;ll Encounter</h3>\n                            <p class="lead">\n                                Scraping real websites, you&#39;re likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.\n                            </p>\n                            <hr>\n\n                            \n                            <h4>\n                                <a href="/pages/advanced/?gotcha=headers" target="_blank">Spoofing Headers</a>\n                            </h4>\n                            <p>\n                                Sometimes you need to make your web scraper appear to be making HTTP requests as a browser in order to get the web server to return the same data that you see in your browser.\n                            </p>\n                            <hr>\n                            \n                            <h4>\n                                <a href="/pages/advanced/?gotcha=login" target="_blank">Logins &amp; Session Data</a>\n                            </h4>\n                            <p>\n                                Submit some data in one request, get a session cookie back from the site, and then be sure to send that cookie back on subsequent requests so you stay &#34;logged in&#34; between requests.\n                            </p>\n                            <hr>\n                            \n                            <h4>\n                                <a href="/pages/advanced/?gotcha=csrf" target="_blank">CSRF &amp; Hidden Values</a>\n                            </h4>\n                            <p>\n                                Some forms require hidden values to be submitted, not just the fields that have text fields. Load the login page, grab all the hidden value, then submit them with the rest of the form fields.\n                            </p>\n                            <hr>\n                            \n\n                        </div><!--.col-->\n                    </div><!--.row-->\n\n                </div><!--.container-->\n            </section>\n\n        </div><!--#page-->\n\n    \n\n\n    <section id="footer">\n        <div class="container">\n            <div class="row">\n                <div class="col-md-12 text-center text-muted">\n                    Lessons and Videos &copy; Hartley Brody 2023\n                </div><!--.col-->\n            </div><!--.row-->\n        </div><!--.container-->\n    </section>\n  </body>\n\n  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>\n  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>\n\n  \n\n  <script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>\n  <link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css">\n\n  <!-- pnotify messages -->\n  <script type="text/javascript">\n    \n    PNotify.prototype.options.styling = "bootstrap3";\n    $(function(){\n      \n    });\n    \n\n    $(function () {\n      $(\'[data-toggle="tooltip"]\').tooltip()\n    })\n  </script>\n\n  <!-- golbal video controls -->\n  <script type="text/javascript">\n    $("video").hover(function() {\n        $(this).prop("controls", true);\n    }, function() {\n        $(this).prop("controls", false);\n    });\n\n    $("video").click(function() {\n        if( this.paused){\n            this.play();\n        }\n        else {\n            this.pause();\n        }\n    });\n    </script>\n\n  <!-- insert google analytics here -->\n  <script>\n    (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){\n    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n    })(window,document,\'script\',\'https://www.google-analytics.com/analytics.js\',\'ga\');\n\n    ga(\'create\', \'UA-41551755-8\', \'auto\');\n    ga(\'send\', \'pageview\');\n  </script>\n\n  <!-- Facebook Pixel Code -->\n  <script>\n  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?\n  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;\n  n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;\n  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,\n  document,\'script\',\'https://connect.facebook.net/en_US/fbevents.js\');\n\n  fbq(\'init\', \'764287443701341\');\n  fbq(\'track\', "PageView");</script>\n  <noscript><img height="1" width="1" style="display:none"\n  src="https://www.facebook.com/tr?id=764287443701341&ev=PageView&noscript=1"\n  /></noscript>\n  <!-- End Facebook Pixel Code -->\n\n  <!-- Google Code for Remarketing Tag -->\n  <script type="text/javascript">\n    /* <![CDATA[ */\n    var google_conversion_id = 950945448;\n    var google_custom_params = window.google_tag_params;\n    var google_remarketing_only = true;\n    /* ]]> */\n    </script>\n    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">\n    </script>\n    <noscript>\n    <div style="display:inline;">\n    <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0"/>\n    </div>\n  </noscript>\n\n  <!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->\n  <script async src="https://www.googletagmanager.com/gtag/js?id=AW-950945448"></script>\n  <script>\n   window.dataLayer = window.dataLayer || [];\n   function gtag(){dataLayer.push(arguments);}\n   gtag(\'js\', new Date());\n\n   gtag(\'config\', \'AW-950945448\');\n  </script>\n\n</html>'

In [38]:
with open("scraped_data/data3.html","w") as f:
    f.write(res.text)

# Practice Again

In [39]:
url="https://meowfacts.herokuapp.com/"

In [40]:
res=r.get(url)

In [41]:
data=res.json()

In [42]:
data

{'data': ['The Maine Coon is 4 to 5 times larger than the Singapura, the smallest breed of cat.']}

In [43]:
df=pd.json_normalize(data)

In [44]:
df

                                                data
0  [The Maine Coon is 4 to 5 times larger than th...

In [45]:
url="https://x-colors.yurace.pro/api/random"

In [46]:
res=r.get(url)

In [47]:
res

In [48]:
res.text

'{"hex":"#BEDB13","rgb":"rgb(190, 219, 19)","hsl":"hsl(69, 84%, 47%)"}'

In [49]:
data=res.json()

In [50]:
data

{'hex': '#BEDB13', 'rgb': 'rgb(190, 219, 19)', 'hsl': 'hsl(69, 84%, 47%)'}

In [51]:
df=pd.json_normalize(data)

In [52]:
df

       hex                rgb                hsl
0  #BEDB13  rgb(190, 219, 19)  hsl(69, 84%, 47%)

# --------------------------------------------

In [53]:
url="https://www.scrapethissite.com/pages/simple/"

In [54]:
headers={
    "User-Agent":"Mozilla/5.0"
}

In [55]:
res=r.get(url,headers)

In [56]:
res

In [57]:
print(res.text)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="countries">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>
                            <strong>Population:</strong> <span class="country-population">84000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>
                            <strong>Population:</strong> <span class="country-population">4975593</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>
                            <strong>Population:</strong> <span class="country-population">29121286</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>
                            <strong>Population:</strong> <span class="country-population">86754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>
                            <strong>Population:</strong> <span class="country-population">13254</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>
                            <strong>Population:</strong> <span class="country-population">2986952</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>
                            <strong>Population:</strong> <span class="country-population">2968000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>
                            <strong>Population:</strong> <span class="country-population">13068161</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">None</span><br>
                            <strong>Population:</strong> <span class="country-population">0</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>
                            <strong>Population:</strong> <span class="country-population">41343201</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>
                            <strong>Population:</strong> <span class="country-population">57881</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>
                            <strong>Population:</strong> <span class="country-population">8205000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
                            <strong>Population:</strong> <span class="country-population">21515754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>
                            <strong>Population:</strong> <span class="country-population">71566</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>
                            <strong>Population:</strong> <span class="country-population">26711</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>
                            <strong>Population:</strong> <span class="country-population">8303512</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>
                            <strong>Population:</strong> <span class="country-population">4590000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>
                            <strong>Population:</strong> <span class="country-population">285653</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br>
                            <strong>Population:</strong> <span class="country-population">156118464</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Brussels</span><br>
                            <strong>Population:</strong> <span class="country-population">10403000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br>

In [58]:
res.content

b'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="countries">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Countries of the World: A Simple Example\n                            <small>250 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row">\n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ad"></i>\n                            Andorra\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>\n                            <strong>Population:</strong> <span class="country-population">84000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ae"></i>\n                            United Arab Emirates\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>\n                            <strong>Population:</strong> <span class="country-population">4975593</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-af"></i>\n                            Afghanistan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>\n                            <strong>Population:</strong> <span class="country-population">29121286</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ag"></i>\n                            Antigua and Barbuda\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>\n                            <strong>Population:</strong> <span class="country-population">86754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ai"></i>\n                            Anguilla\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>\n                            <strong>Population:</strong> <span class="country-population">13254</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-al"></i>\n                            Albania\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>\n                            <strong>Population:</strong> <span class="country-population">2986952</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-am"></i>\n                            Armenia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>\n                            <strong>Population:</strong> <span class="country-population">2968000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ao"></i>\n                            Angola\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>\n                            <strong>Population:</strong> <span class="country-population">13068161</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aq"></i>\n                            Antarctica\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">None</span><br>\n                            <strong>Population:</strong> <span class="country-population">0</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ar"></i>\n                            Argentina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>\n                            <strong>Population:</strong> <span class="country-population">41343201</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-as"></i>\n                            American Samoa\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>\n                            <strong>Population:</strong> <span class="country-population">57881</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-at"></i>\n                            Austria\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>\n                            <strong>Population:</strong> <span class="country-population">8205000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-au"></i>\n                            Australia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>\n                            <strong>Population:</strong> <span class="country-population">21515754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aw"></i>\n                            Aruba\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>\n                            <strong>Population:</strong> <span class="country-population">71566</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ax"></i>\n                            \xc3\x85land\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>\n                            <strong>Population:</strong> <span class="country-population">26711</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-az"></i>\n                            Azerbaijan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>\n                            <strong>Population:</strong> <span class="country-population">8303512</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ba"></i>\n                            Bosnia and Herzegovina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>\n                            <strong>Population:</strong> <span class="country-population">4590000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-bb"></i>\n                            Barbados\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>\n                            <strong>Population:</strong> <span class="country-population">285653</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-

In [59]:
res.status_code

200

In [60]:
res.headers

{'Date': 'Sun, 01 Feb 2026 08:46:51 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=aGZnNluwTb1P1hlpEXQg0jBz44DAb8YfHlBM7AvxI5k%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1769935611"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=aGZnNluwTb1P1hlpEXQg0jBz44DAb8YfHlBM7AvxI5k%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1769935611"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9c702e4279dace49-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

In [61]:
with open("scraped_data/data4.html","w") as f:
    f.write(res.text)

In [62]:
url="https://www.scrapethissite.com/pages/simple/"

In [67]:
headers={
    "User-Agent":"Mozilla/5.0"
}

In [68]:
res=r.get(url,headers)

In [69]:
res

In [70]:
res.text

'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="countries">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Countries of the World: A Simple Example\n                            <small>250 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row">\n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ad"></i>\n                            Andorra\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>\n                            <strong>Population:</strong> <span class="country-population">84000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ae"></i>\n                            United Arab Emirates\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>\n                            <strong>Population:</strong> <span class="country-population">4975593</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-af"></i>\n                            Afghanistan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>\n                            <strong>Population:</strong> <span class="country-population">29121286</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ag"></i>\n                            Antigua and Barbuda\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>\n                            <strong>Population:</strong> <span class="country-population">86754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ai"></i>\n                            Anguilla\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>\n                            <strong>Population:</strong> <span class="country-population">13254</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-al"></i>\n                            Albania\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>\n                            <strong>Population:</strong> <span class="country-population">2986952</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-am"></i>\n                            Armenia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>\n                            <strong>Population:</strong> <span class="country-population">2968000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ao"></i>\n                            Angola\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>\n                            <strong>Population:</strong> <span class="country-population">13068161</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aq"></i>\n                            Antarctica\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">None</span><br>\n                            <strong>Population:</strong> <span class="country-population">0</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ar"></i>\n                            Argentina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>\n                            <strong>Population:</strong> <span class="country-population">41343201</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-as"></i>\n                            American Samoa\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>\n                            <strong>Population:</strong> <span class="country-population">57881</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-at"></i>\n                            Austria\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>\n                            <strong>Population:</strong> <span class="country-population">8205000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-au"></i>\n                            Australia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>\n                            <strong>Population:</strong> <span class="country-population">21515754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aw"></i>\n                            Aruba\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>\n                            <strong>Population:</strong> <span class="country-population">71566</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ax"></i>\n                            Åland\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>\n                            <strong>Population:</strong> <span class="country-population">26711</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-az"></i>\n                            Azerbaijan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>\n                            <strong>Population:</strong> <span class="country-population">8303512</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ba"></i>\n                            Bosnia and Herzegovina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>\n                            <strong>Population:</strong> <span class="country-population">4590000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-bb"></i>\n                            Barbados\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>\n                            <strong>Population:</strong> <span class="country-population">285653</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 cou

In [71]:
if res.status_code==200:
    with open("scraped_data/data5.html","w")  as f:
        f.write(res.text)

# ______________________________________________________________________

In [72]:
url="https://www.scrapethissite.com/pages/forms/"

In [73]:
headers={
    "User-Agent":"Mozilla/5.0"
}

In [74]:
res=r.get(url,headers)

In [75]:
res

In [76]:
res.text

'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="hockey">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Hockey Teams: Forms, Searching and Pagination\n                            <small>25 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.\n                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://www.opensourcesports.com/hockey/" class="data-attribution" target="_blank">http://www.opensourcesports.com/hockey/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row search-area">\n                    <div class="col-md-12 text-center">\n                        <form method="GET" action="/pages/forms/" class="form form-inline">\n                            <label for="q">\n                                Search for Teams: &nbsp;\n                            </label>\n                            <input type="text" class="form-control" name="q" id="q" placeholder="Search for Teams" />\n                            \n                            <input type="submit" class="btn btn-primary" value="Search" />\n                        </form>\n                        <hr>\n                    </div>\n                </div><!--.row.search-area-->\n\n\n                <table class="table">\n                    <tr>\n                        <th>\n                            Team Name\n                        </th>\n                        <th>\n                            Year\n                        </th>\n                        <th>\n                            Wins\n                        </th>\n                        <th>\n                            Losses\n                        </th>\n                        <th>\n                            OT Losses\n                        </th>\n                        <th>\n                            Win %\n                        </th>\n                        <th>\n                            Goals For (GF)\n                        </th>\n                        <th>\n                            Goals Against (GA)\n                        </th>\n                        <th>\n                            + / -\n                        </th>\n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Boston Bruins\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            44\n                        </td>\n                        <td class="losses">\n                            24\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.55\n                        </td>\n                        \n                        <td class="gf">\n                            299\n                        </td>\n                        <td class="ga">\n                            264\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            35\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Buffalo Sabres\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            31\n                        </td>\n                        <td class="losses">\n                            30\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.388\n                        </td>\n                        \n                        <td class="gf">\n                            292\n                        </td>\n                        <td class="ga">\n                            278\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            14\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Calgary Flames\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            46\n                        </td>\n                        <td class="losses">\n                            26\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.575\n                        </td>\n                        \n                        <td class="gf">\n                            344\n                        </td>\n                        <td class="ga">\n                            263\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            81\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Chicago Blackhawks\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            49\n                        </td>\n                        <td class="losses">\n                            23\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.613\n                        </td>\n                        \n                        <td class="gf">\n                            284\n                        </td>\n                        <td class="ga">\n                            211\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            73\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Detroit Red Wings\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            34\n                        </td>\n                        <td class="losses">\n                            38\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.425\n                        </td>\n                        \n                        <td class="gf">\n                            273\n                        </td>\n                        <td class="ga">\n                            298\n                        </td>\n                        \n                        \n                        <td class="diff text-danger">\n                            -25\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Edmonton Oilers\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            37\n                        </td>\n                        <td class="losses">\n                            37\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.463\n                        </td>\n                        \n                        <td class="gf">\n                            272\n                        </td>\n                        <td class="ga">\n                            272\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            0\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Hartford Whalers\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            31\n                        </td>\n                        <td class="losses">\n                            38\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.388\n                        </td>\n                        \n                        <td class="gf">\n                            238\n                        </td>\n                        <td class="ga">\n                            276\n                        </td>\n                        \n                        \n                        <td class="diff text-danger">\n                            -38\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Los Angeles Kings\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            46\n                        </td>\n                        <td class="losses">\n                            24\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-success">\n                            0.575\n                        </td>\n                        \n                        <td class="gf">\n                            340\n                        </td>\n                        <td class="ga">\n                            254\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            86\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Minnesota North Stars\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            27\n                        </td>\n                        <td class="losses">\n                            39\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.338\n                        </td>\n                        \n                        <td class="gf">\n                            256\n                        </td>\n                        <td class="ga">\n                            266\n                        </td>\n                        \n                        \n                        <td class="diff text-danger">\n                            -10\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            Montreal Canadiens\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td class="wins">\n                            39\n                        </td>\n                        <td class="losses">\n                            30\n                        </td>\n                        <td class="ot-losses">\n                            \n                        </td>\n                        \n                        \n                        <td class="pct text-danger">\n                            0.487\n                        </td>\n                        \n                        <td class="gf">\n                            273\n                        </td>\n                        <td class="ga">\n                            249\n                        </td>\n                        \n                        \n                        <td class="diff text-success">\n                            24\n                        </td>\n                        \n                    </tr>\n                    \n                    <tr class="team">\n                        <td class="name">\n                            New Jersey Devils\n                        </td>\n                        <td class="year">\n                            1990\n                        </td>\n                        <td 

In [77]:
with open("scraped_data/data6.html","w") as f:
    f.write(res.text)

# ____________________________________________________________________________

In [91]:
url = "https://www.scrapethissite.com/pages/ajax-javascript/"

In [97]:
params = {
    "ajax": "true",
    "year": 2015
}

In [98]:
res=r.get(url,params=params)

In [99]:
res

In [100]:
res.text

'[\n  {\n    "title": "Spotlight  ",\n    "year": 2015,\n    "awards": 2,\n    "nominations": 6,\n    "best_picture": true\n  },\n  {\n    "title": "Mad Max: Fury Road ",\n    "year": 2015,\n    "awards": 6,\n    "nominations": 10\n  },\n  {\n    "title": "The Revenant   ",\n    "year": 2015,\n    "awards": 3,\n    "nominations": 12\n  },\n  {\n    "title": "Bridge of Spies",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 6\n  },\n  {\n    "title": "The Big Short  ",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 5\n  },\n  {\n    "title": "The Danish Girl",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 4\n  },\n  {\n    "title": "Room   ",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 4\n  },\n  {\n    "title": "Ex Machina ",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 2\n  },\n  {\n    "title": "The Hateful Eight  ",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 2\n  },\n  {\n    "title": "Inside Out ",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 2\n  },\n  {\n    "title": "Amy",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 1\n  },\n  {\n    "title": "Bear Story ",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 1\n  },\n  {\n    "title": "A Girl in the River: The Price of Forgiveness  ",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 1\n  },\n  {\n    "title": "Son of Saul",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 1\n  },\n  {\n    "title": "Spectre",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 1\n  },\n  {\n    "title": "Stutterer  ",\n    "year": 2015,\n    "awards": 1,\n    "nominations": 1\n  }\n]'

In [101]:
with open("scraped_data/data7.html","w") as f:
    f.write(res.text)

In [104]:
data=res.json()

In [107]:
df=pd.DataFrame(data)

In [108]:
df

,title,year,awards,nominations,best_picture
0,Spotlight,2015,2,6,True
1,Mad Max: Fury Road,2015,6,10,NaN
2,The Revenant,2015,3,12,NaN
3,Bridge of Spies,2015,1,6,NaN
4,The Big Short,2015,1,5,NaN
5,The Danish Girl,2015,1,4,NaN
6,Room,2015,1,4,NaN
7,Ex Machina,2015,1,2,NaN
8,The Hateful Eight,2015,1,2,NaN
9,Inside Out,2015,1,2,NaN
10,Amy,2015,1,1,NaN
11,Bear Story,2015,1,1,NaN
12,A Girl in the River: The Price of Forgiveness,2015,1,1,NaN
13,Son of Saul,2015,1,1,NaN
14,Spectre,2015,1,1,NaN
15,Stutterer,2015,1,1,NaN

# ____________________________________

In [109]:
url="https://www.scrapethissite.com/pages/frames/"

In [110]:
headers={
    "User-Agent":"Mozilla/5.0"
}

In [111]:
res=r.get(url,headers)

In [112]:
res

In [113]:
res.text

'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Turtles All the Way Down: Frames &amp; iFrames | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    \n\n        <div id="page">\n\n            <section id="frames">\n                <div class="container">\n\n                    <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Turtles All the Way Down: Frames &amp; iFrames\n                            <small>14 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.\n                            See if you can find the &#39;real&#39; URL that our content is being loaded from, and scrape that page. Also practice interating over a list of items and loading their detail pages to get more information about each one.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">3 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="https://en.wikipedia.org/wiki/List_of_Testudines_families" class="data-attribution" target="_blank">https://en.wikipedia.org/wiki/List_of_Testudines_families</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                    <div class="row">\n                        <div class="col-md-12">\n                            <frameset rows="10%,80%,10%">\n                                <frame name="top" src="/pages/frames/?frame=top" />\n                                <frame name="main" src="/pages/frames/?frame=main" />\n                                <frame name="bottom" src="/pages/frames/frame=bottom" />\n                                <noframes>\n                                        Your browser does not support frames.\n                                </noframes>\n                            </frameset>\n\n                            <iframe src="/pages/frames/?frame=i" id="iframe">\n                                Your browser does not support iframes\n                            </iframe>\n\n                        </div><!--.col-->\n                    </div><!--.row-->\n\n                </div><!--.container-->\n            </section>\n\n        </div><!--#page-->\n\n    \n\n\n    <section id="footer">\n        <div class="container">\n            <div class="row">\n                <div class="col-md-12 text-center text-muted">\n                    Lessons and Videos &copy; Hartley Brody 2023\n                </div><!--.col-->\n            </div><!--.row-->\n        </div><!--.container-->\n    </section>\n  </body>\n\n  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>\n  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>\n\n  \n\n  <script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>\n  <link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css">\n\n  <!-- pnotify messages -->\n  <script type="text/javascript">\n    \n    PNotify.prototype.options.styling = "bootstrap3";\n    $(function(){\n      \n    });\n    \n\n    $(function () {\n      $(\'[data-toggle="tooltip"]\').tooltip()\n    })\n  </script>\n\n  <!-- golbal video controls -->\n  <script type="text/javascript">\n    $("video").hover(function() {\n        $(this).prop("controls", true);\n    }, function() {\n        $(this).prop("controls", false);\n    });\n\n    $("video").click(function() {\n        if( this.paused){\n            this.play();\n        }\n        else {\n            this.pause();\n        }\n    });\n    </script>\n\n  <!-- insert google analytics here -->\n  <script>\n    (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){\n    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n    })(window,document,\'script\',\'https://www.google-analytics.com/analytics.js\',\'ga\');\n\n    ga(\'create\', \'UA-41551755-8\', \'auto\');\n    ga(\'send\', \'pageview\');\n  </script>\n\n  <!-- Facebook Pixel Code -->\n  <script>\n  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?\n  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;\n  n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;\n  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,\n  document,\'script\',\'https://connect.facebook.net/en_US/fbevents.js\');\n\n  fbq(\'init\', \'764287443701341\');\n  fbq(\'track\', "PageView");</script>\n  <noscript><img height="1" width="1" style="display:none"\n  src="https://www.facebook.com/tr?id=764287443701341&ev=PageView&noscript=1"\n  /></noscript>\n  <!-- End Facebook Pixel Code -->\n\n  <!-- Google Code for Remarketing Tag -->\n  <script type="text/javascript">\n    /* <![CDATA[ */\n    var google_conversion_id = 950945448;\n    var google_custom_params = window.google_tag_params;\n    var google_remarketing_only = true;\n    /* ]]> */\n    </script>\n    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">\n    </script>\n    <noscript>\n    <div style="display:inline;">\n    <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0"/>\n    </div>\n  </noscript>\n\n  <!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->\n  <script async src="https://www.googletagmanager.com/gtag/js?id=AW-950945448"></script>\n  <script>\n   window.dataLayer = window.dataLayer || [];\n   function gtag(){dataLayer.push(arguments);}\n   gtag(\'js\', new Date());\n\n   gtag(\'config\', \'AW-950945448\');\n  </script>\n\n</html>'

In [114]:
with open("scraped_data/data8.html","w") as f:
    f.write(res.text)

# ___________________________________________________

In [115]:
url="https://www.scrapethissite.com/pages/advanced/"

In [116]:
headers={
    "User-Agent":"Mozilla/5.0"
}

In [117]:
res=r.get(url,headers)

In [118]:
res

In [119]:
with open("scraped_data/data10.html","w") as f:
    f.write(res.text)